use super::*;

// ===========================================================================
// HTML asset index
// ===========================================================================

pub(super) fn write_html_index(out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let dialogue_rows = read_tsv_rows(&out_dir.join("script-dialogue-videos.tsv"));
    let executed_rows = read_tsv_rows(&out_dir.join("script-executed-dialogue.tsv"));
    let scene_rows = read_tsv_rows(&out_dir.join("verified-video-scenes.tsv"));
    let mp4_files = output_files(out_dir, "mp4", "mp4");
    let m4a_files = output_files(out_dir, "m4a", "m4a");
    let flac_files = output_files(out_dir, "flac", "flac");

    let mut html = String::new();
    writeln!(
        html,
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>Commander Blood Media</title>"
    )?;
    writeln!(
        html,
        "<style>
body {{ font: 14px/1.35 system-ui, sans-serif; margin: 24px; background: #111; color: #eee; }}
a {{ color: #8ec7ff; }}
h1, h2, h3 {{ margin: 1.2em 0 0.45em; }}
table {{ width: 100%; border-collapse: collapse; margin: 0.5em 0 1.5em; }}
th, td {{ border-bottom: 1px solid #333; padding: 6px 8px; vertical-align: top; text-align: left; }}
th {{ color: #bbb; font-weight: 600; }}
video {{ width: 960px; max-width: 100%; height: auto; image-rendering: pixelated; background: #000; }}
audio {{ width: 260px; }}
.grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(980px, 1fr)); gap: 16px; }}
@media (max-width: 1040px) {{ .grid {{ grid-template-columns: 1fr; }} }}
.card {{ border: 1px solid #333; border-radius: 6px; padding: 10px; background: #181818; }}
.meta {{ color: #aaa; font-size: 12px; }}
details {{ margin: 0.5em 0; border: 1px solid #333; border-radius: 6px; padding: 8px 10px; background: #181818; }}
summary {{ cursor: pointer; font-weight: 600; }}
</style></head><body>"
    )?;
    writeln!(html, "<h1>Commander Blood Media Export</h1>")?;
    writeln!(
        html,
        "<p class=\"meta\">{} MP4, {} M4A, {} FLAC files. Generated by commander-blood-tools.</p>",
        mp4_files.len(),
        m4a_files.len(),
        flac_files.len()
    )?;

    write_dialogue_section(&mut html, &dialogue_rows, &executed_rows, out_dir)?;
    write_scene_section(&mut html, &scene_rows, out_dir)?;
    write_music_section(&mut html, &m4a_files, out_dir)?;
    write_snd_section(&mut html, &m4a_files, out_dir)?;
    write_manifest_section(&mut html, out_dir)?;

    writeln!(html, "</body></html>")?;
    fs::write(out_dir.join("index.html"), html)?;
    Ok(())
}

pub(super) fn write_dialogue_section(
    html: &mut String,
    rows: &[Vec<String>],
    executed_rows: &[Vec<String>],
    out_dir: &Path,
) -> Result<(), Box<dyn Error>> {
    writeln!(html, "<h2>Character Dialogue Composites</h2>")?;
    let mapped_speech_rows = executed_rows
        .iter()
        .filter(|row| row.get(12).is_some_and(|clip| !clip.is_empty()))
        .count();
    if !executed_rows.is_empty() {
        writeln!(
            html,
            "<p class=\"meta\">{} branch-aware executed script speech/subtitle rows; {} rows have mapped character voice clips and are grouped into {} exported dialogue composite(s). Rows without clip indices are subtitle-only or non-character subtitle channels.</p>",
            executed_rows.len(),
            mapped_speech_rows,
            rows.len()
        )?;
    }
    let mut by_actor: BTreeMap<String, Vec<&[String]>> = BTreeMap::new();
    for row in rows {
        if row.len() < 9 {
            continue;
        }
        let rel = format!("mp4/{}", row[0]);
        if out_dir.join(&rel).exists() {
            by_actor.entry(row[3].clone()).or_default().push(row);
        }
    }

    if by_actor.is_empty() {
        writeln!(
            html,
            "<p class=\"meta\">No dialogue composites exported.</p>"
        )?;
        return Ok(());
    }

    for (actor, actor_rows) in by_actor {
        writeln!(html, "<h3>{}</h3><div class=\"grid\">", html_escape(&actor))?;
        for row in actor_rows {
            let rel = format!("mp4/{}", row[0]);
            writeln!(html, "<div class=\"card\">")?;
            write_video(html, &rel)?;
            writeln!(
                html,
                "<div><a href=\"{}\">{}</a></div>",
                url_escape(&rel),
                html_escape(&row[0])
            )?;
            writeln!(
                html,
                "<div class=\"meta\">{} / {}<br>background: {} ({})<br>music: {}<br>clips: {}</div>",
                html_escape(&row[1]),
                html_escape(&row[2]),
                html_escape(&row[4]),
                html_escape(&row[5]),
                html_escape(&row[6]),
                html_escape(&row[8])
            )?;
            writeln!(html, "</div>")?;
        }
        writeln!(html, "</div>")?;
    }
    Ok(())
}

pub(super) fn write_scene_section(
    html: &mut String,
    rows: &[Vec<String>],
    out_dir: &Path,
) -> Result<(), Box<dyn Error>> {
    writeln!(html, "<h2>Verified Scene Videos</h2>")?;
    writeln!(
        html,
        "<table><thead><tr><th>Video</th><th>Record</th><th>Music</th><th>HNM</th><th>Subtitles</th></tr></thead><tbody>"
    )?;
    for row in rows {
        if row.len() < 9 || row[5] != "ok" {
            continue;
        }
        let record = &row[0];
        let rel = format!("mp4/scene - {}.mp4", safe_file_stem(record));
        if !out_dir.join(&rel).exists() {
            continue;
        }
        let subtitle_rel = format!("subtitles/{}.srt", safe_file_stem(record));
        let subtitle_link = if out_dir.join(&subtitle_rel).exists() {
            format!(
                "<a href=\"{}\">{} cues</a>",
                url_escape(&subtitle_rel),
                html_escape(&row[7])
            )
        } else {
            html_escape(&row[7])
        };
        writeln!(
            html,
            "<tr><td><a href=\"{}\">{}</a></td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            url_escape(&rel),
            html_escape(&rel),
            html_escape(record),
            html_escape(&row[2]),
            html_escape(&row[4]),
            subtitle_link
        )?;
    }
    writeln!(html, "</tbody></table>")?;
    Ok(())
}

pub(super) fn write_music_section(
    html: &mut String,
    m4a_files: &[String],
    out_dir: &Path,
) -> Result<(), Box<dyn Error>> {
    writeln!(html, "<h2>Music</h2>")?;
    writeln!(
        html,
        "<table><thead><tr><th>Name</th><th>Preview</th><th>Files</th></tr></thead><tbody>"
    )?;
    for rel in m4a_files.iter().filter(|rel| rel.starts_with("m4a/mu - ")) {
        let name = rel
            .strip_prefix("m4a/mu - ")
            .unwrap_or(rel)
            .trim_end_matches(".m4a");
        let flac = rel.replacen("m4a/", "flac/", 1).replace(".m4a", ".flac");
        let flac_link = if out_dir.join(&flac).exists() {
            format!(" | <a href=\"{}\">FLAC</a>", url_escape(&flac))
        } else {
            String::new()
        };
        writeln!(
            html,
            "<tr><td>{}</td><td><audio controls preload=\"none\" src=\"{}\"></audio></td><td><a href=\"{}\">M4A</a>{}</td></tr>",
            html_escape(name),
            url_escape(rel),
            url_escape(rel),
            flac_link
        )?;
    }
    writeln!(html, "</tbody></table>")?;
    Ok(())
}

pub(super) fn write_snd_section(
    html: &mut String,
    m4a_files: &[String],
    out_dir: &Path,
) -> Result<(), Box<dyn Error>> {
    writeln!(html, "<h2>Sound Effects And Voice Banks</h2>")?;
    let mut by_bank: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for rel in m4a_files.iter().filter(|rel| rel.starts_with("m4a/sn - ")) {
        if let Some((bank, clip)) = snd_audio_key(rel) {
            by_bank.entry(bank).or_default().push((clip, rel.clone()));
        }
    }

    for (bank, mut clips) in by_bank {
        clips.sort_by(|a, b| a.0.cmp(&b.0));
        let heading = if bank.eq_ignore_ascii_case("tb") {
            format!("{bank} subtitle/UI SFX")
        } else {
            bank.clone()
        };
        writeln!(
            html,
            "<details{}><summary>{} ({} clips)</summary>",
            if bank.eq_ignore_ascii_case("tb") {
                " open"
            } else {
                ""
            },
            html_escape(&heading),
            clips.len()
        )?;
        writeln!(
            html,
            "<table><thead><tr><th>Clip</th><th>Preview</th><th>Files</th></tr></thead><tbody>"
        )?;
        for (clip, rel) in clips {
            let flac = rel.replacen("m4a/", "flac/", 1).replace(".m4a", ".flac");
            let flac_link = if out_dir.join(&flac).exists() {
                format!(" | <a href=\"{}\">FLAC</a>", url_escape(&flac))
            } else {
                String::new()
            };
            writeln!(
                html,
                "<tr><td>{}</td><td><audio controls preload=\"none\" src=\"{}\"></audio></td><td><a href=\"{}\">M4A</a>{}</td></tr>",
                html_escape(&clip),
                url_escape(&rel),
                url_escape(&rel),
                flac_link
            )?;
        }
        writeln!(html, "</tbody></table></details>")?;
    }
    Ok(())
}

pub(super) fn write_manifest_section(
    html: &mut String,
    out_dir: &Path,
) -> Result<(), Box<dyn Error>> {
    let manifests = [
        "descript-scenes.tsv",
        "verified-video-scenes.tsv",
        "character-combinations.tsv",
        "script-speech.tsv",
        "script-executed-dialogue.tsv",
        "script-executed-dialogue-runs.tsv",
        "script-disassembly.tsv",
        "script-dialogue-videos.tsv",
        "script-dialogue-runs.tsv",
        "script-branch-trace.tsv",
        "DESCRIPT.DES",
    ];
    writeln!(html, "<h2>Manifests</h2><ul>")?;
    for rel in manifests {
        if out_dir.join(rel).exists() {
            writeln!(
                html,
                "<li><a href=\"{}\">{}</a></li>",
                url_escape(rel),
                html_escape(rel)
            )?;
        }
    }
    writeln!(html, "</ul>")?;
    Ok(())
}

pub(super) fn write_video(html: &mut String, rel: &str) -> Result<(), Box<dyn Error>> {
    writeln!(
        html,
        "<video controls preload=\"metadata\" src=\"{}\"></video>",
        url_escape(rel)
    )?;
    Ok(())
}

pub(super) fn read_tsv_rows(path: &Path) -> Vec<Vec<String>> {
    fs::read_to_string(path)
        .ok()
        .map(|text| {
            text.lines()
                .skip(1)
                .map(|line| line.split('\t').map(str::to_string).collect())
                .collect()
        })
        .unwrap_or_default()
}

pub(super) fn output_files(out_dir: &Path, subdir: &str, ext: &str) -> Vec<String> {
    let dir = out_dir.join(subdir);
    if !dir.exists() {
        return Vec::new();
    }
    let mut files: Vec<_> = walk_files(&dir)
        .into_iter()
        .filter(|path| {
            path.extension()
                .is_some_and(|actual| actual.to_string_lossy().eq_ignore_ascii_case(ext))
        })
        .filter_map(|path| path.strip_prefix(out_dir).ok().map(path_to_html_rel))
        .collect();
    files.sort();
    files
}

pub(super) fn snd_audio_key(rel: &str) -> Option<(String, String)> {
    let stem = Path::new(rel).file_stem()?.to_string_lossy();
    let rest = stem.strip_prefix("sn - ")?;
    let (bank, clip) = rest.rsplit_once(" - ")?;
    Some((bank.to_string(), clip.to_string()))
}

pub(super) fn path_to_html_rel(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

pub(super) fn html_escape(text: &str) -> String {
    let mut out = String::new();
    for ch in text.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(ch),
        }
    }
    out
}

pub(super) fn url_escape(text: &str) -> String {
    let mut out = String::new();
    for &byte in text.as_bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.' | b'/' | b'~') {
            out.push(byte as char);
        } else {
            write!(out, "%{byte:02X}").ok();
        }
    }
    out
}
