//! Verified lossless WebM derivatives generated by the recovered HNM decoder.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::io::{BufReader, Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{Context, Result, bail};
use commander_blood_formats::archive::BloodResourceName;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::asset_import::{
    checked_relative_path, replace_directory, sha256_hex, temporary_sibling,
};
use crate::native::bloodprg::{
    IndexedGamePalette, LOGICAL_FRAMEBUFFER_HEIGHT, LOGICAL_FRAMEBUFFER_WIDTH,
    PresentationQueueServiceOutcome,
};
use crate::runtime::{
    OriginalGameData, OriginalGameRuntime, RuntimePresentationQueueMetrics,
    RuntimePresentationRequest, RuntimePresentationStream,
};

const VIDEO_DIRECTORY_NAME: &str = "video-v1";
const VIDEO_MANIFEST_FILENAME: &str = "manifest.json";
const VIDEO_SCHEMA_VERSION: u32 = 1;
const VIDEO_METADATA_SCHEMA_VERSION: u32 = 1;
const TEMPORARY_VIDEO_INFIX: &str = "generate";
const HNM_FILENAME_SUFFIX: &[u8] = b".HNM";
const WEBM_EXTENSION: &str = "webm";
const METADATA_EXTENSION: &str = "json";
const MASK_PATH_INFIX: &str = "mask";
const INDEX_PATH_INFIX: &str = "index";
const NOMINAL_FRAME_RATE_NUMERATOR: u32 = 25;
const NOMINAL_FRAME_RATE_DENOMINATOR: u32 = 1;
const FFMPEG_ENVIRONMENT_VARIABLE: &str = "CBLOOD_FFMPEG";
const DEVELOPMENT_FFMPEG_ENVIRONMENT_VARIABLE: &str = "FFMPEG";
const DEFAULT_FFMPEG_EXECUTABLE: &str = "ffmpeg";
const VP9_PROFILE: &str = "1";
const VP9_CPU_USED: &str = "4";
const VP9_ROW_MULTITHREADING: &str = "1";
const VP9_LOSSLESS: &str = "1";
const VP9_PIXEL_FORMAT: &str = "gbrp";
const VP9_COLOR_RANGE: &str = "pc";
const VP9_COLOR_SPACE: &str = "rgb";
const VP9_DEADLINE: &str = "good";
const FRAME_PROGRESS_INTERVAL: usize = 25;
const MAXIMUM_TRACE_SERVICE_CALLS: usize = u16::MAX as usize;
const PRIMARY_FRAMEBUFFER_SEED: u8 = u8::MIN;
const SECONDARY_FRAMEBUFFER_SEED: u8 = u8::MAX;
const VGA_COMPONENT_MAXIMUM: u8 = 63;
const VGA_COMPONENT_SHIFT: u32 = 2;
const VGA_COMPONENT_REPLICATION_SHIFT: u32 = 4;
const OWNED_PIXEL_ALPHA: u8 = u8::MAX;
const CONTEXT_PIXEL_ALPHA: u8 = u8::MIN;
const RGB_COMPONENT_COUNT: usize = 3;
const SHA256_BUFFER_BYTE_COUNT: usize = 64 * 1_024;

const FRAME_PIXEL_COUNT: usize = LOGICAL_FRAMEBUFFER_WIDTH * LOGICAL_FRAMEBUFFER_HEIGHT;
const PLANAR_FRAME_BYTE_COUNT: usize = FRAME_PIXEL_COUNT * RGB_COMPONENT_COUNT;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
struct VideoDerivativeManifest {
    schema_version: u32,
    source_asset_manifest_sha256: String,
    ffmpeg_version: String,
    nominal_frame_rate: [u32; 2],
    timestamps_authoritative: bool,
    videos: Vec<VideoDerivativeEntry>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
struct VideoDerivativeEntry {
    source_resource_name: String,
    source_sha256: String,
    frame_count: usize,
    webm_path: String,
    webm_byte_count: u64,
    webm_sha256: String,
    index_webm_path: String,
    index_webm_byte_count: u64,
    index_webm_sha256: String,
    mask_webm_path: String,
    mask_webm_byte_count: u64,
    mask_webm_sha256: String,
    metadata_path: String,
    metadata_byte_count: u64,
    metadata_sha256: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
struct VideoMetadata {
    schema_version: u32,
    source_resource_name: String,
    source_sha256: String,
    width: usize,
    height: usize,
    frame_count: usize,
    nominal_frame_rate: [u32; 2],
    timestamps_authoritative: bool,
    rgb_pixel_format: String,
    rgb_stream_sha256: String,
    indexed_video_stream_sha256: String,
    mask_stream_sha256: String,
    indexed_pixel_stream_sha256: String,
    ownership_stream_sha256: String,
    context_dependent_palette_indices: Vec<u8>,
    frames: Vec<VideoFrameMetadata>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
struct VideoFrameMetadata {
    frame_index: usize,
    service_call: u16,
    entry_metric: u16,
    read_wrap_index: u16,
    owned_pixel_count: usize,
    palette_updates: Vec<VideoPaletteUpdate>,
    sound_record_hex: Option<String>,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
struct VideoPaletteUpdate {
    palette_index: u8,
    rgb6: [u8; RGB_COMPONENT_COUNT],
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct TraceFrame {
    indices: Box<[u8]>,
    palette: IndexedGamePalette,
    sound_record: Option<Box<[u8]>>,
    service_call: u16,
    queue_metrics: RuntimePresentationQueueMetrics,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct EncodedFile {
    byte_count: u64,
    sha256: String,
}

impl VideoDerivativeManifest {
    fn load(media_root: &Path, source_asset_manifest_sha256: &str) -> Result<Self> {
        let video_root = media_root.join(VIDEO_DIRECTORY_NAME);
        let manifest_path = video_root.join(VIDEO_MANIFEST_FILENAME);
        let encoded = std::fs::read(&manifest_path)
            .with_context(|| format!("reading video manifest {}", manifest_path.display()))?;
        let manifest: Self = serde_json::from_slice(&encoded)
            .with_context(|| format!("decoding video manifest {}", manifest_path.display()))?;
        manifest.validate(&video_root, source_asset_manifest_sha256, false)?;
        Ok(manifest)
    }

    fn validate(
        &self,
        video_root: &Path,
        source_asset_manifest_sha256: &str,
        verify_hashes: bool,
    ) -> Result<()> {
        if self.schema_version != VIDEO_SCHEMA_VERSION {
            bail!(
                "unsupported normalized video schema {}; expected {}",
                self.schema_version,
                VIDEO_SCHEMA_VERSION
            );
        }
        if self.source_asset_manifest_sha256 != source_asset_manifest_sha256 {
            bail!("normalized video was generated from a different asset manifest");
        }
        if self.nominal_frame_rate != [NOMINAL_FRAME_RATE_NUMERATOR, NOMINAL_FRAME_RATE_DENOMINATOR]
            || self.timestamps_authoritative
        {
            bail!("normalized video has unsupported timing metadata");
        }

        let mut resources = BTreeSet::new();
        let mut paths = BTreeSet::new();
        for entry in &self.videos {
            BloodResourceName::new(entry.source_resource_name.as_bytes()).with_context(|| {
                format!(
                    "invalid normalized video source {}",
                    entry.source_resource_name
                )
            })?;
            if !resources.insert(entry.source_resource_name.as_str()) {
                bail!(
                    "duplicate normalized video source {}",
                    entry.source_resource_name
                );
            }
            for (relative, byte_count, sha256) in [
                (
                    entry.webm_path.as_str(),
                    entry.webm_byte_count,
                    entry.webm_sha256.as_str(),
                ),
                (
                    entry.index_webm_path.as_str(),
                    entry.index_webm_byte_count,
                    entry.index_webm_sha256.as_str(),
                ),
                (
                    entry.mask_webm_path.as_str(),
                    entry.mask_webm_byte_count,
                    entry.mask_webm_sha256.as_str(),
                ),
                (
                    entry.metadata_path.as_str(),
                    entry.metadata_byte_count,
                    entry.metadata_sha256.as_str(),
                ),
            ] {
                if !paths.insert(relative) {
                    bail!("duplicate normalized video path {relative}");
                }
                validate_file(video_root, relative, byte_count, sha256, verify_hashes)?;
            }
            let metadata_path = checked_relative_path(video_root, &entry.metadata_path)?;
            let encoded = std::fs::read(&metadata_path)
                .with_context(|| format!("reading video metadata {}", metadata_path.display()))?;
            let metadata: VideoMetadata = serde_json::from_slice(&encoded)
                .with_context(|| format!("decoding video metadata {}", metadata_path.display()))?;
            if metadata.schema_version != VIDEO_METADATA_SCHEMA_VERSION
                || metadata.source_resource_name != entry.source_resource_name
                || metadata.source_sha256 != entry.source_sha256
                || metadata.frame_count != entry.frame_count
                || metadata.frames.len() != entry.frame_count
                || metadata.width != LOGICAL_FRAMEBUFFER_WIDTH
                || metadata.height != LOGICAL_FRAMEBUFFER_HEIGHT
            {
                bail!(
                    "normalized video metadata mismatch: {}",
                    metadata_path.display()
                );
            }
        }
        Ok(())
    }
}

pub(crate) fn prepare_lossless_webm_derivatives(
    data: OriginalGameData,
) -> Result<OriginalGameData> {
    let mut runtime = OriginalGameRuntime::new(data);
    prepare_lossless_webm_derivatives_for_runtime(&mut runtime)?;
    Ok(runtime.into_data())
}

fn prepare_lossless_webm_derivatives_for_runtime(
    runtime: &mut OriginalGameRuntime,
) -> Result<usize> {
    let media_root = runtime.data().normalized_media().root().to_owned();
    let source_asset_manifest_sha256 = runtime
        .data()
        .normalized_media()
        .source_asset_manifest_sha256()
        .to_owned();
    if let Ok(manifest) = VideoDerivativeManifest::load(&media_root, &source_asset_manifest_sha256)
    {
        return Ok(manifest.videos.len());
    }

    let ffmpeg = ffmpeg_executable();
    let ffmpeg_version = ffmpeg_version(&ffmpeg)?;
    let resource_store = runtime.data().resource_store().clone();
    let default_palette = *runtime.data().default_vga_palette();
    let mut resource_names: Vec<_> = resource_store
        .resource_names()
        .into_iter()
        .filter(is_hnm_resource)
        .collect();
    resource_names.sort();
    if resource_names.is_empty() {
        bail!("the imported asset store contains no HNM resources");
    }

    let video_root = media_root.join(VIDEO_DIRECTORY_NAME);
    let temporary_root = temporary_sibling(&video_root, TEMPORARY_VIDEO_INFIX)?;
    if temporary_root.exists() {
        std::fs::remove_dir_all(&temporary_root).with_context(|| {
            format!(
                "removing interrupted video generation {}",
                temporary_root.display()
            )
        })?;
    }
    std::fs::create_dir_all(&temporary_root).with_context(|| {
        format!(
            "creating normalized video directory {}",
            temporary_root.display()
        )
    })?;

    eprintln!(
        "Generating {} verified lossless WebM derivatives in {}. This one-time operation is CPU and disk intensive.",
        resource_names.len(),
        video_root.display()
    );
    let generated = generate_videos(
        runtime,
        &resource_store,
        &resource_names,
        default_palette,
        &temporary_root,
        &ffmpeg,
        ffmpeg_version,
        source_asset_manifest_sha256.clone(),
    );
    let manifest = match generated {
        Ok(manifest) => manifest,
        Err(error) => {
            let _ = std::fs::remove_dir_all(&temporary_root);
            runtime.reset_video_conversion_state(default_palette, PRIMARY_FRAMEBUFFER_SEED);
            return Err(error);
        }
    };
    runtime.reset_video_conversion_state(default_palette, PRIMARY_FRAMEBUFFER_SEED);
    manifest.validate(&temporary_root, &source_asset_manifest_sha256, true)?;
    write_json(
        &temporary_root.join(VIDEO_MANIFEST_FILENAME),
        &manifest,
        "video manifest",
    )?;
    replace_directory(&temporary_root, &video_root)?;
    Ok(manifest.videos.len())
}

#[allow(clippy::too_many_arguments)]
fn generate_videos(
    runtime: &mut OriginalGameRuntime,
    resource_store: &crate::assets::OriginalResourceStore,
    resource_names: &[BloodResourceName],
    default_palette: IndexedGamePalette,
    root: &Path,
    ffmpeg: &Path,
    ffmpeg_version: String,
    source_asset_manifest_sha256: String,
) -> Result<VideoDerivativeManifest> {
    let secondary_palette = alternate_palette(default_palette)?;
    let mut videos = Vec::with_capacity(resource_names.len());
    for (resource_index, resource_name) in resource_names.iter().enumerate() {
        if resource_index == usize::MIN
            || (resource_index + 1).is_multiple_of(FRAME_PROGRESS_INTERVAL)
            || resource_index + 1 == resource_names.len()
        {
            eprintln!(
                "Transcoding HNM {}/{}: {}",
                resource_index + 1,
                resource_names.len(),
                display_resource_name(resource_name)
            );
        }
        let source = resource_store.load(resource_name).with_context(|| {
            format!(
                "loading HNM resource {}",
                display_resource_name(resource_name)
            )
        })?;
        let source_sha256 = sha256_hex(&source);
        let primary = decode_trace(
            runtime,
            resource_name,
            default_palette,
            PRIMARY_FRAMEBUFFER_SEED,
        )?;
        let secondary = decode_trace(
            runtime,
            resource_name,
            secondary_palette,
            SECONDARY_FRAMEBUFFER_SEED,
        )?;
        validate_parallel_traces(resource_name, &primary, &secondary)?;
        videos.push(write_video_derivative(
            root,
            ffmpeg,
            resource_name,
            source_sha256,
            &primary,
            &secondary,
        )?);
    }
    Ok(VideoDerivativeManifest {
        schema_version: VIDEO_SCHEMA_VERSION,
        source_asset_manifest_sha256,
        ffmpeg_version,
        nominal_frame_rate: [NOMINAL_FRAME_RATE_NUMERATOR, NOMINAL_FRAME_RATE_DENOMINATOR],
        timestamps_authoritative: false,
        videos,
    })
}

fn decode_trace(
    runtime: &mut OriginalGameRuntime,
    resource_name: &BloodResourceName,
    palette: IndexedGamePalette,
    framebuffer_seed: u8,
) -> Result<Vec<TraceFrame>> {
    runtime.reset_video_conversion_state(palette, framebuffer_seed);
    let mut request = RuntimePresentationRequest::new(resource_name.clone());
    request.entry_policy.draw_via_back_buffer = true;
    request.present_policy.draw_via_back_buffer = true;
    request.present_policy.unclamped_rows = true;
    let (mut stream, initial) = RuntimePresentationStream::load(runtime, request, u16::MIN)
        .with_context(|| format!("opening HNM trace {}", display_resource_name(resource_name)))?;
    if !initial.initial_entry_accepted || !initial.initial_present.frame_presented {
        bail!(
            "HNM trace did not present its initial frame: {}",
            display_resource_name(resource_name)
        );
    }
    let mut frames = vec![snapshot_trace_frame(
        runtime,
        initial.initial_sound_record,
        u16::MIN,
        stream.queue_metrics()?,
    )];
    for service_call in 1..=MAXIMUM_TRACE_SERVICE_CALLS {
        let clock = service_call as u16;
        let step = stream
            .service_frame(runtime, clock, clock)
            .with_context(|| {
                format!(
                    "decoding HNM {} at service call {service_call}",
                    display_resource_name(resource_name)
                )
            })?;
        if let Some(sound_record) = presented_frame_sound_record(&step.queue) {
            frames.push(snapshot_trace_frame(
                runtime,
                sound_record,
                clock,
                step.queue_metrics,
            ));
        }
        if step.stream_finished {
            if stream.presented_frame_count() != frames.len() as u64 {
                bail!(
                    "HNM trace frame accounting mismatch for {}",
                    display_resource_name(resource_name)
                );
            }
            return Ok(frames);
        }
    }
    bail!(
        "HNM trace exceeded {} service calls: {}",
        MAXIMUM_TRACE_SERVICE_CALLS,
        display_resource_name(resource_name)
    )
}

fn snapshot_trace_frame(
    runtime: &OriginalGameRuntime,
    sound_record: Option<Box<[u8]>>,
    service_call: u16,
    queue_metrics: RuntimePresentationQueueMetrics,
) -> TraceFrame {
    TraceFrame {
        indices: Box::from(runtime.front_buffer().pixels()),
        palette: *runtime.live_palette(),
        sound_record,
        service_call,
        queue_metrics,
    }
}

fn presented_frame_sound_record(
    outcome: &PresentationQueueServiceOutcome,
) -> Option<Option<Box<[u8]>>> {
    match outcome {
        PresentationQueueServiceOutcome::Active {
            present: Some(present),
            sound_record,
            ..
        } if present.frame_presented => Some(sound_record.clone()),
        _ => None,
    }
}

fn validate_parallel_traces(
    resource_name: &BloodResourceName,
    primary: &[TraceFrame],
    secondary: &[TraceFrame],
) -> Result<()> {
    if primary.is_empty() || primary.len() != secondary.len() {
        bail!(
            "dual HNM traces disagree on frame count for {}: {} versus {}",
            display_resource_name(resource_name),
            primary.len(),
            secondary.len()
        );
    }
    for (frame_index, (primary, secondary)) in primary.iter().zip(secondary).enumerate() {
        if primary.indices.len() != FRAME_PIXEL_COUNT
            || secondary.indices.len() != FRAME_PIXEL_COUNT
        {
            bail!(
                "HNM trace frame {frame_index} has invalid dimensions for {}",
                display_resource_name(resource_name)
            );
        }
        if primary.sound_record != secondary.sound_record {
            bail!(
                "dual HNM traces disagree on sound record at frame {frame_index} for {}",
                display_resource_name(resource_name)
            );
        }
        if primary.service_call != secondary.service_call
            || primary.queue_metrics != secondary.queue_metrics
        {
            bail!(
                "dual HNM traces disagree on queue state at frame {frame_index} for {}",
                display_resource_name(resource_name)
            );
        }
    }
    Ok(())
}

fn write_video_derivative(
    root: &Path,
    ffmpeg: &Path,
    resource_name: &BloodResourceName,
    source_sha256: String,
    primary: &[TraceFrame],
    secondary: &[TraceFrame],
) -> Result<VideoDerivativeEntry> {
    let (webm_relative, index_relative, mask_relative, metadata_relative) =
        derivative_paths(resource_name)?;
    let webm_path = checked_relative_path(root, &webm_relative)?;
    let index_path = checked_relative_path(root, &index_relative)?;
    let mask_path = checked_relative_path(root, &mask_relative)?;
    let metadata_path = checked_relative_path(root, &metadata_relative)?;
    for path in [&webm_path, &index_path, &mask_path, &metadata_path] {
        std::fs::create_dir_all(path.parent().context("video derivative has no parent")?)
            .with_context(|| {
                format!("creating video derivative directory for {}", path.display())
            })?;
    }

    let rgb_stream_sha256 =
        encode_lossless_vp9(ffmpeg, &webm_path, primary.len(), |frame_index, output| {
            build_rgb_planar_frame(&primary[frame_index], &secondary[frame_index], output)
        })?;
    let decoded_rgb_sha256 = decode_webm_stream_hash(ffmpeg, &webm_path, primary.len())?;
    if decoded_rgb_sha256 != rgb_stream_sha256 {
        bail!(
            "lossless VP9 RGB verification failed: {}",
            webm_path.display()
        );
    }

    let indexed_video_stream_sha256 =
        encode_lossless_vp9(ffmpeg, &index_path, primary.len(), |frame_index, output| {
            build_indexed_planar_frame(&primary[frame_index], &secondary[frame_index], output)
        })?;
    let decoded_index_sha256 = decode_webm_stream_hash(ffmpeg, &index_path, primary.len())?;
    if decoded_index_sha256 != indexed_video_stream_sha256 {
        bail!(
            "lossless VP9 index verification failed: {}",
            index_path.display()
        );
    }

    let mask_stream_sha256 =
        encode_lossless_vp9(ffmpeg, &mask_path, primary.len(), |frame_index, output| {
            build_mask_planar_frame(&primary[frame_index], &secondary[frame_index], output)
        })?;
    let decoded_mask_sha256 = decode_webm_stream_hash(ffmpeg, &mask_path, primary.len())?;
    if decoded_mask_sha256 != mask_stream_sha256 {
        bail!(
            "lossless VP9 mask verification failed: {}",
            mask_path.display()
        );
    }

    let metadata = build_video_metadata(
        resource_name,
        source_sha256.clone(),
        primary,
        secondary,
        rgb_stream_sha256,
        indexed_video_stream_sha256,
        mask_stream_sha256,
    )?;
    let metadata_encoded = encoded_json(&metadata)?;
    std::fs::write(&metadata_path, &metadata_encoded)
        .with_context(|| format!("writing video metadata {}", metadata_path.display()))?;

    let webm = encoded_file(&webm_path)?;
    let index = encoded_file(&index_path)?;
    let mask = encoded_file(&mask_path)?;
    Ok(VideoDerivativeEntry {
        source_resource_name: display_resource_name(resource_name),
        source_sha256,
        frame_count: primary.len(),
        webm_path: webm_relative,
        webm_byte_count: webm.byte_count,
        webm_sha256: webm.sha256,
        index_webm_path: index_relative,
        index_webm_byte_count: index.byte_count,
        index_webm_sha256: index.sha256,
        mask_webm_path: mask_relative,
        mask_webm_byte_count: mask.byte_count,
        mask_webm_sha256: mask.sha256,
        metadata_path: metadata_relative,
        metadata_byte_count: metadata_encoded.len() as u64,
        metadata_sha256: sha256_hex(&metadata_encoded),
    })
}

fn build_video_metadata(
    resource_name: &BloodResourceName,
    source_sha256: String,
    primary: &[TraceFrame],
    secondary: &[TraceFrame],
    rgb_stream_sha256: String,
    indexed_video_stream_sha256: String,
    mask_stream_sha256: String,
) -> Result<VideoMetadata> {
    let mut indexed_hasher = Sha256::new();
    let mut ownership_hasher = Sha256::new();
    let mut known_palette = [None; 256];
    let mut frames = Vec::with_capacity(primary.len());
    for (frame_index, (primary, secondary)) in primary.iter().zip(secondary).enumerate() {
        indexed_hasher.update(&primary.indices);
        let mut owned_pixel_count = usize::MIN;
        for (primary, secondary) in primary.indices.iter().zip(&secondary.indices) {
            let owned = primary == secondary;
            ownership_hasher.update([u8::from(owned)]);
            owned_pixel_count += usize::from(owned);
        }

        let mut palette_updates = Vec::new();
        for palette_index in u8::MIN..=u8::MAX {
            let index = usize::from(palette_index);
            let primary_color = primary.palette[index];
            if primary_color == secondary.palette[index]
                && known_palette[index] != Some(primary_color)
            {
                validate_rgb6(primary_color)?;
                known_palette[index] = Some(primary_color);
                palette_updates.push(VideoPaletteUpdate {
                    palette_index,
                    rgb6: primary_color,
                });
            }
        }
        frames.push(VideoFrameMetadata {
            frame_index,
            service_call: primary.service_call,
            entry_metric: primary.queue_metrics.entry_metric,
            read_wrap_index: primary.queue_metrics.read_wrap_index,
            owned_pixel_count,
            palette_updates,
            sound_record_hex: primary.sound_record.as_deref().map(hex_bytes),
        });
    }
    let context_dependent_palette_indices = known_palette
        .iter()
        .enumerate()
        .filter_map(|(index, color)| color.is_none().then_some(index as u8))
        .collect();
    Ok(VideoMetadata {
        schema_version: VIDEO_METADATA_SCHEMA_VERSION,
        source_resource_name: display_resource_name(resource_name),
        source_sha256,
        width: LOGICAL_FRAMEBUFFER_WIDTH,
        height: LOGICAL_FRAMEBUFFER_HEIGHT,
        frame_count: primary.len(),
        nominal_frame_rate: [NOMINAL_FRAME_RATE_NUMERATOR, NOMINAL_FRAME_RATE_DENOMINATOR],
        timestamps_authoritative: false,
        rgb_pixel_format: VP9_PIXEL_FORMAT.to_owned(),
        rgb_stream_sha256,
        indexed_video_stream_sha256,
        mask_stream_sha256,
        indexed_pixel_stream_sha256: finish_sha256(indexed_hasher),
        ownership_stream_sha256: finish_sha256(ownership_hasher),
        context_dependent_palette_indices,
        frames,
    })
}

fn build_indexed_planar_frame(
    primary: &TraceFrame,
    secondary: &TraceFrame,
    output: &mut Vec<u8>,
) -> Result<()> {
    output.clear();
    output.reserve(PLANAR_FRAME_BYTE_COUNT);
    for _ in 0..RGB_COMPONENT_COUNT {
        output.extend(primary.indices.iter().zip(&secondary.indices).map(
            |(primary, secondary)| {
                if primary == secondary {
                    *primary
                } else {
                    u8::MIN
                }
            },
        ));
    }
    Ok(())
}

fn build_rgb_planar_frame(
    primary: &TraceFrame,
    secondary: &TraceFrame,
    output: &mut Vec<u8>,
) -> Result<()> {
    output.clear();
    output.resize(PLANAR_FRAME_BYTE_COUNT, u8::MIN);
    let (green, blue_and_red) = output.split_at_mut(FRAME_PIXEL_COUNT);
    let (blue, red) = blue_and_red.split_at_mut(FRAME_PIXEL_COUNT);
    for (position, (primary_index, secondary_index)) in
        primary.indices.iter().zip(&secondary.indices).enumerate()
    {
        if primary_index != secondary_index {
            continue;
        }
        let color = primary.palette[usize::from(*primary_index)];
        validate_rgb6(color)?;
        red[position] = expand_vga_component(color[0]);
        green[position] = expand_vga_component(color[1]);
        blue[position] = expand_vga_component(color[2]);
    }
    Ok(())
}

fn build_mask_planar_frame(
    primary: &TraceFrame,
    secondary: &TraceFrame,
    output: &mut Vec<u8>,
) -> Result<()> {
    output.clear();
    output.reserve(PLANAR_FRAME_BYTE_COUNT);
    for _ in 0..RGB_COMPONENT_COUNT {
        output.extend(primary.indices.iter().zip(&secondary.indices).map(
            |(primary, secondary)| {
                if primary == secondary {
                    OWNED_PIXEL_ALPHA
                } else {
                    CONTEXT_PIXEL_ALPHA
                }
            },
        ));
    }
    Ok(())
}

fn encode_lossless_vp9(
    ffmpeg: &Path,
    destination: &Path,
    frame_count: usize,
    mut frame: impl FnMut(usize, &mut Vec<u8>) -> Result<()>,
) -> Result<String> {
    let dimensions = format!(
        "{}x{}",
        LOGICAL_FRAMEBUFFER_WIDTH, LOGICAL_FRAMEBUFFER_HEIGHT
    );
    let frame_rate = format!("{NOMINAL_FRAME_RATE_NUMERATOR}/{NOMINAL_FRAME_RATE_DENOMINATOR}");
    let mut child = Command::new(ffmpeg)
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-nostdin",
            "-f",
            "rawvideo",
            "-pixel_format",
            VP9_PIXEL_FORMAT,
            "-video_size",
            &dimensions,
            "-framerate",
            &frame_rate,
            "-i",
            "pipe:0",
            "-an",
            "-c:v",
            "libvpx-vp9",
            "-profile:v",
            VP9_PROFILE,
            "-lossless",
            VP9_LOSSLESS,
            "-pix_fmt",
            VP9_PIXEL_FORMAT,
            "-color_range",
            VP9_COLOR_RANGE,
            "-colorspace",
            VP9_COLOR_SPACE,
            "-deadline",
            VP9_DEADLINE,
            "-cpu-used",
            VP9_CPU_USED,
            "-row-mt",
            VP9_ROW_MULTITHREADING,
            "-f",
            "webm",
            "-y",
        ])
        .arg(destination)
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::inherit())
        .spawn()
        .with_context(|| format!("starting FFmpeg encoder {}", ffmpeg.display()))?;
    let mut stdin = child.stdin.take().context("FFmpeg encoder has no stdin")?;
    let mut encoded_frame = Vec::with_capacity(PLANAR_FRAME_BYTE_COUNT);
    let mut hasher = Sha256::new();
    for frame_index in 0..frame_count {
        frame(frame_index, &mut encoded_frame)?;
        if encoded_frame.len() != PLANAR_FRAME_BYTE_COUNT {
            bail!(
                "normalized raw frame has {} bytes; expected {}",
                encoded_frame.len(),
                PLANAR_FRAME_BYTE_COUNT
            );
        }
        hasher.update(&encoded_frame);
        stdin
            .write_all(&encoded_frame)
            .with_context(|| format!("streaming raw frame {frame_index} to FFmpeg"))?;
    }
    drop(stdin);
    let status = child.wait().context("waiting for FFmpeg encoder")?;
    if !status.success() {
        bail!("FFmpeg lossless VP9 encoder exited with {status}");
    }
    Ok(finish_sha256(hasher))
}

fn decode_webm_stream_hash(ffmpeg: &Path, source: &Path, frame_count: usize) -> Result<String> {
    let mut child = Command::new(ffmpeg)
        .args(["-hide_banner", "-loglevel", "error", "-nostdin", "-i"])
        .arg(source)
        .args([
            "-map",
            "0:v:0",
            "-fps_mode",
            "passthrough",
            "-f",
            "rawvideo",
            "-pix_fmt",
            VP9_PIXEL_FORMAT,
            "pipe:1",
        ])
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .with_context(|| format!("starting FFmpeg verifier {}", ffmpeg.display()))?;
    let stdout = child
        .stdout
        .take()
        .context("FFmpeg verifier has no stdout")?;
    let mut stdout = BufReader::new(stdout);
    let mut decoded_frame = vec![u8::MIN; PLANAR_FRAME_BYTE_COUNT];
    let mut hasher = Sha256::new();
    for frame_index in 0..frame_count {
        stdout.read_exact(&mut decoded_frame).with_context(|| {
            format!(
                "reading verified frame {frame_index} from {}",
                source.display()
            )
        })?;
        hasher.update(&decoded_frame);
    }
    let mut extra = [u8::MIN; 1];
    if stdout
        .read(&mut extra)
        .context("checking for extra decoded frames")?
        != usize::MIN
    {
        bail!("FFmpeg decoded extra frames from {}", source.display());
    }
    drop(stdout);
    let status = child.wait().context("waiting for FFmpeg verifier")?;
    if !status.success() {
        bail!("FFmpeg VP9 verifier exited with {status}");
    }
    Ok(finish_sha256(hasher))
}

fn derivative_paths(resource_name: &BloodResourceName) -> Result<(String, String, String, String)> {
    let key = display_resource_name(resource_name).replace('\\', "/");
    let mut base = PathBuf::from(key);
    base.set_extension("");
    let webm = base.with_extension(WEBM_EXTENSION);
    let index = base.with_extension(format!("{INDEX_PATH_INFIX}.{WEBM_EXTENSION}"));
    let mask = base.with_extension(format!("{MASK_PATH_INFIX}.{WEBM_EXTENSION}"));
    let metadata = base.with_extension(METADATA_EXTENSION);
    Ok((
        utf8_relative_path(&webm)?,
        utf8_relative_path(&index)?,
        utf8_relative_path(&mask)?,
        utf8_relative_path(&metadata)?,
    ))
}

fn utf8_relative_path(path: &Path) -> Result<String> {
    path.to_str()
        .context("normalized video path is not UTF-8")
        .map(str::to_owned)
}

fn validate_file(
    root: &Path,
    relative: &str,
    expected_byte_count: u64,
    expected_sha256: &str,
    verify_hash: bool,
) -> Result<()> {
    let path = checked_relative_path(root, relative)?;
    let metadata = std::fs::metadata(&path)
        .with_context(|| format!("reading normalized video metadata {}", path.display()))?;
    if metadata.len() != expected_byte_count {
        bail!("normalized video size mismatch: {}", path.display());
    }
    if verify_hash && encoded_file(&path)?.sha256 != expected_sha256 {
        bail!("normalized video hash mismatch: {}", path.display());
    }
    Ok(())
}

fn encoded_file(path: &Path) -> Result<EncodedFile> {
    let file = std::fs::File::open(path)
        .with_context(|| format!("opening generated video {}", path.display()))?;
    let byte_count = file
        .metadata()
        .with_context(|| format!("reading generated video metadata {}", path.display()))?
        .len();
    let mut reader = BufReader::new(file);
    let mut buffer = vec![u8::MIN; SHA256_BUFFER_BYTE_COUNT];
    let mut hasher = Sha256::new();
    loop {
        let read = reader
            .read(&mut buffer)
            .with_context(|| format!("hashing generated video {}", path.display()))?;
        if read == usize::MIN {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(EncodedFile {
        byte_count,
        sha256: finish_sha256(hasher),
    })
}

fn write_json(path: &Path, value: &impl Serialize, description: &str) -> Result<()> {
    let encoded = encoded_json(value)?;
    std::fs::write(path, encoded)
        .with_context(|| format!("writing {description} {}", path.display()))
}

fn encoded_json(value: &impl Serialize) -> Result<Vec<u8>> {
    let mut encoded = serde_json::to_vec_pretty(value).context("encoding normalized video JSON")?;
    encoded.push(b'\n');
    Ok(encoded)
}

fn alternate_palette(palette: IndexedGamePalette) -> Result<IndexedGamePalette> {
    for color in palette {
        validate_rgb6(color)?;
    }
    Ok(palette.map(|color| color.map(|component| VGA_COMPONENT_MAXIMUM - component)))
}

fn validate_rgb6(color: [u8; RGB_COMPONENT_COUNT]) -> Result<()> {
    if color
        .iter()
        .any(|component| *component > VGA_COMPONENT_MAXIMUM)
    {
        bail!("HNM palette component exceeds the six-bit VGA range");
    }
    Ok(())
}

const fn expand_vga_component(component: u8) -> u8 {
    (component << VGA_COMPONENT_SHIFT) | (component >> VGA_COMPONENT_REPLICATION_SHIFT)
}

fn is_hnm_resource(name: &BloodResourceName) -> bool {
    name.as_bytes()
        .get(
            name.as_bytes()
                .len()
                .saturating_sub(HNM_FILENAME_SUFFIX.len())..,
        )
        .is_some_and(|suffix| suffix.eq_ignore_ascii_case(HNM_FILENAME_SUFFIX))
}

fn display_resource_name(name: &BloodResourceName) -> String {
    String::from_utf8(name.archive_lookup_key().into_vec())
        .expect("validated resource names are ASCII")
}

fn ffmpeg_executable() -> PathBuf {
    std::env::var_os(FFMPEG_ENVIRONMENT_VARIABLE)
        .or_else(|| std::env::var_os(DEVELOPMENT_FFMPEG_ENVIRONMENT_VARIABLE))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(DEFAULT_FFMPEG_EXECUTABLE))
}

fn ffmpeg_version(ffmpeg: &Path) -> Result<String> {
    let output = Command::new(ffmpeg)
        .arg("-version")
        .output()
        .with_context(|| format!("running FFmpeg {}", ffmpeg.display()))?;
    if !output.status.success() {
        bail!("FFmpeg version probe exited with {}", output.status);
    }
    String::from_utf8(output.stdout)
        .context("FFmpeg version output is not UTF-8")?
        .lines()
        .next()
        .context("FFmpeg version output is empty")
        .map(str::to_owned)
}

fn hex_bytes(bytes: &[u8]) -> String {
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(&mut encoded, "{byte:02x}").expect("writing to a String cannot fail");
    }
    encoded
}

fn finish_sha256(hasher: Sha256) -> String {
    hex_bytes(&hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::{OriginalGameData, OriginalGameDataPaths};

    const TEST_VIDEO_RESOURCE: &[u8] = br"SQ\LOGO01.HNM";

    #[test]
    fn derivative_paths_preserve_dos_resource_identity() {
        let name = BloodResourceName::new(br"PE\AAGAR.HNM").unwrap();
        assert_eq!(
            derivative_paths(&name).unwrap(),
            (
                "PE/AAGAR.webm".to_owned(),
                "PE/AAGAR.index.webm".to_owned(),
                "PE/AAGAR.mask.webm".to_owned(),
                "PE/AAGAR.json".to_owned(),
            )
        );
    }

    #[test]
    fn dual_seed_frames_produce_exact_rgb_and_ownership_planes() {
        let mut palette = [[u8::MIN; RGB_COMPONENT_COUNT]; 256];
        palette[1] = [63, 32, 1];
        let primary = TraceFrame {
            indices: vec![1, 0].into_boxed_slice(),
            palette,
            sound_record: None,
            service_call: u16::MIN,
            queue_metrics: RuntimePresentationQueueMetrics::default(),
        };
        let secondary = TraceFrame {
            indices: vec![1, 255].into_boxed_slice(),
            palette,
            sound_record: None,
            service_call: u16::MIN,
            queue_metrics: RuntimePresentationQueueMetrics::default(),
        };
        let mut rgb = Vec::new();
        build_rgb_planar_frame_for_dimensions(&primary, &secondary, 2, &mut rgb).unwrap();
        assert_eq!(rgb, [130, 0, 4, 0, 255, 0]);
        let mut mask = Vec::new();
        build_mask_planar_frame_for_dimensions(&primary, &secondary, 2, &mut mask);
        assert_eq!(mask, [255, 0, 255, 0, 255, 0]);
        let mut indices = Vec::new();
        build_indexed_planar_frame(&primary, &secondary, &mut indices).unwrap();
        assert_eq!(&indices[..6], &[1, 0, 1, 0, 1, 0],);
    }

    #[test]
    #[ignore = "requires original Commander Blood data and FFmpeg"]
    fn real_hnm_round_trips_exactly_through_lossless_webm() {
        let paths = OriginalGameDataPaths::discover(None).unwrap();
        let scratch = std::env::temp_dir().join(format!(
            "commander-blood-video-roundtrip-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&scratch);
        std::fs::create_dir_all(&scratch).unwrap();

        let data = OriginalGameData::load_with_writable_root(paths, &scratch).unwrap();
        let resource_name = BloodResourceName::new(TEST_VIDEO_RESOURCE).unwrap();
        let source_sha256 = sha256_hex(&data.resource_store().load(&resource_name).unwrap());
        let default_palette = *data.default_vga_palette();
        let secondary_palette = alternate_palette(default_palette).unwrap();
        let mut runtime = OriginalGameRuntime::new(data);
        let primary = decode_trace(
            &mut runtime,
            &resource_name,
            default_palette,
            PRIMARY_FRAMEBUFFER_SEED,
        )
        .unwrap();
        let secondary = decode_trace(
            &mut runtime,
            &resource_name,
            secondary_palette,
            SECONDARY_FRAMEBUFFER_SEED,
        )
        .unwrap();
        validate_parallel_traces(&resource_name, &primary, &secondary).unwrap();

        let ffmpeg = ffmpeg_executable();
        let entry = write_video_derivative(
            &scratch,
            &ffmpeg,
            &resource_name,
            source_sha256,
            &primary,
            &secondary,
        )
        .unwrap();
        assert_eq!(entry.frame_count, primary.len());
        assert!(entry.webm_byte_count > 0);
        assert!(entry.index_webm_byte_count > 0);
        assert!(entry.mask_webm_byte_count > 0);
        assert!(entry.metadata_byte_count > 0);

        std::fs::remove_dir_all(&scratch).unwrap();
    }

    fn build_rgb_planar_frame_for_dimensions(
        primary: &TraceFrame,
        secondary: &TraceFrame,
        pixel_count: usize,
        output: &mut Vec<u8>,
    ) -> Result<()> {
        output.clear();
        output.resize(pixel_count * RGB_COMPONENT_COUNT, u8::MIN);
        let (green, blue_and_red) = output.split_at_mut(pixel_count);
        let (blue, red) = blue_and_red.split_at_mut(pixel_count);
        for (position, (primary_index, secondary_index)) in
            primary.indices.iter().zip(&secondary.indices).enumerate()
        {
            if primary_index == secondary_index {
                let color = primary.palette[usize::from(*primary_index)];
                red[position] = expand_vga_component(color[0]);
                green[position] = expand_vga_component(color[1]);
                blue[position] = expand_vga_component(color[2]);
            }
        }
        Ok(())
    }

    fn build_mask_planar_frame_for_dimensions(
        primary: &TraceFrame,
        secondary: &TraceFrame,
        pixel_count: usize,
        output: &mut Vec<u8>,
    ) {
        output.clear();
        for _ in 0..RGB_COMPONENT_COUNT {
            output.extend(
                primary
                    .indices
                    .iter()
                    .zip(&secondary.indices)
                    .take(pixel_count)
                    .map(|(primary, secondary)| u8::from(primary == secondary) * u8::MAX),
            );
        }
    }
}
