#!/usr/bin/env python3
"""Emit lift.py's CFG lift(s) for specific functions into an auto-generated Rust module, so they
can be checked against the INTERPRETER oracle (with realistic seeded data) in ptr_leaves.rs —
these are pointer-chasing / data-reading leaves the Unicorn fuzz + det oracles can't feed.

    PYTHONSAFEPATH=1 python3 re/tools/emit_one.py src/recomp/ptr_leaves_gen.rs 0x22e0 ...
The first arg is the output path; the rest are function offsets (hex).
"""
import sys, dis  # noqa: F401  (import stdlib dis before lift shadows it)
sys.path.insert(0, "re/tools")
import lift

outpath = sys.argv[1]
offs = [int(a, 16) for a in sys.argv[2:]]
bodies = []
for off in offs:
    name = f"func_{off:x}"
    src = lift.lift_cfg(off, name)
    todo = [l for l in src.splitlines() if "TODO(lifter)" in l]
    if todo:
        sys.stderr.write(f"# SKIP {name}: {len(todo)} TODO(s)\n")
        continue
    sys.stderr.write(f"# {name}: CLEAN; {'retf' if ': retf' in src else 'ret'}\n")
    bodies.append(src)

header = (
    "//! AUTO-GENERATED by re/tools/emit_one.py — do NOT edit.\n"
    "//! Pointer-chasing / data-reading pure-CPU leaves the Unicorn fuzz + deterministic oracles\n"
    "//! can't feed (their reads depend on realistic data structures). Each is lift.py's verified\n"
    "//! CFG lift; correctness is checked bit-exact against the ORIGINAL bytes run through the\n"
    "//! interpreter, with realistic seeded data, in `super::ptr_leaves`'s tests.\n"
    "use super::machine::Machine;\n"
)
open(outpath, "w").write(header + "\n" + "\n\n".join(bodies) + "\n")
sys.stderr.write(f"wrote {outpath}: {len(bodies)} fn(s)\n")
