"""Path-B batch generator. For every CLEAN-liftable leaf (re/tools/cfg_clean.json):
  1. lift it (lift_cfg) and detect ret vs retf,
  2. generate generic oracle vectors by running the REAL bytes in Unicorn (auto_oracle.gen),
     keeping only functions that yield >= MIN_VECS clean vectors (no code-region access),
  3. write src/recomp/auto.rs (all kept lifts) and the vectors,
  4. print the Rust batch array (name, fn) to paste into mod.rs's auto_lifted_batch test.
Run: PYTHONSAFEPATH=1 python3 re/tools/gen_batch.py"""
import json, os, sys, dis as _stdlib_dis
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lift, auto_oracle

MIN_VECS = 120
N = 200
CODEGEN_ONLY = "--codegen-only" in sys.argv  # re-emit auto.rs from existing vectors, skip oracle
# Functions the generic oracle cannot fairly verify (documented, not silent):
EXCLUDE = {
    0xccb: "CPU-type detection: reads FLAGS bits 12-15 (IOPL/NT) via pushf/popf; result is "
           "CPU-model-specific and depends on flag bits the 7-flag Machine model omits. "
           "Returns 1 (386) on the target; composition can treat it as constant.",
}
clean = [int(x, 16) for x in json.load(open("re/tools/cfg_clean.json")) if int(x, 16) not in EXCLUDE]

def ret_kind(off):
    """retf if the function's terminator(s) are far returns, else ret."""
    src = lift.lift_cfg(off, "probe")
    has_retf = any(": retf" in l for l in src.splitlines())
    return "retf" if has_retf else "ret"

kept = []      # (off, name, retf)
lifts = []     # rust source
for off in clean:
    name = f"func_{off:x}"
    rk = ret_kind(off)
    retf = rk == "retf"
    vpath = f"re/tools/oracle_vectors/{name}_generic.json"
    if CODEGEN_ONLY:
        if not os.path.exists(vpath):
            continue  # wasn't kept in the last oracle run
        nv = len(json.load(open(vpath)))
    else:
        vecs = auto_oracle.gen(off, retf, n=N)
        if len(vecs) < MIN_VECS:
            print(f"  skip {name}: only {len(vecs)} vectors (code-region access or traps)")
            continue
        json.dump(vecs, open(vpath, "w"))
        nv = len(vecs)
    lifts.append(lift.lift_cfg(off, name))
    kept.append((off, name, retf))
    print(f"  ok   {name}: {nv} vectors ({rk})")

# --- Composition tier: lift NON-leaf functions whose direct callees are all already verified,
# reachable via a near CALL to a near-ret callee (a retf callee would trip the oracle read-hook
# bug mid-run; those await the oracle redesign). We iterate to a fixpoint so deeper tiers compose.
_cg = json.load(open("re/func_graph.json"))["callgraph"]
kept_offs = {off for off, _, _ in kept}
progress = True
while progress:
    progress = False
    lift.AVAILABLE = {f for f in kept_offs if ret_kind(f) == "ret"}  # only near-ret callees are safe
    for f_s, callees in _cg.items():
        f = int(f_s)
        if f in kept_offs or f in EXCLUDE or not callees:
            continue
        if not all(c in kept_offs for c in callees):
            continue
        name = f"func_{f:x}"
        src = lift.lift_cfg(f, name)
        if any("TODO(lifter)" in l for l in src.splitlines()):
            continue  # an unresolved (indirect / retf) call or opcode remains
        retf = ": retf" in src
        vpath = f"re/tools/oracle_vectors/{name}_generic.json"
        if CODEGEN_ONLY:
            if not os.path.exists(vpath):
                continue
            nv = len(json.load(open(vpath)))
        else:
            vecs = auto_oracle.gen(f, retf, n=N)
            if len(vecs) < MIN_VECS:
                print(f"  skip {name}: only {len(vecs)} vectors (composed non-leaf)")
                continue
            json.dump(vecs, open(vpath, "w"))
            nv = len(vecs)
        lifts.append(src)
        kept.append((f, name, retf))
        kept_offs.add(f)
        progress = True
        print(f"  ok   {name}: {nv} vectors (composed non-leaf)")

header = ("//! AUTO-GENERATED by re/tools/gen_batch.py (path B). Do not edit; regenerate +\n"
          "//! oracle-verify with: PYTHONSAFEPATH=1 python3 re/tools/gen_batch.py\n"
          "//! Each fn is bit-exact vs the real BLOODPRG bytes over generic oracle vectors\n"
          "//! (registers + every memory write). Blockers left: I/O (int/out/in), call/lcall.\n"
          "use super::machine::Machine;\n")
open("src/recomp/auto.rs", "w").write(header + "\n" + "\n\n".join(lifts) + "\n")

print(f"\nKEPT {len(kept)} functions -> src/recomp/auto.rs")
print("\n--- paste into mod.rs auto_lifted_batch_matches_oracle ---")
for off, name, retf in kept:
    print(f'            ("{name}", super::auto::{name}),')
