//! AUTO-GENERATED by re/tools/lift.py (path B). Do not edit; regenerate + oracle-verify.
//! func_92a3 (0x92A3) deferred: a longer branch to 0x9339 exposes a lifter gap (WIP).
use super::machine::Machine;

pub fn func_1fbc(m: &mut Machine) {
    let mut __blk: u32 = 0x1fbc;
    loop {
        match __blk {
            0x1fbc => {
                // 0x01fbc: mov ax, word ptr [0xa2e]
                m.regs.set_ax((m.read16(m.regs.ds, 0xa2e)) as u16);
                // 0x01fbf: test al, 1
                m.regs.test8((m.regs.al()) as u8, (0x1) as u8);
                // 0x01fc1: je 0x1fd3
                if m.regs.zf { __blk = 0x1fd3; } else { __blk = 0x1fc3; }
            }
            0x1fc3 => {
                // 0x01fc3: and al, byte ptr [0xa30]
                let __r = m.regs.and8((m.regs.al()) as u8, (m.read8(m.regs.ds, 0xa30)) as u8);
                m.regs.set_al(__r);
                // 0x01fc7: jne 0x1fd3
                if !m.regs.zf { __blk = 0x1fd3; } else { __blk = 0x1fc9; }
            }
            0x1fc9 => {
                // 0x01fc9: mov byte ptr [0xa3e], 1
                m.write8(m.regs.ds, 0xa3e, (0x1) as u8);
                // 0x01fce: mov byte ptr [0xa40], 1
                m.write8(m.regs.ds, 0xa40, (0x1) as u8);
                __blk = 0x1fd3;
            }
            0x1fd3 => {
                // 0x01fd3: test al, 2
                m.regs.test8((m.regs.al()) as u8, (0x2) as u8);
                // 0x01fd5: je 0x1fe7
                if m.regs.zf { __blk = 0x1fe7; } else { __blk = 0x1fd7; }
            }
            0x1fd7 => {
                // 0x01fd7: and al, byte ptr [0xa30]
                let __r = m.regs.and8((m.regs.al()) as u8, (m.read8(m.regs.ds, 0xa30)) as u8);
                m.regs.set_al(__r);
                // 0x01fdb: jne 0x1fe7
                if !m.regs.zf { __blk = 0x1fe7; } else { __blk = 0x1fdd; }
            }
            0x1fdd => {
                // 0x01fdd: mov byte ptr [0xa3f], 1
                m.write8(m.regs.ds, 0xa3f, (0x1) as u8);
                // 0x01fe2: mov byte ptr [0xa40], 1
                m.write8(m.regs.ds, 0xa40, (0x1) as u8);
                __blk = 0x1fe7;
            }
            0x1fe7 => {
                // 0x01fe7: mov ax, word ptr [0xa2e]
                m.regs.set_ax((m.read16(m.regs.ds, 0xa2e)) as u16);
                // 0x01fea: mov word ptr [0xa30], ax
                m.write16(m.regs.ds, 0xa30, (m.regs.ax()) as u16);
                // 0x01fed: ret 
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn func_5fd8(m: &mut Machine) {
    let mut __blk: u32 = 0x5fd8;
    loop {
        match __blk {
            0x5fd8 => {
                // 0x05fd8: push cx
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp(), (m.regs.cx()) as u16);
                // 0x05fd9: push bp
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp(), (m.regs.bp()) as u16);
                // 0x05fda: mov bp, 0x6d3e
                m.regs.set_bp((0x6d3e) as u16);
                // 0x05fdd: mov cx, 0x10
                m.regs.set_cx((0x10) as u16);
                __blk = 0x5fe0;
            }
            0x5fe0 => {
                // 0x05fe0: cmp ax, word ptr [bp]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ss, m.regs.bp())) as u16);
                // 0x05fe3: je 0x5fed
                if m.regs.zf { __blk = 0x5fed; } else { __blk = 0x5fe5; }
            }
            0x5fe5 => {
                // 0x05fe5: add bp, 2
                let __r = m.regs.add16((m.regs.bp()) as u16, (0x2) as u16);
                m.regs.set_bp(__r);
                // 0x05fe8: loop 0x5fe0
                let __c = m.regs.cx().wrapping_sub(1); m.regs.set_cx(__c);
                if __c != 0 { __blk = 0x5fe0; } else { __blk = 0x5fea; }
            }
            0x5fea => {
                // 0x05fea: clc 
                m.regs.cf = false;
                // 0x05feb: jmp 0x5ff3
                __blk = 0x5ff3;
            }
            0x5fed => {
                // 0x05fed: mov word ptr [bp], 0
                m.write16(m.regs.ss, m.regs.bp(), (0x0) as u16);
                // 0x05ff2: stc 
                m.regs.cf = true;
                __blk = 0x5ff3;
            }
            0x5ff3 => {
                // 0x05ff3: pop bp
                let __v = m.read16(m.regs.ss, m.regs.sp());
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_bp((__v) as u16);
                // 0x05ff4: pop cx
                let __v = m.read16(m.regs.ss, m.regs.sp());
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_cx((__v) as u16);
                // 0x05ff5: ret 
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn func_5ff6(m: &mut Machine) {
    let mut __blk: u32 = 0x5ff6;
    loop {
        match __blk {
            0x5ff6 => {
                // 0x05ff6: push cx
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp(), (m.regs.cx()) as u16);
                // 0x05ff7: push bp
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp(), (m.regs.bp()) as u16);
                // 0x05ff8: mov bp, 0x6d3e
                m.regs.set_bp((0x6d3e) as u16);
                // 0x05ffb: mov cx, 0x10
                m.regs.set_cx((0x10) as u16);
                __blk = 0x5ffe;
            }
            0x5ffe => {
                // 0x05ffe: cmp ax, word ptr [bp]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ss, m.regs.bp())) as u16);
                // 0x06001: je 0x601f
                if m.regs.zf { __blk = 0x601f; } else { __blk = 0x6003; }
            }
            0x6003 => {
                // 0x06003: add bp, 2
                let __r = m.regs.add16((m.regs.bp()) as u16, (0x2) as u16);
                m.regs.set_bp(__r);
                // 0x06006: loop 0x5ffe
                let __c = m.regs.cx().wrapping_sub(1); m.regs.set_cx(__c);
                if __c != 0 { __blk = 0x5ffe; } else { __blk = 0x6008; }
            }
            0x6008 => {
                // 0x06008: mov bp, 0x6d3e
                m.regs.set_bp((0x6d3e) as u16);
                // 0x0600b: mov cx, 0x10
                m.regs.set_cx((0x10) as u16);
                __blk = 0x600e;
            }
            0x600e => {
                // 0x0600e: cmp word ptr [bp], 0
                m.regs.cmp16((m.read16(m.regs.ss, m.regs.bp())) as u16, (0x0) as u16);
                // 0x06012: je 0x601c
                if m.regs.zf { __blk = 0x601c; } else { __blk = 0x6014; }
            }
            0x6014 => {
                // 0x06014: add bp, 2
                let __r = m.regs.add16((m.regs.bp()) as u16, (0x2) as u16);
                m.regs.set_bp(__r);
                // 0x06017: loop 0x600e
                let __c = m.regs.cx().wrapping_sub(1); m.regs.set_cx(__c);
                if __c != 0 { __blk = 0x600e; } else { __blk = 0x6019; }
            }
            0x6019 => {
                // 0x06019: clc 
                m.regs.cf = false;
                // 0x0601a: jmp 0x6020
                __blk = 0x6020;
            }
            0x601c => {
                // 0x0601c: mov word ptr [bp], ax
                m.write16(m.regs.ss, m.regs.bp(), (m.regs.ax()) as u16);
                __blk = 0x601f;
            }
            0x601f => {
                // 0x0601f: stc 
                m.regs.cf = true;
                __blk = 0x6020;
            }
            0x6020 => {
                // 0x06020: pop bp
                let __v = m.read16(m.regs.ss, m.regs.sp());
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_bp((__v) as u16);
                // 0x06021: pop cx
                let __v = m.read16(m.regs.ss, m.regs.sp());
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_cx((__v) as u16);
                // 0x06022: ret 
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn func_78d0(m: &mut Machine) {
    let mut __blk: u32 = 0x78d0;
    loop {
        match __blk {
            0x78d0 => {
                // 0x078d0: push bp
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp(), (m.regs.bp()) as u16);
                // 0x078d1: mov bp, 0x2a27
                m.regs.set_bp((0x2a27) as u16);
                // 0x078d4: test byte ptr [0x2793], 0x50
                m.regs.test8((m.read8(m.regs.ds, 0x2793)) as u8, (0x50) as u8);
                // 0x078d9: je 0x792b
                if m.regs.zf { __blk = 0x792b; } else { __blk = 0x78db; }
            }
            0x78db => {
                // 0x078db: test byte ptr [0x2793], 0x40
                m.regs.test8((m.read8(m.regs.ds, 0x2793)) as u8, (0x40) as u8);
                // 0x078e0: je 0x78e5
                if m.regs.zf { __blk = 0x78e5; } else { __blk = 0x78e2; }
            }
            0x78e2 => {
                // 0x078e2: add bp, 0x30
                let __r = m.regs.add16((m.regs.bp()) as u16, (0x30) as u16);
                m.regs.set_bp(__r);
                __blk = 0x78e5;
            }
            0x78e5 => {
                // 0x078e5: mov ax, word ptr [0xa2a]
                m.regs.set_ax((m.read16(m.regs.ds, 0xa2a)) as u16);
                // 0x078e8: cmp ax, word ptr [bp]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ss, m.regs.bp())) as u16);
                // 0x078eb: jl 0x7919
                if (m.regs.sf != m.regs.of) { __blk = 0x7919; } else { __blk = 0x78ed; }
            }
            0x78ed => {
                // 0x078ed: sub ax, word ptr [bp + 4]
                let __r = m.regs.sub16((m.regs.ax()) as u16, (m.read16(m.regs.ss, m.regs.bp().wrapping_add(0x4))) as u16);
                m.regs.set_ax(__r);
                // 0x078f0: cmp ax, word ptr [bp]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ss, m.regs.bp())) as u16);
                // 0x078f3: jg 0x7919
                if (!m.regs.zf && (m.regs.sf == m.regs.of)) { __blk = 0x7919; } else { __blk = 0x78f5; }
            }
            0x78f5 => {
                // 0x078f5: mov ax, word ptr [0xa2c]
                m.regs.set_ax((m.read16(m.regs.ds, 0xa2c)) as u16);
                // 0x078f8: cmp ax, word ptr [bp + 2]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ss, m.regs.bp().wrapping_add(0x2))) as u16);
                // 0x078fb: jl 0x7919
                if (m.regs.sf != m.regs.of) { __blk = 0x7919; } else { __blk = 0x78fd; }
            }
            0x78fd => {
                // 0x078fd: sub ax, word ptr [bp + 6]
                let __r = m.regs.sub16((m.regs.ax()) as u16, (m.read16(m.regs.ss, m.regs.bp().wrapping_add(0x6))) as u16);
                m.regs.set_ax(__r);
                // 0x07900: cmp ax, word ptr [bp + 2]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ss, m.regs.bp().wrapping_add(0x2))) as u16);
                // 0x07903: jg 0x7919
                if (!m.regs.zf && (m.regs.sf == m.regs.of)) { __blk = 0x7919; } else { __blk = 0x7905; }
            }
            0x7905 => {
                // 0x07905: test byte ptr [0x27ea], 1
                m.regs.test8((m.read8(m.regs.ds, 0x27ea)) as u8, (0x1) as u8);
                // 0x0790a: jne 0x792b
                if !m.regs.zf { __blk = 0x792b; } else { __blk = 0x790c; }
            }
            0x790c => {
                // 0x0790c: mov byte ptr [0x27ea], 1
                m.write8(m.regs.ds, 0x27ea, (0x1) as u8);
                // 0x07911: mov word ptr [0xa32], 9
                m.write16(m.regs.ds, 0xa32, (0x9) as u16);
                // 0x07917: jmp 0x792b
                __blk = 0x792b;
            }
            0x7919 => {
                // 0x07919: test byte ptr [0x27ea], 1
                m.regs.test8((m.read8(m.regs.ds, 0x27ea)) as u8, (0x1) as u8);
                // 0x0791e: je 0x792b
                if m.regs.zf { __blk = 0x792b; } else { __blk = 0x7920; }
            }
            0x7920 => {
                // 0x07920: mov byte ptr [0x27ea], 0
                m.write8(m.regs.ds, 0x27ea, (0x0) as u8);
                // 0x07925: mov ax, word ptr [0xa36]
                m.regs.set_ax((m.read16(m.regs.ds, 0xa36)) as u16);
                // 0x07928: mov word ptr [0xa32], ax
                m.write16(m.regs.ds, 0xa32, (m.regs.ax()) as u16);
                __blk = 0x792b;
            }
            0x792b => {
                // 0x0792b: pop bp
                let __v = m.read16(m.regs.ss, m.regs.sp());
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_bp((__v) as u16);
                // 0x0792c: ret 
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn func_8269(m: &mut Machine) {
    let mut __blk: u32 = 0x8269;
    loop {
        match __blk {
            0x8269 => {
                // 0x08269: push ax
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp(), (m.regs.ax()) as u16);
                // 0x0826a: test byte ptr [0xa3e], 1
                m.regs.test8((m.read8(m.regs.ds, 0xa3e)) as u8, (0x1) as u8);
                // 0x0826f: je 0x8293
                if m.regs.zf { __blk = 0x8293; } else { __blk = 0x8271; }
            }
            0x8271 => {
                // 0x08271: mov ax, word ptr [0xa2a]
                m.regs.set_ax((m.read16(m.regs.ds, 0xa2a)) as u16);
                // 0x08274: cmp ax, word ptr [si]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ds, m.regs.si())) as u16);
                // 0x08276: jl 0x8293
                if (m.regs.sf != m.regs.of) { __blk = 0x8293; } else { __blk = 0x8278; }
            }
            0x8278 => {
                // 0x08278: sub ax, word ptr [si + 4]
                let __r = m.regs.sub16((m.regs.ax()) as u16, (m.read16(m.regs.ds, m.regs.si().wrapping_add(0x4))) as u16);
                m.regs.set_ax(__r);
                // 0x0827b: cmp ax, word ptr [si]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ds, m.regs.si())) as u16);
                // 0x0827d: jg 0x8293
                if (!m.regs.zf && (m.regs.sf == m.regs.of)) { __blk = 0x8293; } else { __blk = 0x827f; }
            }
            0x827f => {
                // 0x0827f: mov ax, word ptr [0xa2c]
                m.regs.set_ax((m.read16(m.regs.ds, 0xa2c)) as u16);
                // 0x08282: cmp ax, word ptr [si + 2]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ds, m.regs.si().wrapping_add(0x2))) as u16);
                // 0x08285: jl 0x8293
                if (m.regs.sf != m.regs.of) { __blk = 0x8293; } else { __blk = 0x8287; }
            }
            0x8287 => {
                // 0x08287: sub ax, word ptr [si + 6]
                let __r = m.regs.sub16((m.regs.ax()) as u16, (m.read16(m.regs.ds, m.regs.si().wrapping_add(0x6))) as u16);
                m.regs.set_ax(__r);
                // 0x0828a: cmp ax, word ptr [si + 2]
                m.regs.cmp16((m.regs.ax()) as u16, (m.read16(m.regs.ds, m.regs.si().wrapping_add(0x2))) as u16);
                // 0x0828d: jg 0x8293
                if (!m.regs.zf && (m.regs.sf == m.regs.of)) { __blk = 0x8293; } else { __blk = 0x828f; }
            }
            0x828f => {
                // 0x0828f: or byte ptr [bp], 8
                let __r = m.regs.or8((m.read8(m.regs.ss, m.regs.bp())) as u8, (0x8) as u8);
                m.write8(m.regs.ss, m.regs.bp(), __r);
                __blk = 0x8293;
            }
            0x8293 => {
                // 0x08293: pop ax
                let __v = m.read16(m.regs.ss, m.regs.sp());
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_ax((__v) as u16);
                // 0x08294: ret 
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn func_a3ad(m: &mut Machine) {
    let mut __blk: u32 = 0xa3ad;
    loop {
        match __blk {
            0xa3ad => {
                // 0x0a3ad: mov ax, word ptr [0xd8c]
                m.regs.set_ax((m.read16(m.regs.ds, 0xd8c)) as u16);
                // 0x0a3b0: mov bx, word ptr [0xd90]
                m.regs.set_bx((m.read16(m.regs.ds, 0xd90)) as u16);
                // 0x0a3b4: cmp ax, bx
                m.regs.cmp16((m.regs.ax()) as u16, (m.regs.bx()) as u16);
                // 0x0a3b6: jae 0xa3c1
                if !m.regs.cf { __blk = 0xa3c1; } else { __blk = 0xa3b8; }
            }
            0xa3b8 => {
                // 0x0a3b8: add ax, cx
                let __r = m.regs.add16((m.regs.ax()) as u16, (m.regs.cx()) as u16);
                m.regs.set_ax(__r);
                // 0x0a3ba: add ax, 0x12
                let __r = m.regs.add16((m.regs.ax()) as u16, (0x12) as u16);
                m.regs.set_ax(__r);
                // 0x0a3bd: cmp bx, ax
                m.regs.cmp16((m.regs.bx()) as u16, (m.regs.ax()) as u16);
                // 0x0a3bf: jb 0xa3cf
                if m.regs.cf { __blk = 0xa3cf; } else { __blk = 0xa3c1; }
            }
            0xa3c1 => {
                // 0x0a3c1: mov ax, word ptr [0xd9a]
                m.regs.set_ax((m.read16(m.regs.ds, 0xd9a)) as u16);
                // 0x0a3c4: add ax, 0xa
                let __r = m.regs.add16((m.regs.ax()) as u16, (0xa) as u16);
                m.regs.set_ax(__r);
                // 0x0a3c7: add ax, cx
                let __r = m.regs.add16((m.regs.ax()) as u16, (m.regs.cx()) as u16);
                m.regs.set_ax(__r);
                // 0x0a3c9: jb 0xa3cf
                if m.regs.cf { __blk = 0xa3cf; } else { __blk = 0xa3cb; }
            }
            0xa3cb => {
                // 0x0a3cb: cmp word ptr [0xd98], ax
                m.regs.cmp16((m.read16(m.regs.ds, 0xd98)) as u16, (m.regs.ax()) as u16);
                __blk = 0xa3cf;
            }
            0xa3cf => {
                // 0x0a3cf: ret 
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn func_b75c(m: &mut Machine) {
    let mut __blk: u32 = 0xb75c;
    loop {
        match __blk {
            0xb75c => {
                // 0x0b75c: push ax
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp(), (m.regs.ax()) as u16);
                // 0x0b75d: push bx
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp(), (m.regs.bx()) as u16);
                // 0x0b75e: test byte ptr [0x252f], 1
                m.regs.test8((m.read8(m.regs.ds, 0x252f)) as u8, (0x1) as u8);
                // 0x0b763: je 0xb785
                if m.regs.zf { __blk = 0xb785; } else { __blk = 0xb765; }
            }
            0xb765 => {
                // 0x0b765: mov ax, word ptr [0x2527]
                m.regs.set_ax((m.read16(m.regs.ds, 0x2527)) as u16);
                // 0x0b768: cmp ax, 0x41
                m.regs.cmp16((m.regs.ax()) as u16, (0x41) as u16);
                // 0x0b76b: je 0xb77e
                if m.regs.zf { __blk = 0xb77e; } else { __blk = 0xb76d; }
            }
            0xb76d => {
                // 0x0b76d: add al, byte ptr [0x2531]
                let __r = m.regs.add8((m.regs.al()) as u8, (m.read8(m.regs.ds, 0x2531)) as u8);
                m.regs.set_al(__r);
                // 0x0b771: cmp ax, 0x41
                m.regs.cmp16((m.regs.ax()) as u16, (0x41) as u16);
                // 0x0b774: jl 0xb779
                if (m.regs.sf != m.regs.of) { __blk = 0xb779; } else { __blk = 0xb776; }
            }
            0xb776 => {
                // 0x0b776: mov ax, 0x41
                m.regs.set_ax((0x41) as u16);
                __blk = 0xb779;
            }
            0xb779 => {
                // 0x0b779: mov word ptr [0x2527], ax
                m.write16(m.regs.ds, 0x2527, (m.regs.ax()) as u16);
                // 0x0b77c: jmp 0xb7a5
                __blk = 0xb7a5;
            }
            0xb77e => {
                // 0x0b77e: mov byte ptr [0x252f], 0
                m.write8(m.regs.ds, 0x252f, (0x0) as u8);
                // 0x0b783: jmp 0xb7a5
                __blk = 0xb7a5;
            }
            0xb785 => {
                // 0x0b785: test byte ptr [0x2530], 1
                m.regs.test8((m.read8(m.regs.ds, 0x2530)) as u8, (0x1) as u8);
                // 0x0b78a: je 0xb7a5
                if m.regs.zf { __blk = 0xb7a5; } else { __blk = 0xb78c; }
            }
            0xb78c => {
                // 0x0b78c: mov ax, word ptr [0x2527]
                m.regs.set_ax((m.read16(m.regs.ds, 0x2527)) as u16);
                // 0x0b78f: or ax, ax
                let __r = m.regs.or16((m.regs.ax()) as u16, (m.regs.ax()) as u16);
                m.regs.set_ax(__r);
                // 0x0b791: je 0xb7a0
                if m.regs.zf { __blk = 0xb7a0; } else { __blk = 0xb793; }
            }
            0xb793 => {
                // 0x0b793: sub al, byte ptr [0x2531]
                let __r = m.regs.sub8((m.regs.al()) as u8, (m.read8(m.regs.ds, 0x2531)) as u8);
                m.regs.set_al(__r);
                // 0x0b797: jns 0xb79b
                if !m.regs.sf { __blk = 0xb79b; } else { __blk = 0xb799; }
            }
            0xb799 => {
                // 0x0b799: xor ax, ax
                let __r = m.regs.xor16((m.regs.ax()) as u16, (m.regs.ax()) as u16);
                m.regs.set_ax(__r);
                __blk = 0xb79b;
            }
            0xb79b => {
                // 0x0b79b: mov word ptr [0x2527], ax
                m.write16(m.regs.ds, 0x2527, (m.regs.ax()) as u16);
                // 0x0b79e: jmp 0xb7a5
                __blk = 0xb7a5;
            }
            0xb7a0 => {
                // 0x0b7a0: mov byte ptr [0x2530], 0
                m.write8(m.regs.ds, 0x2530, (0x0) as u8);
                __blk = 0xb7a5;
            }
            0xb7a5 => {
                // 0x0b7a5: pop bx
                let __v = m.read16(m.regs.ss, m.regs.sp());
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_bx((__v) as u16);
                // 0x0b7a6: pop ax
                let __v = m.read16(m.regs.ss, m.regs.sp());
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_ax((__v) as u16);
                // 0x0b7a7: ret 
                return;
            }
            _ => unreachable!(),
        }
    }
}
