//! 1-to-1 static recompilation of BLOODPRG.EXE (path B).
//!
//! Each function here is lifted directly from the disassembly to operate on the shared
//! [`Machine`], reproducing the exact register + memory effects of the original. Correctness is
//! established per-function by the Unicorn oracle: `re/tools/gen_oracle_vectors.py` fuzzes the
//! real DOS function and dumps (input-state → output-state) vectors, and the tests below replay
//! each vector through the lifted Rust and assert bit-exact equality. When every reachable
//! function is lifted + verified and composed in the binary's call graph, the whole program runs
//! identically by construction (see re/tools/README_oracle.md).

// Generated by re/tools/gen_batch.py; its transliterated expressions carry redundant
// parens the generator emits verbatim. Silence that one lint for the generated module
// (it is oracle-verified bit-exact, not hand-maintained) instead of editing generated code.
#[allow(unused_parens)]
pub mod auto;
pub mod interp;
pub mod io_lift;
pub mod machine;
pub mod ptr_leaves;
#[allow(unused_parens)]
pub mod ptr_leaves_gen;
pub mod runtime;

use machine::Machine;

/// `prng_2de2` — the game PRNG at file 0x2DE2 (far 0x1CE:0x0B02).
///
/// Input: `AX` = modulus. State (in the code segment): `cs:0xAEE` seed_word (u16), `cs:0xAF0` a,
/// `cs:0xAF1` b, `cs:0xAF2` counter. Output: `AX` = a value in `[0, modulus)` (or unchanged if
/// modulus == 0), with a/b/counter advanced. `bx/cx/dx` are preserved (push/pop). Lifted 1-to-1
/// from the disassembly (0x2DE2..0x2E32); verified bit-exact vs the binary by the oracle vectors.
pub fn prng_2de2(m: &mut Machine) {
    let cs = m.regs.cs;
    let modulus = m.regs.ax(); // mov dx, ax  (dx is scratch, restored by pop)

    // mov bl,cs:[0xAF0]; mov bh,cs:[0xAF1]; mov cx,8; xor ax,ax (clears CF)
    let mut bl = m.read8(cs, 0xaf0);
    let mut bh = m.read8(cs, 0xaf1);
    let mut ax: u16 = 0;
    let mut cf = false;
    // 8x: rcr bl,1 ; rcl ax,1 ; rcl bh,1 ; rcl ax,1
    for _ in 0..8 {
        let carry_out = bl & 1;
        bl = ((cf as u8) << 7) | (bl >> 1);
        cf = carry_out != 0;

        let carry_out = ax >> 15;
        ax = ax.wrapping_shl(1) | cf as u16;
        cf = carry_out != 0;

        let carry_out = bh >> 7;
        bh = bh.wrapping_shl(1) | cf as u8;
        cf = carry_out != 0;

        let carry_out = ax >> 15;
        ax = ax.wrapping_shl(1) | cf as u16;
        cf = carry_out != 0;
    }

    // mov bx,cs:[0xAEE]; shr bx,3  — dead (bx restored, bl overwritten below); read for fidelity.
    let _ = m.read16(cs, 0xaee) >> 3;

    // xor ax, cs:[0xAEE]  (mix in seed_word)
    ax ^= m.read16(cs, 0xaee);

    // inc byte cs:[0xAF2]; mov bl,cs:[0xAF2]; sub byte cs:[0xAF1],bl; rol bl,1; xor byte cs:[0xAF0],bl
    let counter = m.read8(cs, 0xaf2).wrapping_add(1);
    m.write8(cs, 0xaf2, counter);
    let new_b = m.read8(cs, 0xaf1).wrapping_sub(counter);
    m.write8(cs, 0xaf1, new_b);
    let rotated = counter.rotate_left(1);
    let new_a = m.read8(cs, 0xaf0) ^ rotated;
    m.write8(cs, 0xaf0, new_a);

    // or dx,dx; jne .. ; je ..  then  while ax >= dx: ax -= dx   (dx == modulus)
    if modulus != 0 {
        while ax >= modulus {
            ax = ax.wrapping_sub(modulus);
        }
    }
    m.regs.set_ax(ax);
    // bx/cx/dx are pushed then popped -> unchanged; we never touched m.regs.{bx,cx,dx}.
}

/// `func_a734` — file 0xA734: `add [DS:0xD8C],ax ; add [DS:0xD9A],ax ; clc ; ret`.
/// Adds `AX` into the two word globals (with full ADD flags from the second add), then clears
/// CF. `AX`/`DS` unchanged. Lifted 1-to-1; oracle-verified (return regs, memory, all 6 flags).
pub fn func_a734(m: &mut Machine) {
    let ds = m.regs.ds;
    let ax = m.regs.ax();
    let v1 = m.read16(ds, 0xd8c);
    let r1 = m.regs.add16(v1, ax);
    m.write16(ds, 0xd8c, r1);
    let v2 = m.read16(ds, 0xd9a);
    let r2 = m.regs.add16(v2, ax);
    m.write16(ds, 0xd9a, r2);
    m.regs.cf = false; // clc
}

/// `func_a744` — file 0xA744: initialise three word globals to constants (no input, no flags).
pub fn func_a744(m: &mut Machine) {
    let ds = m.regs.ds;
    m.write16(ds, 0xd62, 0x0000);
    m.write16(ds, 0xd64, 0xffff);
    m.write16(ds, 0xd66, 0xffff);
}

/// `func_9f80` — file 0x9F80: `bx=0x1FB5; add bx,ax (x4); mov bx,[bx]; ret`. Computes the table
/// address `0x1FB5 + 4*ax` (16-bit wrapping), reads the word there (DS-relative) into `BX`.
/// Flags come from the 4th `add`. Lifted 1-to-1; oracle-verified (BX + all 6 flags).
pub fn func_9f80(m: &mut Machine) {
    let ax = m.regs.ax();
    let mut addr: u16 = 0x1fb5;
    for _ in 0..4 {
        addr = m.regs.add16(addr, ax);
    }
    m.regs.set_bx(m.read16(m.regs.ds, addr as u32));
}

/// `func_533c` — file 0x533C (resource_get_field4): `push bx; shl ax,3; mov bx,ax;
/// mov eax,fs:[bx+4]; pop bx; retf`. Loads `EAX` from the dword at `fs:(ax*8 + 4)` — the +4 field
/// of the resource-table entry indexed by `AX`. `BX` preserved. Flags come from `shl ax,3`
/// (CF/ZF/SF/PF defined; OF/AF undefined for a >1-bit shift). Lifted 1-to-1; oracle-verified.
pub fn func_533c(m: &mut Machine) {
    let shifted = m.regs.shl16(m.regs.ax(), 3);
    m.regs.eax = m.read32(m.regs.fs, (shifted.wrapping_add(4)) as u32);
}

/// `func_a40b` — file 0xA40B: `cmp gs:[0xD5F],0; je .end; cmp gs:[0xD5F],1; .end: ret`. A
/// tri-state check of the byte at `gs:0xD5F`: leaves flags from `cmp(b,0)` if b==0, else from
/// `cmp(b,1)` (so the caller can branch <1 / ==1 / >1). No register/memory change. Oracle-verified.
pub fn func_a40b(m: &mut Machine) {
    let b = m.read8(m.regs.gs, 0xd5f);
    m.regs.cmp8(b, 0);
    if !m.regs.zf {
        m.regs.cmp8(b, 1);
    }
}

/// `func_a634` — file 0xA634: `test byte [DS←GS:0xB17],1; ret` (with AX/DS saved+restored).
/// Sets ZF from bit 0 of `gs:0xB17` (CF/OF cleared). No register/memory change. Oracle-verified
/// (CF/OF/ZF/SF/PF; AF undefined for TEST).
pub fn func_a634(m: &mut Machine) {
    let b = m.read8(m.regs.gs, 0xb17);
    m.regs.test8(b, 1);
}

/// `func_a73e` — file 0xA73E: init 4 word globals to 0/0/0xFFFF/0xFFFF (no input, no flags).
pub fn func_a73e(m: &mut Machine) {
    let ds = m.regs.ds;
    m.write16(ds, 0xd60, 0x0000);
    m.write16(ds, 0xd62, 0x0000);
    m.write16(ds, 0xd64, 0xffff);
    m.write16(ds, 0xd66, 0xffff);
}

/// `func_6023` — file 0x6023: `push bx; shl ax,4; bsf bx,bx; add bx,ax; mov al,gs:[bx+0x6D60];
/// CBW; pop bx; ret`. Indexes a byte table at `gs:0x6D60` by `bsf(bx) + (ax<<4)`, sign-extends
/// the byte from `AL` into `AX` (byte `98` is CBW in 16-bit mode — the oracle caught this vs
/// capstone's "cwde" mislabel). `BX` preserved. Flags from the final `add`. Contract: `BX != 0`
/// (bsf of 0 is undefined). Lifted 1-to-1; oracle-verified.
pub fn func_6023(m: &mut Machine) {
    let shifted = m.regs.shl16(m.regs.ax(), 4);
    m.regs.set_ax(shifted);
    let idx = m.regs.bx().trailing_zeros() as u16; // bsf bx,bx (bx != 0)
    let addr = m.regs.add16(idx, m.regs.ax()); // add bx,ax -> final flags
    let al = m.read8(m.regs.gs, (addr.wrapping_add(0x6d60)) as u32);
    m.regs.set_al(al);
    // cbw: AX = sign-extend(AL); EAX high word unchanged.
    let signed = m.regs.al() as i8 as i16 as u16;
    m.regs.set_ax(signed);
}

/// `func_a757` — file 0xA757: a state reset. `ax=[0xA7E]; [0xD8E]=ax; [0xD92]=ax; xor ax,ax;
/// [0xD8C]=[0xD90]=[0xD9A]=[0xDA0]=[0xD96]=0; ax=[0x5233]; [0xD98]=ax; retf`. Flags from the
/// `xor ax,ax` (ZF=1, SF=0, PF=1, CF=0, OF=0; AF undefined). Lifted 1-to-1; oracle-verified.
pub fn func_a757(m: &mut Machine) {
    let ds = m.regs.ds;
    let a = m.read16(ds, 0xa7e);
    m.regs.set_ax(a);
    m.write16(ds, 0xd8e, a);
    m.write16(ds, 0xd92, a);
    let z = m.regs.xor16(a, a);
    m.regs.set_ax(z);
    m.write16(ds, 0xd8c, z);
    m.write16(ds, 0xd90, z);
    m.write16(ds, 0xd9a, z);
    m.write16(ds, 0xda0, z);
    m.write16(ds, 0xd96, z);
    let b = m.read16(ds, 0x5233);
    m.regs.set_ax(b);
    m.write16(ds, 0xd98, b);
}

#[cfg(test)]
mod tests {
    use super::machine::Machine;
    use super::*;
    use serde::Deserialize;
    use std::collections::HashMap;

    #[derive(Deserialize)]
    struct GenVec {
        regs_in: HashMap<String, u16>,
        segs: HashMap<String, u16>,
        mem_in: Vec<(usize, u8)>,
        regs_out: HashMap<String, u32>,
        mem_writes: Vec<(usize, u8)>,
        flags: Flags,
    }

    fn set_gp(m: &mut Machine, r: &str, v: u16) {
        match r {
            "ax" => m.regs.set_ax(v),
            "bx" => m.regs.set_bx(v),
            "cx" => m.regs.set_cx(v),
            "dx" => m.regs.set_dx(v),
            "si" => m.regs.set_si(v),
            "di" => m.regs.set_di(v),
            "bp" => m.regs.set_bp(v),
            "sp" => m.regs.set_sp(v),
            _ => panic!("gp {r}"),
        }
    }
    fn set_seg(m: &mut Machine, s: &str, v: u16) {
        match s {
            "ds" => m.regs.ds = v,
            "es" => m.regs.es = v,
            "fs" => m.regs.fs = v,
            "gs" => m.regs.gs = v,
            "ss" => m.regs.ss = v,
            _ => panic!("seg {s}"),
        }
    }
    fn get_e(m: &Machine, r: &str) -> u32 {
        match r {
            "eax" => m.regs.eax,
            "ebx" => m.regs.ebx,
            "ecx" => m.regs.ecx,
            "edx" => m.regs.edx,
            "esi" => m.regs.esi,
            "edi" => m.regs.edi,
            "ebp" => m.regs.ebp,
            "esp" => m.regs.esp,
            _ => panic!("e {r}"),
        }
    }

    /// The generic verifier: run `f` on each auto-generated vector (all registers fuzzed, input
    /// memory discovered) and assert the full output state — every register, every memory write,
    /// and (when `check_flags`) all six flags — matches the real binary. This is the fully
    /// automated path-B check: `lift.py` emits `f`, `auto_oracle.py` emits the vectors.
    /// Returns whether vectors were FOUND. A missing file used to `return` and let
    /// the batch pass silently, so deleting or renaming a vector file would have
    /// quietly dropped that function from verification while the test still
    /// claimed to cover it. The batches now assert on the found count.
    fn verify_generic(name: &str, f: fn(&mut Machine), check_flags: bool) -> bool {
        let raw =
            match std::fs::read_to_string(format!("re/tools/oracle_vectors/{name}_generic.json"))
                .or_else(|_| {
                    std::fs::read_to_string(format!(
                        "../re/tools/oracle_vectors/{name}_generic.json"
                    ))
                }) {
                Ok(s) => s,
                Err(_) => return false,
            };
        let vecs: Vec<GenVec> = serde_json::from_str(&raw).unwrap();
        assert!(!vecs.is_empty());
        for (i, v) in vecs.iter().enumerate() {
            let mut m = Machine::new();
            for (r, val) in &v.regs_in {
                set_gp(&mut m, r, *val);
            }
            for (s, val) in &v.segs {
                set_seg(&mut m, s, *val);
            }
            for (addr, byte) in &v.mem_in {
                m.mem[*addr] = *byte;
            }
            f(&mut m);
            for (r, val) in &v.regs_out {
                assert_eq!(get_e(&m, r), *val, "{name} vec {i}: {r}");
            }
            for (addr, byte) in &v.mem_writes {
                assert_eq!(m.mem[*addr], *byte, "{name} vec {i}: mem[{addr:#x}]");
            }
            if check_flags {
                assert_eq!(m.regs.cf, v.flags.cf, "{name} vec {i}: CF");
                assert_eq!(m.regs.pf, v.flags.pf, "{name} vec {i}: PF");
                assert_eq!(m.regs.af, v.flags.af, "{name} vec {i}: AF");
                assert_eq!(m.regs.zf, v.flags.zf, "{name} vec {i}: ZF");
                assert_eq!(m.regs.sf, v.flags.sf, "{name} vec {i}: SF");
                assert_eq!(m.regs.of, v.flags.of, "{name} vec {i}: OF");
            }
        }
        true
    }

    /// A deterministic-oracle vector: no `mem_in` (input memory IS the EXE image, loaded below).
    #[derive(Deserialize)]
    struct DetVec {
        regs_in: HashMap<String, u16>,
        segs: HashMap<String, u16>,
        regs_out: HashMap<String, u32>,
        mem_writes: Vec<(usize, u8)>,
        flags: Flags,
    }

    /// Load the raw BLOODPRG.EXE image (padded to 0x120000, exactly as the oracle maps it).
    fn load_exe_image() -> Option<Vec<u8>> {
        let raw = std::fs::read("re/bin/BLOODPRG.EXE")
            .or_else(|_| std::fs::read("../re/bin/BLOODPRG.EXE"))
            .ok()?;
        let mut img = raw;
        img.resize(0x120000, 0);
        Some(img)
    }

    /// Verify a lift against DETERMINISTIC oracle vectors (`{name}_det.json`): memory starts as the
    /// real EXE image (the Machine mirrors what Unicorn saw), so no `mem_in` capture is needed and
    /// there is no read hook to corrupt 16-bit `retf`. Asserts regs_out + every memory write are
    /// bit-exact. This is the oracle that can verify pointer-/sentinel-driven and composed
    /// (retf-callee) functions the random-fuzz oracle cannot.
    fn verify_det(name: &str, f: fn(&mut Machine), exe: &[u8]) -> bool {
        let raw = match std::fs::read_to_string(format!("re/tools/oracle_vectors/{name}_det.json"))
            .or_else(|_| std::fs::read_to_string(format!("../re/tools/oracle_vectors/{name}_det.json")))
        {
            Ok(s) => s,
            Err(_) => return false,
        };
        let vecs: Vec<DetVec> = serde_json::from_str(&raw).unwrap();
        assert!(!vecs.is_empty(), "{name}: no det vectors");
        // Addresses any vector writes — restored to the EXE image before each run so a correct
        // lift sees a pristine deterministic image every time.
        let mut m = Machine::new();
        m.mem[..exe.len()].copy_from_slice(exe);
        let written: std::collections::HashSet<usize> =
            vecs.iter().flat_map(|v| v.mem_writes.iter().map(|(a, _)| *a)).collect();
        for (i, v) in vecs.iter().enumerate() {
            for &a in &written {
                m.mem[a] = if a < exe.len() { exe[a] } else { 0 };
            }
            m.regs = super::machine::Regs::default();
            for (r, val) in &v.regs_in {
                set_gp(&mut m, r, *val);
            }
            for (s, val) in &v.segs {
                set_seg(&mut m, s, *val);
            }
            // return frame at ss:sp (retf pushes 4, near ret 2; sp already encodes which)
            let sp = m.regs.sp() as u32;
            m.write16(m.regs.ss, sp, 0x0000);
            m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
            f(&mut m);
            for (r, val) in &v.regs_out {
                assert_eq!(get_e(&m, r), *val, "{name} det vec {i}: {r}");
            }
            for (addr, byte) in &v.mem_writes {
                assert_eq!(m.mem[*addr], *byte, "{name} det vec {i}: mem[{addr:#x}]");
            }
        }
        true
    }

    /// One oracle vector of either kind (`flags` ignored — register/memory effects are the
    /// substantive state, mirroring the batch tests).
    #[derive(Deserialize)]
    struct AnyVec {
        regs_in: HashMap<String, u16>,
        segs: HashMap<String, u16>,
        #[serde(default)]
        mem_in: Vec<(usize, u8)>,
        regs_out: HashMap<String, u32>,
        mem_writes: Vec<(usize, u8)>,
    }

    /// M1 gate for the path-B RUNTIME: the real-mode interpreter (`interp::Cpu`) must replay the
    /// ENTIRE oracle corpus — every function, generic and deterministic — by executing the
    /// ORIGINAL EXE bytes, with the same pass criteria as the lifted batches (all output
    /// registers + every recorded memory write bit-exact).
    ///
    /// Memory layout mirrors the oracle exactly: the raw EXE image at physical 0 (CS=0, entry =
    /// file offset), plus for generic vectors the recorded `mem_in` overlay, and for det vectors
    /// the far-callee copies `gen_det` mirrored (far_copies.json) + the return frame.
    #[test]
    fn interp_replays_full_oracle_corpus() {
        let exe = match load_exe_image() {
            Some(e) => e,
            None => return,
        };
        let dir = if std::path::Path::new("re/tools/oracle_vectors").is_dir() {
            "re/tools/oracle_vectors"
        } else {
            "../re/tools/oracle_vectors"
        };
        let far_copies: HashMap<String, Vec<usize>> =
            std::fs::read_to_string(format!("{dir}/far_copies.json"))
                .map(|s| serde_json::from_str(&s).unwrap())
                .unwrap_or_default();

        let mut names: Vec<(String, bool, u16)> = vec![];
        for e in std::fs::read_dir(dir).unwrap() {
            let f = e.unwrap().file_name().into_string().unwrap();
            for (suffix, det) in [("_generic.json", false), ("_det.json", true)] {
                if let Some(stem) = f.strip_suffix(suffix) {
                    if let Some(hexpart) = stem.strip_prefix("func_") {
                        if let Ok(entry) = u16::from_str_radix(hexpart, 16) {
                            names.push((stem.to_string(), det, entry));
                        }
                    }
                }
            }
        }
        names.sort();
        assert!(!names.is_empty(), "no oracle vectors found in {dir}");

        let mut m = Machine::new();
        let mut failures: Vec<String> = vec![];
        let mut unimpl: HashMap<String, usize> = HashMap::new();
        let (mut nfuncs, mut nvecs) = (0usize, 0usize);
        for (name, det, entry) in &names {
            let suffix = if *det { "det" } else { "generic" };
            let raw = std::fs::read_to_string(format!("{dir}/{name}_{suffix}.json")).unwrap();
            let vecs: Vec<AnyVec> = serde_json::from_str(&raw).unwrap();
            nfuncs += 1;
            'vecs: for (i, v) in vecs.iter().enumerate() {
                nvecs += 1;
                m.mem[..exe.len()].copy_from_slice(&exe);
                m.mem[exe.len()..].fill(0);
                if *det {
                    if let Some(ts) = far_copies.get(name) {
                        for &t in ts {
                            let len = 0x800.min(exe.len() - t);
                            m.mem[t - 0x600..t - 0x600 + len].copy_from_slice(&exe[t..t + len]);
                        }
                    }
                }
                for (addr, byte) in &v.mem_in {
                    m.mem[*addr] = *byte;
                }
                m.regs = super::machine::Regs::default();
                for (r, val) in &v.regs_in {
                    set_gp(&mut m, r, *val);
                }
                for (s, val) in &v.segs {
                    set_seg(&mut m, s, *val);
                }
                if *det {
                    let sp = m.regs.sp() as u32;
                    m.write16(m.regs.ss, sp, 0x0000);
                    m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
                }
                let mut cpu = interp::Cpu::new(0, *entry);
                cpu.iflag = false; // Unicorn's initial EFLAGS has IF=0; pushf must match it
                match cpu.run(&mut m, 2_000_000) {
                    interp::Exit::Ret | interp::Exit::Retf => {}
                    interp::Exit::Unimplemented { cs, ip, byte, what } => {
                        *unimpl.entry(format!("{what} (op {byte:#04x})")).or_default() += 1;
                        failures.push(format!(
                            "{name} vec {i}: UNIMPLEMENTED {what} op {byte:#04x} near {cs:#06x}:{ip:#06x}"
                        ));
                        break 'vecs;
                    }
                    other => {
                        failures.push(format!("{name} vec {i}: unexpected exit {other:?}"));
                        break 'vecs;
                    }
                }
                for (r, val) in &v.regs_out {
                    let got = get_e(&m, r);
                    if got != *val {
                        failures.push(format!("{name} vec {i}: {r} = {got:#x}, want {val:#x}"));
                        break 'vecs;
                    }
                }
                for (addr, byte) in &v.mem_writes {
                    if m.mem[*addr] != *byte {
                        failures.push(format!(
                            "{name} vec {i}: mem[{addr:#x}] = {:#04x}, want {byte:#04x}",
                            m.mem[*addr]
                        ));
                        break 'vecs;
                    }
                }
            }
        }
        println!("interp corpus: {nfuncs} function/vector-files, {nvecs} vectors replayed");
        if !unimpl.is_empty() {
            let mut h: Vec<_> = unimpl.into_iter().collect();
            h.sort_by_key(|(_, n)| std::cmp::Reverse(*n));
            println!("unimplemented histogram: {h:?}");
        }
        assert!(
            failures.is_empty(),
            "interp corpus: {} failing functions:\n{}",
            failures.len(),
            failures.join("\n")
        );
    }

    /// One differential-fuzz vector (re/tools/diff_fuzz.py): a single instruction, input state,
    /// and Unicorn's ground-truth output. Memory is the deterministic fill `fill(a)`.
    #[derive(Deserialize)]
    struct DiffVec {
        code: String,
        asm: String,
        regs_in: HashMap<String, u32>,
        segs: HashMap<String, u16>,
        flags_in: u16,
        regs_out: HashMap<String, u32>,
        segs_out: HashMap<String, u16>,
        ip_out: u16,
        flags_out: u16,
        mem_writes: Vec<(usize, u8)>,
    }

    /// M1b: harden the interpreter beyond the corpus' mix by differentially fuzzing EVERY unique
    /// instruction encoding in the game's code (+ the SND driver) against Unicorn, one instruction
    /// at a time. Asserts GP registers, IP, memory writes, and the DEFINED arithmetic flags match.
    /// (Flags left architecturally undefined by an instruction are not asserted — same policy as
    /// the oracle; we compare only flags both models define deterministically per opcode class.)
    #[test]
    fn interp_matches_unicorn_diff() {
        let dir = if std::path::Path::new("re/tools/oracle_vectors").is_dir() {
            "re/tools/oracle_vectors"
        } else {
            "../re/tools/oracle_vectors"
        };
        let raw = match std::fs::read_to_string(format!("{dir}/diff_fuzz.json")) {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        let vecs: Vec<DiffVec> = serde_json::from_str(&raw).unwrap();
        assert!(!vecs.is_empty());
        const CS_BASE: u16 = 0x1000;
        const MEM_TOP: usize = 0x110000;
        let fill = |a: usize| -> u8 { ((a.wrapping_mul(2654435761) >> 16) & 0xFF) as u8 };

        let mut fails: Vec<String> = vec![];
        let mut checked = 0usize;
        // Which arithmetic flags an instruction leaves defined — keyed by mnemonic. Anything not
        // listed: compare none (mul/div/shifts-by-cl/etc. have undefined flags Unicorn fills
        // differently). This mirrors machine.rs's "assigned but not asserted" policy.
        let all6 = 0x8d5u16; // CF PF AF ZF SF OF bit positions mask (0,2,4,6,7,11)
        for (i, v) in vecs.iter().enumerate() {
            let code = (0..v.code.len() / 2)
                .map(|k| u8::from_str_radix(&v.code[k * 2..k * 2 + 2], 16).unwrap())
                .collect::<Vec<u8>>();
            let mut m = Machine::new();
            // deterministic memory fill
            for a in 0..MEM_TOP {
                m.mem[a] = fill(a);
            }
            let base = (CS_BASE as usize) * 16;
            m.mem[base..base + code.len()].copy_from_slice(&code);
            for (r, val) in &v.regs_in {
                match r.as_str() {
                    "eax" => m.regs.eax = *val,
                    "ebx" => m.regs.ebx = *val,
                    "ecx" => m.regs.ecx = *val,
                    "edx" => m.regs.edx = *val,
                    "esi" => m.regs.esi = *val,
                    "edi" => m.regs.edi = *val,
                    "ebp" => m.regs.ebp = *val,
                    "esp" => m.regs.esp = *val,
                    _ => {}
                }
            }
            for (s, val) in &v.segs {
                set_seg(&mut m, s, *val);
            }
            let f = v.flags_in;
            m.regs.cf = f & 1 != 0;
            m.regs.pf = f & 4 != 0;
            m.regs.af = f & 0x10 != 0;
            m.regs.zf = f & 0x40 != 0;
            m.regs.sf = f & 0x80 != 0;
            m.regs.df = f & 0x400 != 0;
            m.regs.of = f & 0x800 != 0;

            let mut cpu = interp::Cpu::new(CS_BASE, 0);
            cpu.flags_high = f & 0x7000;
            cpu.iflag = f & 0x200 != 0; // sync IF so pushf matches Unicorn's flag word
            cpu.depth = 1 << 30; // not oracle-replay: ret/retf must EXECUTE (pop), not stop
            let _ = cpu.step_public(&mut m);
            checked += 1;

            let mut bad = vec![];
            for (r, val) in &v.regs_out {
                if get_e(&m, r) != *val {
                    bad.push(format!("{r}={:#x}!={:#x}", get_e(&m, r), val));
                }
            }
            for (sname, sval) in &v.segs_out {
                let got = match sname.as_str() {
                    "ds" => m.regs.ds,
                    "es" => m.regs.es,
                    "ss" => m.regs.ss,
                    "fs" => m.regs.fs,
                    "gs" => m.regs.gs,
                    _ => continue,
                };
                if got != *sval {
                    bad.push(format!("{sname}={got:#x}!={sval:#x}"));
                }
            }
            if cpu.ip != v.ip_out {
                bad.push(format!("ip={:#x}!={:#x}", cpu.ip, v.ip_out));
            }
            for (addr, byte) in &v.mem_writes {
                if *addr < MEM_TOP && m.mem[*addr] != *byte {
                    bad.push(format!("mem[{addr:#x}]={:#x}!={byte:#x}", m.mem[*addr]));
                }
            }
            // Defined-flag comparison per opcode class.
            let mn = v.asm.split_whitespace().next().unwrap_or("");
            let defined: u16 = match mn {
                "add" | "sub" | "adc" | "sbb" | "cmp" | "neg" | "xadd" => all6,
                "and" | "or" | "xor" | "test" => 0x8d5 & !0x810, // CF/OF cleared, AF undefined
                "inc" | "dec" => all6 & !1, // CF unaffected
                // Shifts/rotates: CF is DEFINED (the bit shifted out / rotated through) for any
                // nonzero count; the other flags are count-dependent/undefined. A wrong carry-out
                // silently corrupts chained-rotate loops (e.g. the subtitle glyph plotter), so
                // assert CF here. (Count could be 0 → CF unchanged, but that still matches Unicorn.)
                "shl" | "shr" | "sar" | "rol" | "ror" | "sal" | "rcl" | "rcr" => 1, // CF (bit 0)
                "bt" | "btr" | "bts" | "btc" => 1, // CF only
                "bsf" | "bsr" => 0x40, // ZF only
                _ => 0,
            };
            let cur = (m.regs.cf as u16)
                | ((m.regs.pf as u16) << 2)
                | ((m.regs.af as u16) << 4)
                | ((m.regs.zf as u16) << 6)
                | ((m.regs.sf as u16) << 7)
                | ((m.regs.of as u16) << 11);
            if (cur ^ v.flags_out) & defined != 0 {
                bad.push(format!(
                    "flags {:#x}!={:#x} (defined {:#x})",
                    cur & defined,
                    v.flags_out & defined,
                    defined
                ));
            }
            if !bad.is_empty() && fails.len() < 40 {
                fails.push(format!("vec {i} [{}] {}: {}", v.code, v.asm, bad.join(", ")));
            } else if !bad.is_empty() {
                fails.push(String::new());
            }
        }
        let nfail = fails.iter().filter(|s| !s.is_empty()).count()
            + fails.iter().filter(|s| s.is_empty()).count();
        println!("diff-fuzz: {checked} instructions checked, {nfail} mismatched");
        let shown: Vec<&String> = fails.iter().filter(|s| !s.is_empty()).collect();
        assert!(
            shown.is_empty(),
            "diff-fuzz mismatches ({} shown):\n{}",
            shown.len(),
            shown.iter().map(|s| s.as_str()).collect::<Vec<_>>().join("\n")
        );
    }

    #[test]
    fn func_a734_generic_pipeline() {
        // Validates the full automated pipeline (generic oracle + generic verifier) against a
        // hand-lift with known-good semantics. add+clc: all flags defined.
        verify_generic("func_a734", func_a734, true);
    }

    /// The AUTO-lifted batch (src/recomp/auto.rs, produced by lift.py) verified against
    /// auto-generated generic vectors (auto_oracle.py). Registers + every memory write must be
    /// bit-exact vs the real binary. Flags are checked separately per-function where all-defined;
    /// here we assert the register + memory side effects (the substantive state), since some
    /// carry architecturally-undefined flag bits.
    #[test]
    fn auto_lifted_batch_matches_oracle() {
        let batch: &[(&str, fn(&mut Machine))] = &[
            ("func_149b", super::auto::func_149b),
            ("func_1fbc", super::auto::func_1fbc),
            ("func_242d", super::auto::func_242d),
            ("func_248b", super::auto::func_248b),
            ("func_25a4", super::auto::func_25a4),
            ("func_2612", super::auto::func_2612),
            ("func_2e73", super::auto::func_2e73),
            ("func_3066", super::auto::func_3066),
            ("func_30cd", super::auto::func_30cd),
            ("func_3106", super::auto::func_3106),
            ("func_3192", super::auto::func_3192),
            ("func_32ac", super::auto::func_32ac),
            ("func_3321", super::auto::func_3321),
            ("func_339e", super::auto::func_339e),
            ("func_3c6c", super::auto::func_3c6c),
            ("func_3d7b", super::auto::func_3d7b),
            ("func_3dbf", super::auto::func_3dbf),
            ("func_414e", super::auto::func_414e),
            ("func_41d1", super::auto::func_41d1),
            ("func_420d", super::auto::func_420d),
            ("func_42cd", super::auto::func_42cd),
            ("func_509d", super::auto::func_509d),
            ("func_5320", super::auto::func_5320),
            ("func_533c", super::auto::func_533c),
            ("func_577a", super::auto::func_577a),
            ("func_5791", super::auto::func_5791),
            ("func_5fd8", super::auto::func_5fd8),
            ("func_5ff6", super::auto::func_5ff6),
            ("func_6023", super::auto::func_6023),
            ("func_78d0", super::auto::func_78d0),
            ("func_7cb4", super::auto::func_7cb4),
            ("func_8269", super::auto::func_8269),
            ("func_8295", super::auto::func_8295),
            ("func_9510", super::auto::func_9510),
            ("func_963f", super::auto::func_963f),
            ("func_98b9", super::auto::func_98b9),
            ("func_9b04", super::auto::func_9b04),
            ("func_9f80", super::auto::func_9f80),
            ("func_a117", super::auto::func_a117),
            ("func_a38e", super::auto::func_a38e),
            ("func_a3ad", super::auto::func_a3ad),
            ("func_a3d0", super::auto::func_a3d0),
            ("func_a40b", super::auto::func_a40b),
            ("func_a634", super::auto::func_a634),
            ("func_a734", super::auto::func_a734),
            ("func_a73e", super::auto::func_a73e),
            ("func_a744", super::auto::func_a744),
            ("func_a757", super::auto::func_a757),
            ("func_a7e6", super::auto::func_a7e6),
            ("func_aabc", super::auto::func_aabc),
            ("func_ad96", super::auto::func_ad96),
            ("func_b75c", super::auto::func_b75c),
        ];
        let mut failures = Vec::new();
        let mut unverified = Vec::new();
        for (name, f) in batch {
            let f = *f;
            let name = *name;
            match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                verify_generic(name, f, false)
            })) {
                Err(_) => failures.push(name),
                Ok(false) => unverified.push(name),
                Ok(true) => {}
            }
        }
        assert!(
            failures.is_empty(),
            "{}/{} auto-lifts failed generic verification: {:?}",
            failures.len(),
            batch.len(),
            failures
        );
        // A function with no vector file is NOT verified, and this test used to
        // pass anyway. All-or-nothing: a checkout without the vectors skips the
        // whole batch, but a batch that has some and is missing others is a hole.
        assert!(
            unverified.is_empty() || unverified.len() == batch.len(),
            "{}/{} auto-lifts have NO oracle vectors and were silently skipped: {:?}",
            unverified.len(),
            batch.len(),
            unverified
        );
    }

    /// The DETERMINISTIC batch: pointer-/sentinel-driven leaves the random-fuzz oracle cannot
    /// verify (non-terminating or garbage-dereferencing under random memory). Verified against
    /// the real EXE image (mirrored into the Machine) — includes retf functions the read-hook
    /// oracle mishandles. Registers + every memory write must be bit-exact vs the binary.
    #[test]
    fn det_lifted_batch_matches_oracle() {
        let Some(exe) = load_exe_image() else { return };
        let batch: &[(&str, fn(&mut Machine))] = &[
            ("func_1d94", super::auto::func_1d94),
            ("func_2de2", super::auto::func_2de2),
            ("func_4240", super::auto::func_4240),
            ("func_43f7", super::auto::func_43f7),
            ("func_5afd", super::auto::func_5afd),
            ("func_604e", super::auto::func_604e),
            ("func_92a3", super::auto::func_92a3),
            ("func_933a", super::auto::func_933a),
            ("func_9364", super::auto::func_9364),
            ("func_1e5d", super::auto::func_1e5d),
            ("func_555b", super::auto::func_555b),
            ("func_1dd8", super::auto::func_1dd8),
            ("func_713d", super::auto::func_713d),
            ("func_3b45", super::auto::func_3b45),
            ("func_8bab", super::auto::func_8bab),
            ("func_7ce8", super::auto::func_7ce8),
            ("func_3b85", super::auto::func_3b85),
            ("func_82c3", super::auto::func_82c3),
            ("func_40d0", super::auto::func_40d0),
            ("func_9240", super::auto::func_9240),
            ("func_726", super::auto::func_726),
            ("func_14ca", super::auto::func_14ca),
            ("func_792d", super::auto::func_792d),
        ];
        let mut failures = Vec::new();
        let mut unverified = Vec::new();
        for (name, f) in batch {
            let (f, name) = (*f, *name);
            match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                verify_det(name, f, &exe)
            })) {
                Err(_) => failures.push(name),
                Ok(false) => unverified.push(name),
                Ok(true) => {}
            }
        }
        assert!(
            failures.is_empty(),
            "{}/{} det auto-lifts failed verification: {:?}",
            failures.len(),
            batch.len(),
            failures
        );
        assert!(
            unverified.is_empty() || unverified.len() == batch.len(),
            "{}/{} det auto-lifts have NO oracle vectors and were silently skipped: {:?}",
            unverified.len(),
            batch.len(),
            unverified
        );
    }

    #[test]
    fn func_a757_matches_oracle_vectors() {
        #[derive(Deserialize)]
        struct V {
            a7e: u16,
            r5233: u16,
            ax_out: u16,
            flags: Flags,
            mem: std::collections::HashMap<String, u16>,
        }
        let raw = match std::fs::read_to_string("re/tools/oracle_vectors/func_a757.json")
            .or_else(|_| std::fs::read_to_string("../re/tools/oracle_vectors/func_a757.json"))
        {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        const DS: u16 = 0x2000;
        for (i, v) in serde_json::from_str::<Vec<V>>(&raw)
            .unwrap()
            .iter()
            .enumerate()
        {
            let mut m = Machine::new();
            m.regs.ds = DS;
            m.write16(DS, 0xa7e, v.a7e);
            m.write16(DS, 0x5233, v.r5233);
            func_a757(&mut m);
            assert_eq!(m.regs.ax(), v.ax_out, "vec {i}: AX");
            for off in [0xd8c, 0xd8e, 0xd90, 0xd92, 0xd96, 0xd98, 0xd9a, 0xda0] {
                let want = v.mem[&format!("{off}")];
                assert_eq!(m.read16(DS, off), want, "vec {i}: [{off:#x}]");
            }
            // xor ax,ax flags (AF undefined -> not asserted).
            assert_eq!(m.regs.cf, v.flags.cf, "vec {i}: CF");
            assert_eq!(m.regs.of, v.flags.of, "vec {i}: OF");
            assert_eq!(m.regs.zf, v.flags.zf, "vec {i}: ZF");
            assert_eq!(m.regs.sf, v.flags.sf, "vec {i}: SF");
            assert_eq!(m.regs.pf, v.flags.pf, "vec {i}: PF");
        }
    }

    #[test]
    fn func_a73e_matches_oracle_vectors() {
        #[derive(Deserialize)]
        struct V {
            a: u16,
            b: u16,
            c: u16,
            dd: u16,
        }
        let raw = match std::fs::read_to_string("re/tools/oracle_vectors/func_a73e.json")
            .or_else(|_| std::fs::read_to_string("../re/tools/oracle_vectors/func_a73e.json"))
        {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        const DS: u16 = 0x2000;
        for (i, v) in serde_json::from_str::<Vec<V>>(&raw)
            .unwrap()
            .iter()
            .enumerate()
        {
            let mut m = Machine::new();
            m.regs.ds = DS;
            func_a73e(&mut m);
            assert_eq!(m.read16(DS, 0xd60), v.a, "vec {i}");
            assert_eq!(m.read16(DS, 0xd62), v.b, "vec {i}");
            assert_eq!(m.read16(DS, 0xd64), v.c, "vec {i}");
            assert_eq!(m.read16(DS, 0xd66), v.dd, "vec {i}");
        }
    }

    #[test]
    fn func_6023_matches_oracle_vectors() {
        #[derive(Deserialize)]
        struct V {
            ax: u16,
            bx: u16,
            byte: u8,
            eax_out: u32,
            bx_out: u16,
            flags: Flags,
        }
        let raw = match std::fs::read_to_string("re/tools/oracle_vectors/func_6023.json")
            .or_else(|_| std::fs::read_to_string("../re/tools/oracle_vectors/func_6023.json"))
        {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        const GS: u16 = 0x3000;
        for (i, v) in serde_json::from_str::<Vec<V>>(&raw)
            .unwrap()
            .iter()
            .enumerate()
        {
            let mut m = Machine::new();
            m.regs.gs = GS;
            m.regs.set_ax(v.ax);
            m.regs.set_bx(v.bx);
            let shifted = (v.ax << 4) & 0xffff;
            let idx = v.bx.trailing_zeros() as u16;
            let addr = idx.wrapping_add(shifted);
            m.write8(GS, (addr.wrapping_add(0x6d60)) as u32, v.byte);
            func_6023(&mut m);
            assert_eq!(m.regs.eax, v.eax_out, "vec {i}: EAX");
            assert_eq!(m.regs.bx(), v.bx_out, "vec {i}: BX preserved");
            assert_eq!(m.regs.cf, v.flags.cf, "vec {i}: CF");
            assert_eq!(m.regs.pf, v.flags.pf, "vec {i}: PF");
            assert_eq!(m.regs.af, v.flags.af, "vec {i}: AF");
            assert_eq!(m.regs.zf, v.flags.zf, "vec {i}: ZF");
            assert_eq!(m.regs.sf, v.flags.sf, "vec {i}: SF");
            assert_eq!(m.regs.of, v.flags.of, "vec {i}: OF");
        }
    }

    #[derive(Deserialize)]
    struct ByteFlagsVec {
        #[allow(dead_code)]
        byte: u8,
        flags: Flags,
    }

    fn load_byte_flags(name: &str) -> Option<Vec<ByteFlagsVec>> {
        let raw = std::fs::read_to_string(format!("re/tools/oracle_vectors/{name}.json"))
            .or_else(|_| std::fs::read_to_string(format!("../re/tools/oracle_vectors/{name}.json")))
            .ok()?;
        Some(serde_json::from_str(&raw).unwrap())
    }

    #[test]
    fn func_a40b_matches_oracle_vectors() {
        let Some(vecs) = load_byte_flags("func_a40b") else {
            return;
        };
        const GS: u16 = 0x3000;
        for (i, v) in vecs.iter().enumerate() {
            let mut m = Machine::new();
            m.regs.gs = GS;
            m.write8(GS, 0xd5f, v.byte);
            func_a40b(&mut m);
            assert_eq!(m.regs.cf, v.flags.cf, "vec {i}: CF");
            assert_eq!(m.regs.pf, v.flags.pf, "vec {i}: PF");
            assert_eq!(m.regs.af, v.flags.af, "vec {i}: AF");
            assert_eq!(m.regs.zf, v.flags.zf, "vec {i}: ZF");
            assert_eq!(m.regs.sf, v.flags.sf, "vec {i}: SF");
            assert_eq!(m.regs.of, v.flags.of, "vec {i}: OF");
        }
    }

    #[test]
    fn func_a634_matches_oracle_vectors() {
        let Some(vecs) = load_byte_flags("func_a634") else {
            return;
        };
        const GS: u16 = 0x3000;
        for (i, v) in vecs.iter().enumerate() {
            let mut m = Machine::new();
            m.regs.gs = GS;
            m.write8(GS, 0xb17, v.byte);
            func_a634(&mut m);
            // TEST: CF/OF cleared, ZF/SF/PF from the AND (AF undefined).
            assert_eq!(m.regs.cf, v.flags.cf, "vec {i}: CF");
            assert_eq!(m.regs.of, v.flags.of, "vec {i}: OF");
            assert_eq!(m.regs.zf, v.flags.zf, "vec {i}: ZF");
            assert_eq!(m.regs.sf, v.flags.sf, "vec {i}: SF");
            assert_eq!(m.regs.pf, v.flags.pf, "vec {i}: PF");
        }
    }

    #[derive(Deserialize)]
    struct F533cVec {
        ax: u16,
        bx: u16,
        off: u16,
        dword: u32,
        eax_out: u32,
        bx_out: u16,
        flags: Flags,
    }

    #[test]
    fn func_533c_matches_oracle_vectors() {
        let raw = match std::fs::read_to_string("re/tools/oracle_vectors/func_533c.json")
            .or_else(|_| std::fs::read_to_string("../re/tools/oracle_vectors/func_533c.json"))
        {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        const FS: u16 = 0x4000;
        let vecs: Vec<F533cVec> = serde_json::from_str(&raw).unwrap();
        assert!(!vecs.is_empty());
        for (i, v) in vecs.iter().enumerate() {
            let mut m = Machine::new();
            m.regs.fs = FS;
            m.regs.set_ax(v.ax);
            m.regs.set_bx(v.bx);
            m.write32(FS, v.off as u32, v.dword);
            func_533c(&mut m);
            assert_eq!(m.regs.eax, v.eax_out, "vec {i}: EAX");
            assert_eq!(m.regs.bx(), v.bx_out, "vec {i}: BX preserved");
            // shl by 3: only CF/ZF/SF/PF are architecturally defined.
            assert_eq!(m.regs.cf, v.flags.cf, "vec {i}: CF");
            assert_eq!(m.regs.zf, v.flags.zf, "vec {i}: ZF");
            assert_eq!(m.regs.sf, v.flags.sf, "vec {i}: SF");
            assert_eq!(m.regs.pf, v.flags.pf, "vec {i}: PF");
        }
    }

    #[derive(Deserialize)]
    struct Flags {
        cf: bool,
        pf: bool,
        af: bool,
        zf: bool,
        sf: bool,
        of: bool,
    }

    #[derive(Deserialize)]
    struct A734Vec {
        ax: u16,
        w1: u16,
        w2: u16,
        ax_out: u16,
        flags: Flags,
        w1_out: u16,
        w2_out: u16,
    }

    #[test]
    fn func_a734_matches_oracle_vectors() {
        let raw = match std::fs::read_to_string("re/tools/oracle_vectors/func_a734.json")
            .or_else(|_| std::fs::read_to_string("../re/tools/oracle_vectors/func_a734.json"))
        {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        const DS: u16 = 0x2000;
        let vecs: Vec<A734Vec> = serde_json::from_str(&raw).unwrap();
        assert!(!vecs.is_empty());
        for (i, v) in vecs.iter().enumerate() {
            let mut m = Machine::new();
            m.regs.ds = DS;
            m.regs.set_ax(v.ax);
            m.write16(DS, 0xd8c, v.w1);
            m.write16(DS, 0xd9a, v.w2);
            func_a734(&mut m);
            assert_eq!(m.regs.ax(), v.ax_out, "vec {i}: AX");
            assert_eq!(m.read16(DS, 0xd8c), v.w1_out, "vec {i}: [0xD8C]");
            assert_eq!(m.read16(DS, 0xd9a), v.w2_out, "vec {i}: [0xD9A]");
            assert_eq!(m.regs.cf, v.flags.cf, "vec {i}: CF");
            assert_eq!(m.regs.pf, v.flags.pf, "vec {i}: PF");
            assert_eq!(m.regs.af, v.flags.af, "vec {i}: AF");
            assert_eq!(m.regs.zf, v.flags.zf, "vec {i}: ZF");
            assert_eq!(m.regs.sf, v.flags.sf, "vec {i}: SF");
            assert_eq!(m.regs.of, v.flags.of, "vec {i}: OF");
        }
    }

    #[derive(Deserialize)]
    struct A744Vec {
        a: u16,
        b: u16,
        c: u16,
    }

    #[test]
    fn func_a744_matches_oracle_vectors() {
        let raw = match std::fs::read_to_string("re/tools/oracle_vectors/func_a744.json")
            .or_else(|_| std::fs::read_to_string("../re/tools/oracle_vectors/func_a744.json"))
        {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        const DS: u16 = 0x2000;
        let vecs: Vec<A744Vec> = serde_json::from_str(&raw).unwrap();
        assert!(!vecs.is_empty());
        for (i, v) in vecs.iter().enumerate() {
            let mut m = Machine::new();
            m.regs.ds = DS;
            func_a744(&mut m);
            assert_eq!(m.read16(DS, 0xd62), v.a, "vec {i}: [0xD62]");
            assert_eq!(m.read16(DS, 0xd64), v.b, "vec {i}: [0xD64]");
            assert_eq!(m.read16(DS, 0xd66), v.c, "vec {i}: [0xD66]");
        }
    }

    #[derive(Deserialize)]
    struct F9f80Vec {
        ax: u16,
        word: u16,
        bx_out: u16,
        flags: Flags,
    }

    #[test]
    fn func_9f80_matches_oracle_vectors() {
        let raw = match std::fs::read_to_string("re/tools/oracle_vectors/func_9f80.json")
            .or_else(|_| std::fs::read_to_string("../re/tools/oracle_vectors/func_9f80.json"))
        {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        const DS: u16 = 0x2000;
        let vecs: Vec<F9f80Vec> = serde_json::from_str(&raw).unwrap();
        assert!(!vecs.is_empty());
        for (i, v) in vecs.iter().enumerate() {
            let mut m = Machine::new();
            m.regs.ds = DS;
            m.regs.set_ax(v.ax);
            let addr = (0x1fb5u16)
                .wrapping_add(v.ax)
                .wrapping_add(v.ax)
                .wrapping_add(v.ax)
                .wrapping_add(v.ax);
            m.write16(DS, addr as u32, v.word);
            func_9f80(&mut m);
            assert_eq!(m.regs.bx(), v.bx_out, "vec {i}: BX");
            assert_eq!(m.regs.cf, v.flags.cf, "vec {i}: CF");
            assert_eq!(m.regs.pf, v.flags.pf, "vec {i}: PF");
            assert_eq!(m.regs.af, v.flags.af, "vec {i}: AF");
            assert_eq!(m.regs.zf, v.flags.zf, "vec {i}: ZF");
            assert_eq!(m.regs.sf, v.flags.sf, "vec {i}: SF");
            assert_eq!(m.regs.of, v.flags.of, "vec {i}: OF");
        }
    }

    /// One oracle vector: the input machine state and the DOS binary's resulting output state,
    /// captured by running the real function in Unicorn (re/tools/gen_oracle_vectors.py).
    #[derive(Deserialize)]
    struct PrngVec {
        cs: u16,
        ax_in: u16,
        seed: u16,
        a: u8,
        b: u8,
        counter: u8,
        ax_out: u16,
        a_out: u8,
        b_out: u8,
        counter_out: u8,
    }

    #[test]
    fn prng_2de2_matches_oracle_vectors() {
        let raw = match std::fs::read_to_string("re/tools/oracle_vectors/prng_2de2.json")
            .or_else(|_| std::fs::read_to_string("../re/tools/oracle_vectors/prng_2de2.json"))
        {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        let vecs: Vec<PrngVec> = serde_json::from_str(&raw).unwrap();
        assert!(!vecs.is_empty());
        for (i, v) in vecs.iter().enumerate() {
            let mut m = Machine::new();
            m.regs.cs = v.cs;
            m.regs.set_ax(v.ax_in);
            m.write16(v.cs, 0xaee, v.seed);
            m.write8(v.cs, 0xaf0, v.a);
            m.write8(v.cs, 0xaf1, v.b);
            m.write8(v.cs, 0xaf2, v.counter);
            prng_2de2(&mut m);
            assert_eq!(m.regs.ax(), v.ax_out, "vec {i}: AX");
            assert_eq!(m.read8(v.cs, 0xaf0), v.a_out, "vec {i}: a");
            assert_eq!(m.read8(v.cs, 0xaf1), v.b_out, "vec {i}: b");
            assert_eq!(m.read8(v.cs, 0xaf2), v.counter_out, "vec {i}: counter");
            // seed_word (0xAEE) must be unchanged by this function.
            assert_eq!(m.read16(v.cs, 0xaee), v.seed, "vec {i}: seed unchanged");
        }
    }

    /// The REGION HIT-TEST against its lift (`func_8295`).
    ///
    /// `0x8295` is the shared console hit-test: gated on `[0xA3E]&1`, it takes a
    /// region record in BP as `{x, y, w, h}` and reports CF set when the cursor
    /// `[0xA2A]`/`[0xA2C]` is inside — INCLUSIVE at both edges (`jl`/`jg` skip
    /// only strictly outside). `confirm_box_click` was written against that shape
    /// in FIX #68 using the dialog's own two region records.
    #[test]
    fn native_confirm_regions_match_the_lifted_hit_test() {
        const GS: u16 = 0x2600;
        const MOUSE_X: u32 = 0x0A2A;
        const MOUSE_Y: u32 = 0x0A2C;
        const ENABLE: u32 = 0x0A3E;
        const REGION_AT: u32 = 0x3100;

        let hit = |rect: (usize, usize, usize, usize), mx: i32, my: i32| -> bool {
            let mut m = Machine::new();
            m.regs.ds = GS;
            m.regs.gs = GS;
            m.regs.ss = GS;
            m.regs.set_sp(0xFF00);
            m.write8(GS, ENABLE, 1);
            m.write16(GS, MOUSE_X, mx as u16);
            m.write16(GS, MOUSE_Y, my as u16);
            m.write16(GS, REGION_AT, rect.0 as u16);
            m.write16(GS, REGION_AT + 2, rect.1 as u16);
            m.write16(GS, REGION_AT + 4, rect.2 as u16);
            m.write16(GS, REGION_AT + 6, rect.3 as u16);
            m.regs.set_bp(REGION_AT as u16);
            let sp = m.regs.sp() as u32;
            m.write16(m.regs.ss, sp, 0x0000);
            m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
            super::auto::func_8295(&mut m);
            m.regs.cf
        };

        let yes = crate::engine::EngineState::CONFIRM_YES_REGION;
        let no = crate::engine::EngineState::CONFIRM_NO_REGION;
        let e = crate::engine::EngineState::new();
        for (mx, my) in [
            (120i32, 105i32), (150, 115), (151, 105), (119, 105), (120, 116),
            (180, 105), (200, 115), (201, 105), (179, 110), (0, 0), (160, 110),
        ] {
            let lift_yes = hit(yes, mx, my);
            let lift_no = hit(no, mx, my);
            let expected = if lift_yes {
                Some(true)
            } else if lift_no {
                Some(false)
            } else {
                None
            };
            assert_eq!(
                e.confirm_box_click(mx, my),
                expected,
                "cursor ({mx},{my}): lift yes={lift_yes} no={lift_no}"
            );
        }
    }

    /// The ACTIVE-OBJECT LIST against its lift (`func_604e`).
    ///
    /// `0x604E` walks the 20-byte directory at `gs:0x672C` while each entry's
    /// `+0x12` is 1 — it STOPS at the first that is not, rather than skipping —
    /// keeps every object whose `fs:[obj+2]` has bit 1, and writes the survivors
    /// to `DS:0x6A16` with a `0xFFFF` terminator. Decoded by hand in FIX #53; this
    /// checks that reading.
    #[test]
    fn native_active_object_list_matches_the_lift() {
        // (object offset, entry kind, flags) — the fourth entry ends the scan, so
        // the fifth must not appear even though it qualifies.
        let cases: [(&str, &[(u16, u16, u16)], &[u16]); 4] = [
            (
                "stops at the kind!=1 entry",
                &[
                    (0x0100, 1, 0x0002),
                    (0x0200, 1, 0x0000),
                    (0x0300, 1, 0x0002),
                    (0x0400, 0, 0x0002),
                    (0x0500, 1, 0x0002),
                ],
                &[0x0100, 0x0300],
            ),
            // `0x6068`'s FIRST visit going straight to `0x6082` — the empty list.
            // The original sweep always entered the body, so "stops immediately"
            // and "stops after N" were the same path to it (audit-fixes #580).
            ("empty when the first entry ends the scan", &[(0x0100, 0, 0x0002)], &[]),
            // `0x6073` is `test BYTE fs:[bx+2],2` — bit 1 among any other bits
            // qualifies, and no other bit does. Every earlier row used exactly
            // 0x0002 or 0x0000, which cannot tell a bit test from an equality.
            (
                "bit 1 is tested, not the word",
                &[
                    (0x0100, 1, 0x0202),
                    (0x0200, 1, 0x0004),
                    (0x0300, 1, 0x00FF),
                    (0x0400, 1, 0x0001),
                    (0x0500, 0, 0x0002),
                ],
                &[0x0100, 0x0300],
            ),
            // Bit 1 set only in the HIGH byte: `test byte` reads `[bx+2]` alone, so
            // 0x0200 must NOT qualify even though the word has a bit-1 pattern.
            (
                "the high byte is not consulted",
                &[(0x0100, 1, 0x0200), (0x0200, 1, 0x0002), (0x0300, 0, 0)],
                &[0x0200],
            ),
        ];
        for (label, entries, want) in cases {
            run_active_object_case(label, entries, want);
        }
    }

    fn run_active_object_case(label: &str, entries: &[(u16, u16, u16)], want: &[u16]) {
        const GS: u16 = 0x2600;
        const FS: u16 = 0x2600; // records in the same arena
        const DIR_PTR: u32 = 0x672C;
        const REC_PTR: u32 = 0x6724;
        const OUT: u32 = 0x6A16;
        const DIR_AT: u32 = 0x3000;

        let mut m = Machine::new();
        m.regs.ds = GS;
        m.regs.gs = GS;
        m.regs.es = GS;
        m.regs.ss = GS;
        m.regs.set_sp(0xFF00);
        m.write16(GS, DIR_PTR, DIR_AT as u16);
        m.write16(GS, DIR_PTR + 2, GS);
        m.write16(GS, REC_PTR, 0);
        m.write16(GS, REC_PTR + 2, FS);
        for (i, &(obj, kind, flags)) in entries.iter().enumerate() {
            let base = DIR_AT + (i as u32) * 20;
            m.write16(GS, base + 0x10, obj);
            m.write16(GS, base + 0x12, kind);
            m.write16(FS, u32::from(obj) + 2, flags);
        }
        let sp = m.regs.sp() as u32;
        m.write16(m.regs.ss, sp, 0x0000);
        m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
        super::auto::func_604e(&mut m);

        let mut lifted = Vec::new();
        for i in 0..8u32 {
            let v = m.read16(GS, OUT + i * 2);
            if v == 0xFFFF {
                break;
            }
            lifted.push(v);
        }

        let mut native = crate::vm::VmMachine::new();
        native.directory = entries.iter().map(|(o, k, _)| (*o, *k)).collect();
        for &(obj, _, flags) in entries {
            native.rec_write_pub(obj + 2, flags);
        }
        assert_eq!(
            lifted,
            native.build_active_object_list(),
            "{label}: the directory walk diverged"
        );
        assert_eq!(lifted, want.to_vec(), "{label}");
    }

    /// The DRAWN-WIDTH accumulator against its lift (`func_3192`).
    ///
    /// FIX #59 established that `gs:0x27CD` counts GLYPH advances only — the space
    /// path (`add di,6 / jmp` @`0x31D7`) moves the pen without touching it, and
    /// unmapped bytes are skipped entirely. `font::game_font_drawn_width` encodes
    /// that, and the panel layout depends on it. This runs the real routine and
    /// reads the accumulator back.
    #[test]
    fn native_drawn_width_matches_the_lifted_accumulator() {
        let Some(exe) = load_exe_image() else { return };
        const GS: u16 = 0x2600;
        const STR_DS: u32 = 0x0400;
        const ACC_DS: u32 = 0x27CD;
        const FB_PTR: u32 = 0x5221;
        // NOT width/height: `cmp dx,gs:[0x523B] / ja` then `cx = gs:[0x5239]-8 /
        // cmp dx,cx / jle` both test dx, and dx is the ROW (0x31BA..0x31C1 build
        // `dx*320 + bx`). So these are the clip's TOP and BOTTOM, and seeding them
        // as 320/200 made the routine bail before drawing a single glyph — the
        // accumulator came back 0.
        const CLIP_TOP: u32 = 0x5239;
        const CLIP_BOTTOM: u32 = 0x523B;
        // The game font's three tables, from the image.
        const XLAT: u32 = 0x7802;
        const ADV: u32 = 0x78B2;
        const GLYPHS: u32 = 0x7908;

        let width_of = |text: &str| -> u16 {
            let mut m = Machine::new();
            m.regs.ds = GS;
            m.regs.gs = GS;
            m.regs.es = GS;
            m.regs.ss = GS;
            m.regs.set_sp(0xFF00);
            for (base, len) in [(XLAT, 176usize), (ADV, 86), (GLYPHS, 86 * 8)] {
                let file = 0xD420 + base as usize;
                for i in 0..len {
                    m.write8(GS, base + i as u32, exe[file + i]);
                }
            }
            // Draw somewhere harmless, with a clip that admits the whole string.
            m.write16(GS, FB_PTR, 0x8000);
            m.write16(GS, FB_PTR + 2, GS);
            m.write16(GS, CLIP_TOP, 0);
            m.write16(GS, CLIP_BOTTOM, 200);
            // CP437 BYTES, not UTF-8. `text.bytes()` would send `é` as the two
            // bytes 0xC3,0xA9 -- neither of which is the 0x82 the game's table maps
            // -- so the accented half of the 176-entry table could never be reached
            // by this sweep. The port decodes game data the same way (`cp437_byte`).
            let bytes: Vec<u8> = text.chars().filter_map(crate::font::cp437_byte).collect();
            for (i, b) in bytes.iter().enumerate() {
                m.write8(GS, STR_DS + i as u32, *b);
            }
            m.write8(GS, STR_DS + bytes.len() as u32, 0);
            m.regs.set_si(STR_DS as u16);
            m.regs.set_bx(10); // column
            m.regs.set_dx(100); // row, inside the clip
            let sp = m.regs.sp() as u32;
            m.write16(m.regs.ss, sp, 0x0000);
            m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
            super::auto::func_3192(&mut m);
            m.read16(GS, ACC_DS)
        };

        for text in [
            "PLANET: ", "SHIP: ", "BLACK HOLE: ", "LIFE SUPPORT:", "Oddland",
            "ARE_YOU_SURE?", "YES", "NO", "LOADING", "PAUSE", "a b", "  ",
            // The `js 0x31CE` SKIP path (audit-fixes #578). 89 of the 176 xlat
            // entries are 0xff, and the printable ones are `#$%&()*/<=>@[\]^`{|}~`.
            // Every string above is drawable ASCII, so the skip was never taken and
            // the sweep could not tell "contributes 0" from "contributes a width".
            "A#B", "(x)", "100%", "a/b", "<@>", "[]{}",
            // Entries PAST 128, reachable only now that the string is CP437-encoded.
            "café", "réacteur", "Ärger", "à côté",
            // Skipped char adjacent to a space -- the two zero-width paths in one
            // string, which take different branches out of the same loop head.
            "a # b", "( )",
        ] {
            let lifted = width_of(text);
            let native = crate::font::game_font_drawn_width(text) as u16;
            assert_eq!(lifted, native, "{text:?}: lift {lifted} vs native {native}");
            // NOT VACUOUS: every char must survive the CP437 encode, or a dropped
            // one would make both sides agree on a string neither actually saw.
            assert_eq!(
                text.chars().filter_map(crate::font::cp437_byte).count(),
                text.chars().count(),
                "{text:?}: a char did not encode to CP437, so this row tests nothing"
            );
        }
    }

    /// The NAV-CHART PICKER against its lift (`func_92a3`).
    ///
    /// This one checks a decode made THIS session by hand: `nav_chart_pick` was
    /// written by reading `0x92A3` off the disassembly, so running it against the
    /// lifted original is an independent check of that reading — per-kind hit
    /// boxes, the `(x-2, y-2)` origin, inclusive bounds, first hit wins, and the
    /// black hole's second endpoint when `obj+0x14` differs from `arche+0x22`.
    #[test]
    fn native_nav_chart_pick_matches_the_lift() {
        const GS: u16 = 0x2600;
        const LIST_DS: u32 = 0x2AD3;
        const COUNT_DS: u32 = 0x27C1;
        const MOUSE_X: u32 = 0x0A2A;
        const MOUSE_Y: u32 = 0x0A2C;
        const ARCHE_PTR: u32 = 0x6752;
        const RECORDS: u32 = 0x6724; // far pointer to the record table
        const ARCHE: u16 = 0x0040;
        const PLANET: u16 = 0x0100;
        const SHIP: u16 = 0x0200;
        const HOLE: u16 = 0x0300;
        // BOTH bits set -- the case that tells the two implementations apart. At the
        // arche, `0x92FC` overwrites the black-hole box with the SHIP box; away from
        // it, `0x92EF` skips the ship test and the black-hole box stands. A kind
        // ladder answers "black hole" for both (audit-fixes #575).
        const BOTH_AT: u16 = 0x0400;
        const BOTH_AWAY: u16 = 0x0500;
        const CONTEXT: u16 = 7;

        // Build the record table once, in a segment the far pointer names.
        let mut native = crate::vm::VmMachine::new();
        for (obj, kind, x, y) in [
            (PLANET, 0u16, 50u16, 60u16),
            (SHIP, crate::vm::LOCATION_KIND_SHIP, 100, 60),
            (HOLE, crate::vm::LOCATION_KIND_BLACK_HOLE, 150, 60),
            (
                BOTH_AT,
                crate::vm::LOCATION_KIND_BLACK_HOLE | crate::vm::LOCATION_KIND_SHIP,
                50,
                120,
            ),
            (
                BOTH_AWAY,
                crate::vm::LOCATION_KIND_BLACK_HOLE | crate::vm::LOCATION_KIND_SHIP,
                100,
                120,
            ),
        ] {
            native.rec_write_pub(obj, kind);
            native.rec_write_pub(obj + crate::vm::NAV_PICK_POSITION_FIELD, x);
            native.rec_write_pub(obj + crate::vm::NAV_PICK_POSITION_FIELD + 2, y);
        }
        native.rec_write_pub(HOLE + 0x14, CONTEXT);
        native.rec_write_pub(HOLE + crate::vm::NAV_PICK_POSITION_FIELD + 4, 250);
        native.rec_write_pub(HOLE + crate::vm::NAV_PICK_POSITION_FIELD + 6, 90);
        // BOTH_AT sits at the arche (`+0x14` == context) -> near marker, ship box.
        native.rec_write_pub(BOTH_AT + 0x14, CONTEXT);
        // BOTH_AWAY does not -> far marker (200,150) and the black-hole box kept.
        native.rec_write_pub(BOTH_AWAY + 0x14, CONTEXT + 1);
        native.rec_write_pub(BOTH_AWAY + crate::vm::NAV_PICK_POSITION_FIELD + 4, 200);
        native.rec_write_pub(BOTH_AWAY + crate::vm::NAV_PICK_POSITION_FIELD + 6, 150);
        let list = [PLANET, SHIP, HOLE, BOTH_AT, BOTH_AWAY];

        let probes = [
            (48i32, 58i32), (60, 66), (61, 58), (98, 58), (120, 58), (98, 70),
            (148, 58), (163, 64), (164, 58), (5, 5), (250, 90), (52, 62),
            // BOTH_AT, marker (50,120): ship box is 21x10 from (48,118), the
            // black-hole box 19x12. x=69 is inside the ship box only; y=130 is
            // inside the black-hole box only. One probe per disagreeing edge.
            (69, 120), (50, 130), (48, 118), (70, 120),
            // BOTH_AWAY, FAR marker (200,150) with the black-hole box: x=217 hits,
            // x=219 (which the ship box would reach) must not, and y=160 hits.
            (217, 150), (219, 150), (200, 160), (200, 120),
        ];
        for (mx, my) in probes {
            let mut m = Machine::new();
            m.regs.ds = GS;
            m.regs.gs = GS;
            m.regs.es = GS;
            m.regs.ss = GS;
            m.regs.set_sp(0xFF00);
            // records: a far pointer at gs:0x6724 -> the same segment, offset 0
            m.write16(GS, RECORDS, 0);
            m.write16(GS, RECORDS + 2, GS);
            for (i, obj) in list.iter().enumerate() {
                m.write16(GS, LIST_DS + (i as u32) * 2, *obj);
            }
            m.write16(GS, LIST_DS + (list.len() as u32) * 2, 0xFFFF);
            m.write16(GS, COUNT_DS, list.len() as u16);
            m.write16(GS, MOUSE_X, mx as u16);
            m.write16(GS, MOUSE_Y, my as u16);
            m.write16(GS, ARCHE_PTR, ARCHE);
            m.write16(GS, u32::from(ARCHE) + 0x22, CONTEXT);
            for obj in list {
                for off in (0..0x24u32).step_by(2) {
                    m.write16(GS, u32::from(obj) + off, native.rec_read_pub(obj + off as u16));
                }
            }
            let sp = m.regs.sp() as u32;
            m.write16(m.regs.ss, sp, 0x0000);
            m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
            super::auto::func_92a3(&mut m);
            let lifted = m.regs.ax();
            let ours = native.nav_chart_pick(&list, (mx, my), CONTEXT).unwrap_or(0);
            assert_eq!(
                lifted, ours,
                "mouse ({mx},{my}): lift {lifted:#06x} vs native {ours:#06x}"
            );
        }
    }

    /// The DEPTH SCROLL against its lift (`func_b75c`), swept.
    ///
    /// `0xB75C` moves `[0x2527]` toward its limit by `[0x2531]`, gated on the
    /// opening flag `[0x252F]` and the closing flag `[0x2530]`, clamping at `0x41`
    /// and 0 and clearing the flag on arrival. `add al,[0x2531]` is a LOW-BYTE add
    /// on a word, which is why the port has `add_to_low_byte` rather than a plain
    /// addition — the sweep covers the values where that matters.
    #[test]
    fn native_depth_scroll_matches_the_lift() {
        const GS: u16 = 0x2600;
        const DEPTH: u32 = 0x2527;
        const OPENING: u32 = 0x252F;
        const CLOSING: u32 = 0x2530;
        const STEP: u32 = 0x2531;

        let mut cases = 0usize;
        for depth in [0u16, 1, 0x20, 0x40, 0x41, 0x42, 0x100, 0x1FF] {
            for step in [1u8, 4, 8, 0x40, 0xFF] {
                for (opening, closing) in [(true, false), (false, true), (false, false)] {
                    let mut m = Machine::new();
                    m.regs.ds = GS;
                    m.regs.gs = GS;
                    m.regs.ss = GS;
                    m.regs.set_sp(0xFF00);
                    m.write16(GS, DEPTH, depth);
                    m.write8(GS, OPENING, opening as u8);
                    m.write8(GS, CLOSING, closing as u8);
                    m.write8(GS, STEP, step);
                    let sp = m.regs.sp() as u32;
                    m.write16(m.regs.ss, sp, 0x0000);
                    m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
                    super::auto::func_b75c(&mut m);

                    let mut native = crate::ship3d::Ship3dDepthState {
                        depth_offset: depth,
                        depth_step: step,
                        opening,
                        closing,
                        ..Default::default()
                    };
                    crate::ship3d::step_ship_3d_depth_scroll(&mut native);

                    assert_eq!(
                        (
                            m.read16(GS, DEPTH),
                            m.read8(GS, OPENING) & 1 != 0,
                            m.read8(GS, CLOSING) & 1 != 0
                        ),
                        (native.depth_offset, native.opening, native.closing),
                        "depth {depth:#x} step {step:#x} opening {opening} closing {closing}"
                    );
                    cases += 1;
                }
            }
        }
        assert_eq!(cases, 8 * 5 * 3);
    }

    /// The SAVE-NAME EDIT LAW against its lift (`func_1dd8`).
    ///
    /// `0x1DD8` reads the key from `[0xB15]` and the current length from
    /// `[0x272E]`, editing the 16-byte buffer at `DS:0x273B`:
    ///
    /// ```text
    ///   0x1DED  cmp al,0x0D            ENTER: commit unless the length is 0
    ///   0x1E02  cmp al,0x30 / 0x39     digits...
    ///   0x1E0A  cmp al,0x61 / 0x7A     ...and lowercase only
    ///   0x1E12  cmp bl,0x0E / je       fourteen characters, then no more
    ///   0x1E1B  cmp al,8               BACKSPACE: `dec bx` then write a SPACE
    /// ```
    ///
    /// The port keeps a `String` and `pop()`s; the original keeps a fixed buffer
    /// and writes `0x20` over the deleted character. Both give the same NAME —
    /// the directory records are space-padded, which is why the shipped
    /// `blood.sav` reads `"ab             \0"` — but the buffer contents differ,
    /// so this compares what the game would COMMIT: the buffer trimmed.
    #[test]
    fn native_save_ui_edit_matches_the_lifted_law() {
        const GS: u16 = 0x2600;
        const BUF_DS: u32 = 0x273B;
        const KEY_DS: u32 = 0x0B15;
        const LEN_DS: u32 = 0x272E;

        // Drive the lift key by key, keeping its buffer and length in memory.
        let mut m = Machine::new();
        m.regs.ds = GS;
        m.regs.gs = GS;
        m.regs.es = GS;
        m.regs.ss = GS;
        m.regs.set_sp(0xFF00);
        for i in 0..16u32 {
            m.write8(GS, BUF_DS + i, b' ');
        }
        m.write16(GS, LEN_DS, 0);
        m.write16(GS, 0x2734, 0x2900); // a slot record to commit into

        let mut e = crate::engine::EngineState::new();
        e.save_ui_active = true;

        // `0x1E1B` (reject) has THREE predecessors and the original sweep reached
        // one: `Q` fails `cmp al,0x61 / jb` at `0x1E0C`. `!` fails `cmp al,0x30 /
        // jb` at `0x1E04` and `~` fails `cmp al,0x7a / ja` at `0x1E10` — two
        // rejects that had never run (audit-fixes #579). Then fifteen `z` for the
        // `cmp bl,0x0E` cap at `0x1E12`, and backspaces past empty for the
        // `or bx,bx / je` guard at `0x1E1F`.
        let keys: Vec<u8> = b"ab9zQ\x08cd".iter().copied()
            .chain([8u8, b'x'])
            .chain(b"!~:@[`".iter().copied())
            .chain(std::iter::repeat(b'z').take(15))
            .chain(std::iter::repeat(8u8).take(20))
            .collect();
        for key in keys {
            m.write8(GS, KEY_DS, key);
            let sp = m.regs.sp() as u32;
            m.write16(m.regs.ss, sp, 0x0000);
            m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
            super::auto::func_1dd8(&mut m);
            e.save_ui_key(key);
            // `0x1DD8` does NOT advance `[0x272E]` — the ONLY writers in the whole
            // image are `mov word [0x272E],0` at `0x1BF3` and the `inc` at
            // `0x1C05` inside a scan that counts buffer characters up to a NUL or
            // a SPACE. So the length is re-derived by the surrounding flow, not by
            // the edit routine, and a harness that calls the edit alone would keep
            // overwriting position 0 — which is exactly what the first run showed.
            let mut len = 0u16;
            for i in 0..16u32 {
                let b = m.read8(GS, BUF_DS + i);
                if b == 0 || b == b' ' {
                    break;
                }
                len += 1;
            }
            m.write16(GS, LEN_DS, len);

            let lifted: String = (0..14u32)
                .map(|i| m.read8(GS, BUF_DS + i) as char)
                .collect::<String>()
                .trim_end()
                .to_string();
            assert_eq!(
                lifted, e.save_ui_name,
                "after key {key:#04x}: lift {lifted:?} vs native {:?}",
                e.save_ui_name
            );
        }
        assert_eq!(e.save_ui_name, "", "20 backspaces must empty the name");

        // ENTER ON AN EMPTY NAME: `0x1DF1 or bx,bx / je 0x1E27` skips the copy, so
        // no commit and CF stays clear (`0x1E54 clc`). Never exercised before.
        m.write8(GS, KEY_DS, 13);
        let sp = m.regs.sp() as u32;
        m.write16(m.regs.ss, sp, 0x0000);
        m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
        super::auto::func_1dd8(&mut m);
        assert!(!m.regs.cf, "empty name must not commit (0x1DF1)");
        assert_eq!(e.save_ui_key(13), None, "port must not commit an empty name");
        assert!(e.save_ui_active, "and the editor stays open");

        // ENTER ON A REAL NAME: `0x1DF5..0x1DFF` copies FOUR DWORDS (16 bytes) from
        // the buffer to `[0x2734]` and sets CF. The commit itself had no coverage.
        for key in *b"hero7" {
            m.write8(GS, KEY_DS, key);
            let sp = m.regs.sp() as u32;
            m.write16(m.regs.ss, sp, 0x0000);
            m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
            super::auto::func_1dd8(&mut m);
            let mut len = 0u16;
            for i in 0..16u32 {
                let b = m.read8(GS, BUF_DS + i);
                if b == 0 || b == b' ' {
                    break;
                }
                len += 1;
            }
            m.write16(GS, LEN_DS, len);
            e.save_ui_key(key);
        }
        m.write8(GS, KEY_DS, 13);
        let sp = m.regs.sp() as u32;
        m.write16(m.regs.ss, sp, 0x0000);
        m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
        super::auto::func_1dd8(&mut m);
        assert!(m.regs.cf, "a non-empty name commits (0x1DFF stc)");
        let committed: String = (0..16u32)
            .map(|i| m.read8(GS, 0x2900 + i) as char)
            .collect::<String>()
            .trim_end()
            .to_string();
        assert_eq!(committed, "hero7", "the rep movsd lands the name in the slot");
        assert_eq!(e.save_ui_key(13), Some("hero7".to_string()));
        assert!(!e.save_ui_active, "committing closes the editor");
        // SIXTEEN bytes, not fourteen: `cx=4 / rep movsd`. The two bytes past the
        // 14-character cap are copied too, which is why the shipped directory
        // records are space-padded to a fixed stride.
        assert_eq!(m.read8(GS, 0x2900 + 15), b' ');
    }

    /// The ENTITY STATE-ADVANCE against its lift (`func_41d1`).
    ///
    /// `0x41D1` reads the flags word of entity `AX` at `gs:[0x6212 + id<<5]`, and
    /// when bit7 (ACTIVE) and bit0 (STATE0) are both set clears bit0 and sets
    /// bit1 — then stores the word back UNCONDITIONALLY, even on the paths that
    /// changed nothing. Swept over every 8-bit flag value.
    #[test]
    fn native_entity_advance_state_matches_the_lift() {
        const GS: u16 = 0x2600;
        const TABLE_DS: u32 = 0x6212;
        const ID: u16 = 3;
        let addr = TABLE_DS + u32::from(ID) * 32;

        for flags in 0u16..=0xFF {
            let mut m = Machine::new();
            m.regs.ds = GS;
            m.regs.gs = GS;
            m.regs.ss = GS;
            m.regs.set_sp(0xFF00);
            m.write16(GS, addr, flags);
            m.regs.set_ax(ID);
            let sp = m.regs.sp() as u32;
            m.write16(m.regs.ss, sp, 0x0000);
            m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
            super::auto::func_41d1(&mut m);
            let lifted = m.read16(GS, addr);

            // NOT `populate(flags, ..)` — that applies the ACTIVATION formula
            // (`([si]&4)|0x83` at 0x40D0) rather than storing the word, so a raw
            // 0x0000 came back as 0x0082. Set the flags directly.
            let mut e = crate::entity::EntityObject::populate(0, (0, 0), 0, (0, 0));
            e.flags = flags;
            e.advance_state();
            assert_eq!(
                lifted, e.flags,
                "flags {flags:#06x}: lift {lifted:#06x} vs native {:#06x}",
                e.flags
            );
        }
    }

    /// The TEXT MEASURE routine against its lift (`func_30cd`).
    ///
    /// `0x30CD` picks a face from `AX` — 0 selects the square-caps xlat/widths at
    /// `DS:0x7362`/`0x7412`, anything else the game font at `0x7802`/`0x78B2` —
    /// then accumulates each glyph's width (`xlatb` / `add dl,gs:[eax+edi]` /
    /// `adc dh,0`) and subtracts 2 for the trailing gap. `font::square_caps_text_width`
    /// is the native twin, and every menu's centring depends on it.
    #[test]
    fn native_square_caps_width_matches_the_lifted_measure() {
        let Some(exe) = load_exe_image() else { return };
        const GS: u16 = 0x2600;
        const STR_DS: u32 = 0x0400; // scratch, clear of the font tables
        // The two square-caps tables, from the image (DS base 0xD420).
        const XLAT_DS: u32 = 0x7362;
        const WIDTHS_DS: u32 = 0x7412;

        let measure = |text: &str| -> u16 {
            let mut m = Machine::new();
            m.regs.ds = GS;
            m.regs.gs = GS;
            m.regs.ss = GS; // `[bp]`/string ops: keep every segment on the arena
            m.regs.set_sp(0xFF00);
            for (i, b) in exe[0xD420 + XLAT_DS as usize..0xD420 + XLAT_DS as usize + 176]
                .iter()
                .enumerate()
            {
                m.write8(GS, XLAT_DS + i as u32, *b);
            }
            for (i, b) in exe[0xD420 + WIDTHS_DS as usize..0xD420 + WIDTHS_DS as usize + 48]
                .iter()
                .enumerate()
            {
                m.write8(GS, WIDTHS_DS + i as u32, *b);
            }
            for (i, b) in text.bytes().enumerate() {
                m.write8(GS, STR_DS + i as u32, b);
            }
            m.write8(GS, STR_DS + text.len() as u32, 0);
            m.regs.set_ax(0); // the square-caps face
            m.regs.set_si(STR_DS as u16);
            let sp = m.regs.sp() as u32;
            m.write16(m.regs.ss, sp, 0x0000);
            m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
            super::auto::func_30cd(&mut m);
            m.regs.ax()
        };

        // Real labels: the words the menus actually measure.
        for text in [
            "TALK", "CANCEL", "BOB_MORLOCK", "EGO", "LIBIDO", "REMEMBER", "BYE_BYE",
            "ONE", "PLANET", "W", "I", "AB",
        ] {
            let lifted = measure(text);
            let native = crate::font::square_caps_text_width(text) as u16;
            assert_eq!(
                lifted, native,
                "{text:?}: lift {lifted} vs native {native}"
            );
        }

        // THE EMPTY STRING diverges, and the divergence is deliberate. `0x30FE`
        // is `sub ax,2` on a zero accumulator, which WRAPS to 0xFFFE — and the
        // widget's max-width compare at `0x8472` is `jb`, UNSIGNED, so 0xFFFE
        // would win and produce a 65534-wide box. The game never measures an
        // empty label: unused save slots hold FIFTEEN SPACES, not "", and a space
        // maps to glyph 47 with a real width.
        assert_eq!(measure(""), 0xFFFE, "the original wraps");
        assert_eq!(
            crate::font::square_caps_text_width("") as u16,
            0,
            "the port saturates instead — safe only because nothing passes it \"\""
        );
        // A blank slot as the DIRECTORY holds it measures like any other string.
        assert_eq!(
            measure("               "),
            crate::font::square_caps_text_width("               ") as u16,
            "fifteen spaces: the real blank-slot label"
        );
    }

    /// The SPECIAL-SLOT pair against their lifts (`func_5ff6` / `func_5fd8`).
    ///
    /// Sixteen words at `DS:0x6D3E`. The sweep drives both implementations through
    /// the same script — insert into an empty list, insert a duplicate, fill it,
    /// overflow it, remove a present value, remove an absent one — and compares
    /// the LIST CONTENTS and the boolean/CF after every step.
    #[test]
    fn native_special_slots_match_the_lifted_pair() {
        const GS: u16 = 0x2600;
        const LIST_DS: u32 = 0x6D3E;
        const SLOTS: usize = 16;

        // A machine whose list mirrors `native`, so both see the same state.
        let run = |list: &mut [u16; SLOTS], value: u16, insert: bool| -> bool {
            let mut m = Machine::new();
            m.regs.ds = GS;
            m.regs.gs = GS;
            // `mov bp,0x6D3E / cmp ax,[bp]` — a `[bp]` operand defaults to SS, not
            // DS. With a separate stack segment the lift reads a different list
            // entirely and silently does nothing, which is exactly what the first
            // run of this test showed.
            m.regs.ss = GS;
            m.regs.set_sp(0xFFF0);
            let base = (GS as u32) * 16 + LIST_DS;
            for (i, v) in list.iter().enumerate() {
                m.write16(GS, LIST_DS + (i as u32) * 2, *v);
            }
            m.regs.set_ax(value);
            let sp = m.regs.sp() as u32;
            m.write16(m.regs.ss, sp, 0x0000);
            m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
            if insert {
                super::auto::func_5ff6(&mut m);
            } else {
                super::auto::func_5fd8(&mut m);
            }
            for (i, v) in list.iter_mut().enumerate() {
                *v = m.read16(GS, LIST_DS + (i as u32) * 2);
            }
            let _ = base;
            m.regs.cf
        };

        let mut lifted = [0u16; SLOTS];
        let mut native = crate::vm::VmMachine::new();
        let script: Vec<(u16, bool)> = vec![
            (0x100, true),  // insert into an empty list
            (0x200, true),
            (0x100, true),  // duplicate: already present
            (0x100, false), // remove a present value
            (0x100, false), // remove it again: absent
            (0x300, true),
        ];
        for (value, insert) in script {
            let lift_cf = run(&mut lifted, value, insert);
            let native_flag = if insert {
                native.special_slot_insert_pub(value)
            } else {
                native.special_slot_remove_pub(value)
            };
            assert_eq!(
                lift_cf, native_flag,
                "value {value:#x} insert={insert}: CF {lift_cf} vs native {native_flag}"
            );
            assert_eq!(
                lifted.to_vec(),
                native.ship_slots_pub().to_vec(),
                "value {value:#x} insert={insert}: list contents diverged"
            );
        }

        // Fill the list, then overflow it — the case that separates `stc` from `clc`.
        let mut lifted = [0u16; SLOTS];
        let mut native = crate::vm::VmMachine::new();
        for i in 0..SLOTS as u16 {
            let v = 0x1000 + i * 2;
            assert!(run(&mut lifted, v, true));
            assert!(native.special_slot_insert_pub(v));
        }
        assert!(!run(&mut lifted, 0xBEEF, true), "a full list must clear CF");
        assert!(!native.special_slot_insert_pub(0xBEEF), "and so must the port");
        assert_eq!(lifted.to_vec(), native.ship_slots_pub().to_vec());
    }

    /// The FIELD-OFFSET RESOLVER has a native twin too, and it is the one every
    /// selector lookup in the VM goes through.
    ///
    /// `func_6023` is the lift, oracle-verified; `vm::vm_field_offset` is a
    /// hand-written reimplementation of the same three instructions (`shl ax,4`,
    /// `bsf bx,bx`, `mov al,gs:[bx+0x6D60]`). Sweep the whole real domain — every
    /// selector row of the matrix against every single-bit kind — and require they
    /// agree. A divergence here would mis-resolve a record field, which is the
    /// quietest possible way for the port to go wrong.
    #[test]
    fn native_field_offset_matches_the_lifted_resolver() {
        let Some(exe) = load_exe_image() else { return };
        const GS: u16 = 0x2600;
        const MATRIX_DS: u32 = 0x6D60;
        const MATRIX_FILE: usize = 0x14180;
        let rows = crate::vm::FIELD_OFFSETS.len();

        let mut checked = 0usize;
        for selector in 0..rows as u8 {
            for bit in 0..16u32 {
                let kind: u16 = 1 << bit;
                let mut m = Machine::new();
                m.regs.ds = GS;
                m.regs.gs = GS;
                m.regs.ss = 0x9000;
                m.regs.set_sp(0xFFF0);
                // The matrix as the game holds it, straight from the image.
                let base = (GS as u32) * 16 + MATRIX_DS;
                for i in 0..rows * 16 {
                    m.mem[(base + i as u32) as usize] = exe[MATRIX_FILE + i];
                }
                m.regs.set_ax(u16::from(selector));
                m.regs.set_bx(kind);
                let sp = m.regs.sp() as u32;
                m.write16(m.regs.ss, sp, 0x0000);
                m.write16(m.regs.ss, sp.wrapping_add(2), 0x0020);
                super::auto::func_6023(&mut m);
                let lifted = m.regs.eax as u16;
                let native = crate::vm::vm_field_offset(selector, kind).unwrap_or(0);
                assert_eq!(
                    lifted, native,
                    "selector {selector:#x} kind {kind:#x}: lift {lifted:#x} vs native {native:#x}"
                );
                checked += 1;
            }
        }
        assert_eq!(checked, rows * 16, "the whole matrix domain was swept");
        // And the port's baked matrix must BE the image's bytes.
        assert_eq!(
            crate::vm::FIELD_OFFSETS.as_flattened(),
            &exe[MATRIX_FILE..MATRIX_FILE + rows * 16]
        );
    }

    /// The PORT'S NATIVE PRNG must agree with the oracle too.
    ///
    /// `prng_2de2_matches_oracle_vectors` checks the LIFTED function; `ship3d`'s
    /// `BloodPrng` is a separate hand-written reimplementation the engine actually
    /// calls, and nothing tied it to the real generator. Same vectors, same
    /// assertions — if the two ever diverge, the starfield and every other
    /// randomised surface drift from the game.
    #[test]
    fn native_bloodprng_matches_the_same_oracle_vectors() {
        let raw = match std::fs::read_to_string("re/tools/oracle_vectors/prng_2de2.json")
            .or_else(|_| std::fs::read_to_string("../re/tools/oracle_vectors/prng_2de2.json"))
        {
            Ok(s) => s,
            Err(_) => panic!("oracle vectors missing: this test verifies NOTHING without them"),
        };
        let vecs: Vec<PrngVec> = serde_json::from_str(&raw).unwrap();
        assert!(!vecs.is_empty());
        for (i, v) in vecs.iter().enumerate() {
            let mut prng = crate::ship3d::BloodPrng {
                seed_word: v.seed,
                a: v.a,
                b: v.b,
                counter: v.counter,
            };
            let out = prng.next(v.ax_in);
            assert_eq!(out, v.ax_out, "vec {i}: result");
            assert_eq!(prng.a, v.a_out, "vec {i}: a");
            assert_eq!(prng.b, v.b_out, "vec {i}: b");
            assert_eq!(prng.counter, v.counter_out, "vec {i}: counter");
            assert_eq!(prng.seed_word, v.seed, "vec {i}: the seed must not change");
        }
    }
}
