//! AUTO-GENERATED by re/tools/emit_one.py — do NOT edit.
//! Pointer-chasing / data-reading pure-CPU leaves the Unicorn fuzz + deterministic oracles
//! can't feed (their reads depend on realistic data structures). Each is lift.py's verified
//! CFG lift; correctness is checked bit-exact against the ORIGINAL bytes run through the
//! interpreter, with realistic seeded data, in `super::ptr_leaves`'s tests.
use super::machine::Machine;

pub fn func_22e0(m: &mut Machine) {
    let mut __blk: u32 = 0x22e0;
    let mut __guard: u32 = 0;
    loop {
        __guard += 1;
        if __guard > 5_000_000 { panic!("func_22e0: iteration guard tripped (non-terminating input)"); }
        match __blk {
            0x22e0 => {
                // 0x022e0: push bp
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.bp()) as u16);
                // 0x022e1: push ax
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.ax()) as u16);
                // 0x022e2: push bx
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.bx()) as u16);
                // 0x022e3: push cx
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.cx()) as u16);
                // 0x022e4: push dx
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.dx()) as u16);
                // 0x022e5: push es
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.es) as u16);
                // 0x022e6: push di
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.di()) as u16);
                // 0x022e7: push ds
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.ds) as u16);
                // 0x022e8: push si
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.si()) as u16);
                // 0x022e9: mov bp, gs
                m.regs.set_bp((m.regs.gs) as u16);
                // 0x022eb: mov ds, bp
                m.regs.ds = (m.regs.bp()) as u16;
                // 0x022ed: mov es, bp
                m.regs.es = (m.regs.bp()) as u16;
                // 0x022ef: mov si, dx
                m.regs.set_si((m.regs.dx()) as u16);
                // 0x022f1: neg ax
                let __r = m.regs.neg16((m.regs.ax()) as u16);
                m.regs.set_ax(__r);
                // 0x022f3: mov bp, ax
                m.regs.set_bp((m.regs.ax()) as u16);
                // 0x022f5: mul bx
                m.regs.mul16((m.regs.bx()) as u16);
                // 0x022f7: mov bx, 0x64
                m.regs.set_bx((0x64) as u16);
                // 0x022fa: div bx
                m.regs.div16((m.regs.bx()) as u16);
                // 0x022fc: push ax
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.ax()) as u16);
                // 0x022fd: mov ax, bp
                m.regs.set_ax((m.regs.bp()) as u16);
                // 0x022ff: mul cx
                m.regs.mul16((m.regs.cx()) as u16);
                // 0x02301: div bx
                m.regs.div16((m.regs.bx()) as u16);
                // 0x02303: push ax
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.ax()) as u16);
                // 0x02304: mov ax, bp
                m.regs.set_ax((m.regs.bp()) as u16);
                // 0x02306: mov dx, si
                m.regs.set_dx((m.regs.si()) as u16);
                // 0x02308: mul dx
                m.regs.mul16((m.regs.dx()) as u16);
                // 0x0230a: div bx
                m.regs.div16((m.regs.bx()) as u16);
                // 0x0230c: push ax
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.ax()) as u16);
                // 0x0230d: mov ax, bp
                m.regs.set_ax((m.regs.bp()) as u16);
                // 0x0230f: sub ax, 0x64
                let __r = m.regs.sub16((m.regs.ax()) as u16, (0x64) as u16);
                m.regs.set_ax(__r);
                // 0x02312: neg ax
                let __r = m.regs.neg16((m.regs.ax()) as u16);
                m.regs.set_ax(__r);
                // 0x02314: push ax
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.ax()) as u16);
                // 0x02315: mov si, 0x5251
                m.regs.set_si((0x5251) as u16);
                // 0x02318: sub sp, 0x10
                let __r = m.regs.sub16((m.regs.sp()) as u16, (0x10) as u16);
                m.regs.set_sp(__r);
                // 0x0231b: mov bp, sp
                m.regs.set_bp((m.regs.sp()) as u16);
                // 0x0231d: xor cx, cx
                let __r = m.regs.xor16((m.regs.cx()) as u16, (m.regs.cx()) as u16);
                m.regs.set_cx(__r);
                __blk = 0x231f;
            }
            0x231f => {
                // 0x0231f: mov bx, 0x64
                m.regs.set_bx((0x64) as u16);
                // 0x02322: lodsb al, byte ptr [si]
                let __v = m.read8(m.regs.ds, m.regs.si() as u32);
                m.regs.set_al(__v);
                m.regs.set_si(m.regs.si().wrapping_add((if m.regs.df { (1 as u16).wrapping_neg() } else { (1 as u16) })));
                // 0x02323: cwde 
                let __s = m.regs.al() as i8 as i16 as u16; m.regs.set_ax(__s);
                // 0x02324: mul word ptr [bp + 0x10]
                m.regs.mul16((m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x10u16)) as u32))) as u16);
                // 0x02327: div bx
                m.regs.div16((m.regs.bx()) as u16);
                // 0x02329: add ax, word ptr [bp + 0x16]
                let __r = m.regs.add16((m.regs.ax()) as u16, (m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x16u16)) as u32))) as u16);
                m.regs.set_ax(__r);
                // 0x0232c: mov word ptr [bp + 0xe], ax
                m.write16(m.regs.ss, ((m.regs.bp().wrapping_add(0xeu16)) as u32), (m.regs.ax()) as u16);
                // 0x0232f: lodsb al, byte ptr [si]
                let __v = m.read8(m.regs.ds, m.regs.si() as u32);
                m.regs.set_al(__v);
                m.regs.set_si(m.regs.si().wrapping_add((if m.regs.df { (1 as u16).wrapping_neg() } else { (1 as u16) })));
                // 0x02330: cwde 
                let __s = m.regs.al() as i8 as i16 as u16; m.regs.set_ax(__s);
                // 0x02331: mul word ptr [bp + 0x10]
                m.regs.mul16((m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x10u16)) as u32))) as u16);
                // 0x02334: div bx
                m.regs.div16((m.regs.bx()) as u16);
                // 0x02336: add ax, word ptr [bp + 0x14]
                let __r = m.regs.add16((m.regs.ax()) as u16, (m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x14u16)) as u32))) as u16);
                m.regs.set_ax(__r);
                // 0x02339: mov word ptr [bp + 0xc], ax
                m.write16(m.regs.ss, ((m.regs.bp().wrapping_add(0xcu16)) as u32), (m.regs.ax()) as u16);
                // 0x0233c: lodsb al, byte ptr [si]
                let __v = m.read8(m.regs.ds, m.regs.si() as u32);
                m.regs.set_al(__v);
                m.regs.set_si(m.regs.si().wrapping_add((if m.regs.df { (1 as u16).wrapping_neg() } else { (1 as u16) })));
                // 0x0233d: cwde 
                let __s = m.regs.al() as i8 as i16 as u16; m.regs.set_ax(__s);
                // 0x0233e: mul word ptr [bp + 0x10]
                m.regs.mul16((m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x10u16)) as u32))) as u16);
                // 0x02341: div bx
                m.regs.div16((m.regs.bx()) as u16);
                // 0x02343: add ax, word ptr [bp + 0x12]
                let __r = m.regs.add16((m.regs.ax()) as u16, (m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x12u16)) as u32))) as u16);
                m.regs.set_ax(__r);
                // 0x02346: mov word ptr [bp + 0xa], ax
                m.write16(m.regs.ss, ((m.regs.bp().wrapping_add(0xau16)) as u32), (m.regs.ax()) as u16);
                // 0x02349: push si
                m.regs.set_sp(m.regs.sp().wrapping_sub(2));
                m.write16(m.regs.ss, m.regs.sp() as u32, (m.regs.si()) as u16);
                // 0x0234a: mov word ptr [bp + 8], 0xffff
                m.write16(m.regs.ss, ((m.regs.bp().wrapping_add(0x8u16)) as u32), (0xffff) as u16);
                // 0x0234f: mov word ptr [bp + 6], 0xbb8
                m.write16(m.regs.ss, ((m.regs.bp().wrapping_add(0x6u16)) as u32), (0xbb8) as u16);
                // 0x02354: mov si, 0x5251
                m.regs.set_si((0x5251) as u16);
                __blk = 0x2357;
            }
            0x2357 => {
                // 0x02357: lodsb al, byte ptr [si]
                let __v = m.read8(m.regs.ds, m.regs.si() as u32);
                m.regs.set_al(__v);
                m.regs.set_si(m.regs.si().wrapping_add((if m.regs.df { (1 as u16).wrapping_neg() } else { (1 as u16) })));
                // 0x02358: cwde 
                let __s = m.regs.al() as i8 as i16 as u16; m.regs.set_ax(__s);
                // 0x02359: mov word ptr [bp + 4], ax
                m.write16(m.regs.ss, ((m.regs.bp().wrapping_add(0x4u16)) as u32), (m.regs.ax()) as u16);
                // 0x0235c: lodsb al, byte ptr [si]
                let __v = m.read8(m.regs.ds, m.regs.si() as u32);
                m.regs.set_al(__v);
                m.regs.set_si(m.regs.si().wrapping_add((if m.regs.df { (1 as u16).wrapping_neg() } else { (1 as u16) })));
                // 0x0235d: cwde 
                let __s = m.regs.al() as i8 as i16 as u16; m.regs.set_ax(__s);
                // 0x0235e: mov word ptr [bp + 2], ax
                m.write16(m.regs.ss, ((m.regs.bp().wrapping_add(0x2u16)) as u32), (m.regs.ax()) as u16);
                // 0x02361: lodsb al, byte ptr [si]
                let __v = m.read8(m.regs.ds, m.regs.si() as u32);
                m.regs.set_al(__v);
                m.regs.set_si(m.regs.si().wrapping_add((if m.regs.df { (1 as u16).wrapping_neg() } else { (1 as u16) })));
                // 0x02362: cwde 
                let __s = m.regs.al() as i8 as i16 as u16; m.regs.set_ax(__s);
                // 0x02363: mov word ptr [bp], ax
                m.write16(m.regs.ss, ((m.regs.bp()) as u32), (m.regs.ax()) as u16);
                // 0x02366: mov ax, word ptr [bp + 0xe]
                m.regs.set_ax((m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0xeu16)) as u32))) as u16);
                // 0x02369: sub ax, word ptr [bp + 4]
                let __r = m.regs.sub16((m.regs.ax()) as u16, (m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x4u16)) as u32))) as u16);
                m.regs.set_ax(__r);
                // 0x0236c: jns 0x2370
                if !m.regs.sf { __blk = 0x2370; } else { __blk = 0x236e; }
            }
            0x236e => {
                // 0x0236e: neg ax
                let __r = m.regs.neg16((m.regs.ax()) as u16);
                m.regs.set_ax(__r);
                __blk = 0x2370;
            }
            0x2370 => {
                // 0x02370: mul ax
                m.regs.mul16((m.regs.ax()) as u16);
                // 0x02372: mov bx, ax
                m.regs.set_bx((m.regs.ax()) as u16);
                // 0x02374: mov ax, word ptr [bp + 0xc]
                m.regs.set_ax((m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0xcu16)) as u32))) as u16);
                // 0x02377: sub ax, word ptr [bp + 2]
                let __r = m.regs.sub16((m.regs.ax()) as u16, (m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x2u16)) as u32))) as u16);
                m.regs.set_ax(__r);
                // 0x0237a: jns 0x237e
                if !m.regs.sf { __blk = 0x237e; } else { __blk = 0x237c; }
            }
            0x237c => {
                // 0x0237c: neg ax
                let __r = m.regs.neg16((m.regs.ax()) as u16);
                m.regs.set_ax(__r);
                __blk = 0x237e;
            }
            0x237e => {
                // 0x0237e: mul ax
                m.regs.mul16((m.regs.ax()) as u16);
                // 0x02380: add bx, ax
                let __r = m.regs.add16((m.regs.bx()) as u16, (m.regs.ax()) as u16);
                m.regs.set_bx(__r);
                // 0x02382: mov ax, word ptr [bp + 0xa]
                m.regs.set_ax((m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0xau16)) as u32))) as u16);
                // 0x02385: sub ax, word ptr [bp]
                let __r = m.regs.sub16((m.regs.ax()) as u16, (m.read16(m.regs.ss, ((m.regs.bp()) as u32))) as u16);
                m.regs.set_ax(__r);
                // 0x02388: jns 0x238c
                if !m.regs.sf { __blk = 0x238c; } else { __blk = 0x238a; }
            }
            0x238a => {
                // 0x0238a: neg ax
                let __r = m.regs.neg16((m.regs.ax()) as u16);
                m.regs.set_ax(__r);
                __blk = 0x238c;
            }
            0x238c => {
                // 0x0238c: mul ax
                m.regs.mul16((m.regs.ax()) as u16);
                // 0x0238e: add bx, ax
                let __r = m.regs.add16((m.regs.bx()) as u16, (m.regs.ax()) as u16);
                m.regs.set_bx(__r);
                // 0x02390: cmp bx, word ptr [bp + 6]
                m.regs.cmp16((m.regs.bx()) as u16, (m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x6u16)) as u32))) as u16);
                // 0x02393: ja 0x239f
                if (!m.regs.cf && !m.regs.zf) { __blk = 0x239f; } else { __blk = 0x2395; }
            }
            0x2395 => {
                // 0x02395: mov word ptr [bp + 6], bx
                m.write16(m.regs.ss, ((m.regs.bp().wrapping_add(0x6u16)) as u32), (m.regs.bx()) as u16);
                // 0x02398: mov byte ptr [bp + 8], cl
                m.write8(m.regs.ss, ((m.regs.bp().wrapping_add(0x8u16)) as u32), (m.regs.cl()) as u8);
                // 0x0239b: mov byte ptr [bp + 9], 0
                m.write8(m.regs.ss, ((m.regs.bp().wrapping_add(0x9u16)) as u32), (0x0) as u8);
                __blk = 0x239f;
            }
            0x239f => {
                // 0x0239f: inc cl
                let __r = m.regs.inc8((m.regs.cl()) as u8);
                m.regs.set_cl(__r);
                // 0x023a1: je 0x23a5
                if m.regs.zf { __blk = 0x23a5; } else { __blk = 0x23a3; }
            }
            0x23a3 => {
                // 0x023a3: jmp 0x2357
                __blk = 0x2357;
            }
            0x23a5 => {
                // 0x023a5: pop si
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_si((__v) as u16);
                // 0x023a6: mov ax, word ptr [bp + 8]
                m.regs.set_ax((m.read16(m.regs.ss, ((m.regs.bp().wrapping_add(0x8u16)) as u32))) as u16);
                // 0x023a9: or ax, ax
                let __r = m.regs.or16((m.regs.ax()) as u16, (m.regs.ax()) as u16);
                m.regs.set_ax(__r);
                // 0x023ab: js 0x23b0
                if m.regs.sf { __blk = 0x23b0; } else { __blk = 0x23ad; }
            }
            0x23ad => {
                // 0x023ad: mov byte ptr es:[di], al
                m.write8(m.regs.es, ((m.regs.di()) as u32), (m.regs.al()) as u8);
                __blk = 0x23b0;
            }
            0x23b0 => {
                // 0x023b0: inc di
                let __r = m.regs.inc16((m.regs.di()) as u16);
                m.regs.set_di(__r);
                // 0x023b1: inc ch
                let __r = m.regs.inc8((m.regs.ch()) as u8);
                m.regs.set_ch(__r);
                // 0x023b3: je 0x23b8
                if m.regs.zf { __blk = 0x23b8; } else { __blk = 0x23b5; }
            }
            0x23b5 => {
                // 0x023b5: jmp 0x231f
                __blk = 0x231f;
            }
            0x23b8 => {
                // 0x023b8: add sp, 0x18
                let __r = m.regs.add16((m.regs.sp()) as u16, (0x18) as u16);
                m.regs.set_sp(__r);
                // 0x023bb: pop si
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_si((__v) as u16);
                // 0x023bc: pop ds
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.ds = (__v) as u16;
                // 0x023bd: pop di
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_di((__v) as u16);
                // 0x023be: pop es
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.es = (__v) as u16;
                // 0x023bf: pop dx
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_dx((__v) as u16);
                // 0x023c0: pop cx
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_cx((__v) as u16);
                // 0x023c1: pop bx
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_bx((__v) as u16);
                // 0x023c2: pop ax
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_ax((__v) as u16);
                // 0x023c3: pop bp
                let __v = m.read16(m.regs.ss, m.regs.sp() as u32);
                m.regs.set_sp(m.regs.sp().wrapping_add(2));
                m.regs.set_bp((__v) as u16);
                // 0x023c4: retf 
                return;
            }
            _ => unreachable!(),
        }
    }
}
