//! Hierarchical transforms and vertex projection for the MANU3 minigame.
//!
//! This is a flat-memory translation of recovered routines
//! `xdb_manu3_matrix_build` and `xdb_manu3_entity_project`. Parent transforms,
//! vertex ownership, and projection copies use typed indices and slices rather
//! than addresses from the original overlay.

use std::error::Error;
use std::fmt::{Display, Formatter};
use std::ops::Range;

/// Number of rows and columns in every MANU3 rotation matrix.
pub const MATRIX_DIMENSION: usize = 3;
/// Number of entries in the MANU3 Q14 trigonometry table.
pub const TRIGONOMETRY_TABLE_LENGTH: usize = 1_024;

const X_AXIS: usize = 0;
const Y_AXIS: usize = 1;
const Z_AXIS: usize = 2;
const ANGLE_MASK: u16 = 0x0ffc;
const ANGLE_INDEX_SHIFT: u32 = 2;
const TRANSFORM_FRACTIONAL_BITS: u32 = 15;
const POSITION_FRACTIONAL_BITS: u32 = 16;
const DEPTH_FRACTIONAL_BITS: u32 = 8;
const RADIAL_ROUNDING_BIT: u32 = 1;
const DOUBLE_SINE_SCALE: i32 = 2;
const SCREEN_ORIGIN: i32 = 0;
const PROJECTION_PLANE_DEPTH: i32 = 0;
const SCREEN_WIDTH: i32 = 320;
const SCREEN_HEIGHT: i32 = 200;
const HORIZONTAL_CLIP_LIMIT: i32 = 40;
const VERTICAL_CLIP_LIMIT: i32 = 100;
const RIGHT_CLAMP_THRESHOLD: i32 = SCREEN_WIDTH + HORIZONTAL_CLIP_LIMIT;
const BOTTOM_CLAMP_THRESHOLD: i32 = SCREEN_HEIGHT + VERTICAL_CLIP_LIMIT;
const EDGE_INSET: i32 = 1;
const LEFT_CLAMPED_POSITION: i32 = EDGE_INSET - HORIZONTAL_CLIP_LIMIT;
const RIGHT_CLAMPED_POSITION: i32 = RIGHT_CLAMP_THRESHOLD - EDGE_INSET;
const TOP_CLAMPED_POSITION: i32 = EDGE_INSET - VERTICAL_CLIP_LIMIT;
const BOTTOM_CLAMPED_POSITION: i32 = BOTTOM_CLAMP_THRESHOLD - EDGE_INSET;
const ZERO_MATRIX: Matrix3 = [[SCREEN_ORIGIN; MATRIX_DIMENSION]; MATRIX_DIMENSION];

/// Signed 3-by-3 matrix used by MANU3's fixed-point transform pipeline.
pub type Matrix3 = [[i32; MATRIX_DIMENSION]; MATRIX_DIMENSION];
/// Signed three-component vector used for positions and translations.
pub type Vector3 = [i32; MATRIX_DIMENSION];

/// One Q14 cosine/sine pair from the original MANU3 table.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct TrigonometryPair {
    /// Cosine of the indexed angle, scaled by 16,384.
    pub cosine: i16,
    /// Sine of the indexed angle, scaled by 16,384.
    pub sine: i16,
}

/// Complete trigonometry lookup table used by MANU3 transforms.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TrigonometryTable {
    entries: [TrigonometryPair; TRIGONOMETRY_TABLE_LENGTH],
}

impl TrigonometryTable {
    /// Build a lookup table from the exact ordered Q14 pairs in the game data.
    pub const fn new(entries: [TrigonometryPair; TRIGONOMETRY_TABLE_LENGTH]) -> Self {
        Self { entries }
    }

    fn lookup(&self, angle: u16) -> TrigonometryPair {
        let index = usize::from((angle & ANGLE_MASK) >> ANGLE_INDEX_SHIFT);
        self.entries[index]
    }
}

/// Fully composed transform that can parent a projection node.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Transform3 {
    /// Q15 orientation matrix.
    pub matrix: Matrix3,
    /// Translation accumulated with the original wrapping integer arithmetic.
    pub translation: Vector3,
}

/// Typed source of a node's parent transform.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TransformParent {
    /// Parent is an externally supplied root transform.
    Root(usize),
    /// Parent is an earlier node in the same hierarchy.
    Node(usize),
}

/// Transform and vertex ownership for one MANU3 model node.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProjectionNode {
    /// Root or previously built node supplying the parent transform.
    pub parent: TransformParent,
    /// Vertices transformed by this node.
    pub vertices: Range<usize>,
    /// Composed Q15 orientation generated by [`build_projection_matrices`].
    pub matrix: Matrix3,
    /// Composed translation generated by [`build_projection_matrices`].
    pub translation: Vector3,
    /// Mutable local position; radial displacement accumulates into this value.
    pub local_position: Vector3,
    /// Three native angle values, each wrapping over 4,096 units.
    pub angles: [u16; MATRIX_DIMENSION],
    /// Signed displacement along the node's locally rotated radial axis.
    pub radial_offset: i16,
}

impl ProjectionNode {
    /// Return this node's currently composed transform.
    pub const fn transform(&self) -> Transform3 {
        Transform3 {
            matrix: self.matrix,
            translation: self.translation,
        }
    }
}

/// Bit field describing which projection boundary rejected a vertex.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ClipFlags(u16);

impl ClipFlags {
    /// Vertex lies behind or on the projection plane.
    pub const BEHIND_CAMERA: Self = Self(0x8000);
    /// Vertex lies left of the visible area.
    pub const LEFT: Self = Self(0x0001);
    /// Vertex lies right of the visible area.
    pub const RIGHT: Self = Self(0x0002);
    /// Vertex lies above the visible area.
    pub const TOP: Self = Self(0x0004);
    /// Vertex lies below the visible area.
    pub const BOTTOM: Self = Self(0x0008);
    /// Vertex is inside all four screen boundaries.
    pub const NONE: Self = Self(u16::MIN);

    /// Return the packed native flag bits for oracle comparison and data output.
    pub const fn bits(self) -> u16 {
        self.0
    }

    fn insert(&mut self, flag: Self) {
        self.0 |= flag.0;
    }
}

/// Projected position and depth generated for one model vertex.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ProjectedVertex {
    /// Screen position in the original 320-by-200 coordinate system.
    pub screen: [i16; 2],
    /// Signed transformed depth after the native eight-bit scale reduction.
    pub depth: i32,
    /// Screen-boundary and behind-camera flags.
    pub clip_flags: ClipFlags,
}

/// One textured model vertex in flat memory.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ModelVertex {
    /// Texture coordinates consumed by the recovered rasterizer.
    pub texture: [i16; 2],
    /// Signed model-space coordinates.
    pub position: [i16; MATRIX_DIMENSION],
    /// Projection output, retained across frames for rejected vertices exactly
    /// as in the native routine.
    pub projected: ProjectedVertex,
}

/// Explicit source/destination pair replacing the native alias-vertex pointer.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ProjectionCopy {
    /// Vertex whose projection result is copied.
    pub source: usize,
    /// Vertex receiving the source projection result.
    pub destination: usize,
}

/// Center added to projected coordinates before clipping.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ProjectionCenter {
    /// Horizontal center.
    pub x: i32,
    /// Vertical center.
    pub y: i32,
}

/// Invalid hierarchy or geometry indices in typed MANU3 data.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum GeometryError {
    /// A node refers to a root transform that is not present.
    RootOutOfRange {
        /// Node containing the invalid reference.
        node: usize,
        /// Requested root index.
        root: usize,
        /// Number of available roots.
        root_count: usize,
    },
    /// A node refers forward or outside the node list.
    ParentNodeNotBuilt {
        /// Node containing the invalid reference.
        node: usize,
        /// Requested parent index.
        parent: usize,
    },
    /// A node's vertex range lies outside the supplied vertex slice.
    VertexRangeOutOfBounds {
        /// Node containing the invalid range.
        node: usize,
        /// Invalid range.
        range: Range<usize>,
        /// Number of available vertices.
        vertex_count: usize,
    },
    /// A projection-copy pair contains an invalid vertex index.
    ProjectionCopyOutOfBounds {
        /// Copy pair's position in the copy list.
        copy: usize,
        /// Invalid source or destination index.
        vertex: usize,
        /// Number of available vertices.
        vertex_count: usize,
    },
}

impl Display for GeometryError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::RootOutOfRange {
                node,
                root,
                root_count,
            } => write!(
                formatter,
                "MANU3 node {node} refers to root {root}, but only {root_count} roots exist"
            ),
            Self::ParentNodeNotBuilt { node, parent } => write!(
                formatter,
                "MANU3 node {node} refers to unbuilt parent node {parent}"
            ),
            Self::VertexRangeOutOfBounds {
                node,
                range,
                vertex_count,
            } => write!(
                formatter,
                "MANU3 node {node} owns vertices {range:?}, outside {vertex_count} vertices"
            ),
            Self::ProjectionCopyOutOfBounds {
                copy,
                vertex,
                vertex_count,
            } => write!(
                formatter,
                "MANU3 projection copy {copy} refers to vertex {vertex}, outside {vertex_count} vertices"
            ),
        }
    }
}

impl Error for GeometryError {}

fn multiply_wrapping(left: i32, right: i32) -> i32 {
    (left as u32).wrapping_mul(right as u32) as i32
}

fn add_wrapping(left: i32, right: i32) -> i32 {
    (left as u32).wrapping_add(right as u32) as i32
}

fn subtract_wrapping(left: i32, right: i32) -> i32 {
    (left as u32).wrapping_sub(right as u32) as i32
}

fn rotation_matrix(angles: [u16; MATRIX_DIMENSION], table: &TrigonometryTable) -> Matrix3 {
    let angle_x = angles[X_AXIS] & ANGLE_MASK;
    let angle_y = angles[Y_AXIS] & ANGLE_MASK;
    let angle_z = angles[Z_AXIS] & ANGLE_MASK;
    let mut matrix = ZERO_MATRIX;

    matrix[Y_AXIS][Z_AXIS] = i32::from(table.lookup(angle_x).sine)
        .wrapping_mul(DOUBLE_SINE_SCALE)
        .wrapping_neg();

    let first = table.lookup(angle_x.wrapping_sub(angle_y).wrapping_sub(angle_z));
    let second = table.lookup(angle_x.wrapping_add(angle_y).wrapping_add(angle_z));
    let base = table.lookup(angle_y.wrapping_add(angle_z));
    let mut value_0 = subtract_wrapping(i32::from(first.cosine), i32::from(second.cosine));
    value_0 = add_wrapping(value_0 >> 1, i32::from(base.sine));
    let mut value_1 = add_wrapping(i32::from(first.sine), i32::from(second.sine));
    value_1 = add_wrapping(value_1 >> 1, i32::from(base.cosine));
    matrix[X_AXIS][Y_AXIS] = value_0;
    matrix[Z_AXIS][X_AXIS] = value_0.wrapping_neg();
    matrix[X_AXIS][X_AXIS] = value_1;
    matrix[Z_AXIS][Y_AXIS] = value_1;

    let first = table.lookup(angle_x.wrapping_sub(angle_y).wrapping_add(angle_z));
    let second = table.lookup(angle_x.wrapping_add(angle_y).wrapping_sub(angle_z));
    let base = table.lookup(angle_y.wrapping_sub(angle_z));
    let value_0 = subtract_wrapping(i32::from(first.cosine), i32::from(second.cosine)) >> 1;
    let value_1 = add_wrapping(i32::from(first.sine), i32::from(second.sine)) >> 1;
    let source_0 = subtract_wrapping(i32::from(base.sine), value_0);
    let source_1 = subtract_wrapping(i32::from(base.cosine), value_1);
    matrix[X_AXIS][Y_AXIS] = subtract_wrapping(matrix[X_AXIS][Y_AXIS], source_0);
    matrix[Z_AXIS][X_AXIS] = subtract_wrapping(matrix[Z_AXIS][X_AXIS], source_0);
    matrix[X_AXIS][X_AXIS] = add_wrapping(matrix[X_AXIS][X_AXIS], source_1);
    matrix[Z_AXIS][Y_AXIS] = subtract_wrapping(matrix[Z_AXIS][Y_AXIS], source_1);

    let first = table.lookup(angle_z.wrapping_add(angle_x));
    let second = table.lookup(angle_z.wrapping_sub(angle_x));
    matrix[Y_AXIS][Y_AXIS] = add_wrapping(i32::from(first.cosine), i32::from(second.cosine));
    matrix[Y_AXIS][X_AXIS] =
        add_wrapping(i32::from(first.sine), i32::from(second.sine)).wrapping_neg();

    let first = table.lookup(angle_y.wrapping_add(angle_x));
    let second = table.lookup(angle_y.wrapping_sub(angle_x));
    matrix[Z_AXIS][Z_AXIS] = add_wrapping(i32::from(first.cosine), i32::from(second.cosine));
    matrix[X_AXIS][Z_AXIS] = add_wrapping(i32::from(first.sine), i32::from(second.sine));
    matrix
}

/// Build local rotations and compose every node with its parent transform.
///
/// This translates `xdb_manu3_matrix_build` at MANU3 file offset `0x0270`.
/// Nodes must be topologically ordered when one node parents another.
pub fn build_projection_matrices(
    nodes: &mut [ProjectionNode],
    roots: &[Transform3],
    table: &TrigonometryTable,
) -> Result<Option<Matrix3>, GeometryError> {
    let mut final_rotation = None;
    for node_index in usize::MIN..nodes.len() {
        let parent = match nodes[node_index].parent {
            TransformParent::Root(root) => {
                roots
                    .get(root)
                    .copied()
                    .ok_or(GeometryError::RootOutOfRange {
                        node: node_index,
                        root,
                        root_count: roots.len(),
                    })?
            }
            TransformParent::Node(parent) if parent < node_index => nodes[parent].transform(),
            TransformParent::Node(parent) => {
                return Err(GeometryError::ParentNodeNotBuilt {
                    node: node_index,
                    parent,
                });
            }
        };
        let rotation = rotation_matrix(nodes[node_index].angles, table);
        let node = &mut nodes[node_index];

        let radial = i32::from(node.radial_offset);
        let radial_x =
            multiply_wrapping(rotation[X_AXIS][Z_AXIS], radial) >> POSITION_FRACTIONAL_BITS;
        node.local_position[X_AXIS] = add_wrapping(node.local_position[X_AXIS], radial_x);
        let radial_y_product = multiply_wrapping(rotation[Y_AXIS][Z_AXIS], radial);
        let radial_y_rounding =
            ((radial_y_product as u32 >> TRANSFORM_FRACTIONAL_BITS) & RADIAL_ROUNDING_BIT) as i32;
        let radial_y = add_wrapping(
            radial_y_product >> POSITION_FRACTIONAL_BITS,
            radial_y_rounding,
        );
        node.local_position[Y_AXIS] = add_wrapping(node.local_position[Y_AXIS], radial_y);
        let radial_z =
            multiply_wrapping(rotation[Z_AXIS][Z_AXIS], radial) >> POSITION_FRACTIONAL_BITS;
        node.local_position[Z_AXIS] = add_wrapping(node.local_position[Z_AXIS], radial_z);

        let local = node.local_position.map(|value| i32::from(value as i16));
        for (row, translation) in node.translation.iter_mut().enumerate() {
            let mut accumulator = SCREEN_ORIGIN;
            for (parent_component, local_component) in parent.matrix[row].iter().zip(local) {
                accumulator = add_wrapping(
                    accumulator,
                    multiply_wrapping(*parent_component, local_component),
                );
            }
            *translation = add_wrapping(accumulator, parent.translation[row]);
        }

        for (row, output_row) in node.matrix.iter_mut().enumerate() {
            for (column, output) in output_row.iter_mut().enumerate() {
                let mut accumulator = SCREEN_ORIGIN;
                for (parent_component, rotation_row) in parent.matrix[row].iter().zip(rotation) {
                    accumulator = add_wrapping(
                        accumulator,
                        multiply_wrapping(*parent_component, rotation_row[column]),
                    );
                }
                *output = accumulator >> TRANSFORM_FRACTIONAL_BITS;
            }
        }
        final_rotation = Some(rotation);
    }
    Ok(final_rotation)
}

fn transformed_component(transform: &Transform3, row: usize, position: Vector3) -> i32 {
    let mut accumulator = SCREEN_ORIGIN;
    for (matrix_component, position_component) in transform.matrix[row].iter().zip(position) {
        accumulator = add_wrapping(
            accumulator,
            multiply_wrapping(*matrix_component, position_component),
        );
    }
    add_wrapping(accumulator, transform.translation[row])
}

/// Project all node-owned vertices and apply explicit projection-copy pairs.
///
/// This translates `xdb_manu3_entity_project` at MANU3 file offset `0x0549`.
/// Empty ranges perform no work in the flat-memory port; the native routine's
/// zero-count 65,536-iteration pointer wrap is deliberately not reproduced.
pub fn project_entities(
    nodes: &[ProjectionNode],
    vertices: &mut [ModelVertex],
    projection_copies: &[ProjectionCopy],
    center: ProjectionCenter,
) -> Result<(), GeometryError> {
    for (node_index, node) in nodes.iter().enumerate() {
        if node.vertices.start > node.vertices.end || node.vertices.end > vertices.len() {
            return Err(GeometryError::VertexRangeOutOfBounds {
                node: node_index,
                range: node.vertices.clone(),
                vertex_count: vertices.len(),
            });
        }
        let transform = node.transform();
        for vertex in &mut vertices[node.vertices.clone()] {
            vertex.projected.clip_flags = ClipFlags::BEHIND_CAMERA;
            let position = vertex.position.map(i32::from);
            let depth =
                transformed_component(&transform, Z_AXIS, position) >> DEPTH_FRACTIONAL_BITS;
            vertex.projected.depth = depth;
            if depth <= PROJECTION_PLANE_DEPTH {
                continue;
            }

            let projected_x = transformed_component(&transform, X_AXIS, position) / depth;
            let projected_y =
                (transformed_component(&transform, Y_AXIS, position) / depth).wrapping_neg();
            let mut screen_x = add_wrapping(projected_x, center.x);
            let mut screen_y = add_wrapping(projected_y, center.y);
            let mut flags = ClipFlags::NONE;

            if screen_x < SCREEN_ORIGIN {
                flags.insert(ClipFlags::LEFT);
                if screen_x <= -HORIZONTAL_CLIP_LIMIT {
                    screen_x = LEFT_CLAMPED_POSITION;
                }
            }
            if screen_x >= SCREEN_WIDTH {
                flags.insert(ClipFlags::RIGHT);
                if screen_x >= RIGHT_CLAMP_THRESHOLD {
                    screen_x = RIGHT_CLAMPED_POSITION;
                }
            }
            if screen_y < SCREEN_ORIGIN {
                flags.insert(ClipFlags::TOP);
                if screen_y <= -VERTICAL_CLIP_LIMIT {
                    screen_y = TOP_CLAMPED_POSITION;
                }
            }
            if screen_y >= SCREEN_HEIGHT {
                flags.insert(ClipFlags::BOTTOM);
                if screen_y >= BOTTOM_CLAMP_THRESHOLD {
                    screen_y = BOTTOM_CLAMPED_POSITION;
                }
            }

            vertex.projected.clip_flags = flags;
            vertex.projected.screen = [screen_x as i16, screen_y as i16];
        }
    }

    for (copy_index, projection_copy) in projection_copies.iter().enumerate() {
        let source = vertices
            .get(projection_copy.source)
            .ok_or(GeometryError::ProjectionCopyOutOfBounds {
                copy: copy_index,
                vertex: projection_copy.source,
                vertex_count: vertices.len(),
            })?
            .projected;
        let vertex_count = vertices.len();
        let destination = vertices.get_mut(projection_copy.destination).ok_or(
            GeometryError::ProjectionCopyOutOfBounds {
                copy: copy_index,
                vertex: projection_copy.destination,
                vertex_count,
            },
        )?;
        destination.projected = source;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use serde::Deserialize;

    use super::*;

    const MATRIX_ORACLE_VECTOR_COUNT: usize = 7;
    const PROJECTION_ORACLE_VECTOR_COUNT: usize = 15;
    const ORIGINAL_ZERO_COUNT_ITERATIONS: usize = 65_536;
    const EMPTY_VERTEX_RANGE: Range<usize> = usize::MIN..usize::MIN;

    type ProjectionSpecification = (Matrix3, Vector3, Vec<[i16; MATRIX_DIMENSION]>);

    #[derive(Deserialize)]
    struct MatrixOracleVector {
        name: String,
        state_count: usize,
        final_rotation_matrix: Vec<i32>,
        states_after: Vec<MatrixStateAfter>,
    }

    #[derive(Deserialize)]
    struct MatrixStateAfter {
        matrix: Vec<i32>,
        translation: Vector3,
        local_position: Vector3,
    }

    #[derive(Deserialize)]
    struct ProjectionOracleVector {
        name: String,
        iterations: usize,
        projected_vertices: Vec<ProjectedVertexOracle>,
    }

    #[derive(Deserialize)]
    struct ProjectedVertexOracle {
        screen_x: i16,
        screen_y: i16,
        depth: i32,
        clip_flags: u16,
    }

    fn flatten_matrix(matrix: Matrix3) -> Vec<i32> {
        matrix.into_iter().flatten().collect()
    }

    fn signed_word(value: u32) -> i16 {
        value as u16 as i16
    }

    fn synthetic_trigonometry_table(case_index: usize) -> TrigonometryTable {
        const COSINE_INDEX_SCALE: u32 = 197;
        const COSINE_CASE_SCALE: u32 = 991;
        const COSINE_BIAS: u32 = 17;
        const SINE_INDEX_SCALE: u32 = 389;
        const SINE_CASE_SCALE: u32 = 577;
        const SINE_BIAS: u32 = 91;

        TrigonometryTable::new(std::array::from_fn(|index| TrigonometryPair {
            cosine: signed_word(
                (index as u32)
                    .wrapping_mul(COSINE_INDEX_SCALE)
                    .wrapping_add((case_index as u32).wrapping_mul(COSINE_CASE_SCALE))
                    .wrapping_add(COSINE_BIAS),
            ),
            sine: signed_word(
                (index as u32)
                    .wrapping_mul(SINE_INDEX_SCALE)
                    .wrapping_add((case_index as u32).wrapping_mul(SINE_CASE_SCALE))
                    .wrapping_add(SINE_BIAS),
            ),
        }))
    }

    fn root_transforms() -> [Transform3; 2] {
        const MATRIX_BASE: u32 = 0x1020_3040;
        const MATRIX_PARENT_SCALE: u32 = 0x1111_1111;
        const MATRIX_ROW_SCALE: u32 = 0x0102_0304;
        const MATRIX_COLUMN_SCALE: u32 = 0x0011_2233;
        const TRANSLATION_BASE: u32 = 0x7000_0000;
        const TRANSLATION_PARENT_SCALE: u32 = 0x0808_0808;
        const TRANSLATION_ROW_SCALE: u32 = 0x0123_4567;

        std::array::from_fn(|parent| Transform3 {
            matrix: std::array::from_fn(|row| {
                std::array::from_fn(|column| {
                    MATRIX_BASE
                        .wrapping_add((parent as u32).wrapping_mul(MATRIX_PARENT_SCALE))
                        .wrapping_add((row as u32).wrapping_mul(MATRIX_ROW_SCALE))
                        .wrapping_sub((column as u32).wrapping_mul(MATRIX_COLUMN_SCALE))
                        as i32
                })
            }),
            translation: std::array::from_fn(|row| {
                TRANSLATION_BASE
                    .wrapping_add((parent as u32).wrapping_mul(TRANSLATION_PARENT_SCALE))
                    .wrapping_add((row as u32).wrapping_mul(TRANSLATION_ROW_SCALE))
                    as i32
            }),
        })
    }

    fn matrix_case(name: &str) -> Vec<([u16; MATRIX_DIMENSION], i16)> {
        match name {
            "single_zero_angles" => vec![([0x0000, 0x0000, 0x0000], 0)],
            "single_mixed_angles" => vec![([0x0014, 0x02a0, 0x07fc], 1_234)],
            "angle_masking" => vec![([0xf013, 0xa2a3, 0x77ff], -2_222)],
            "negative_radial_extreme" => vec![([0x0ffc, 0x0800, 0x0400], i16::MIN)],
            "positive_radial_extreme" => vec![([0x0554, 0x0aa8, 0x0cc0], i16::MAX)],
            "two_state_hierarchy" => vec![
                ([0x0100, 0x0200, 0x0300], 511),
                ([0x0444, 0x0888, 0x0ccc], -777),
            ],
            "two_state_overflow" => vec![
                ([0x0ff8, 0x0004, 0x07fc], -1),
                ([0x0abc, 0x0120, 0x0f00], 1),
            ],
            unknown => panic!("unadapted MANU3 matrix oracle case {unknown}"),
        }
    }

    fn matrix_nodes(name: &str) -> Vec<ProjectionNode> {
        const LOCAL_POSITION_BASE: u32 = 0x7fff_0001;
        const LOCAL_POSITION_NODE_SCALE: u32 = 0x8080_8080;
        const LOCAL_POSITION_AXIS_SCALE: u32 = 0x1111_fffe;

        matrix_case(name)
            .into_iter()
            .enumerate()
            .map(|(node, (angles, radial_offset))| ProjectionNode {
                parent: if node == usize::MIN {
                    TransformParent::Root(usize::MIN)
                } else {
                    TransformParent::Node(node - 1)
                },
                vertices: EMPTY_VERTEX_RANGE,
                matrix: ZERO_MATRIX,
                translation: [SCREEN_ORIGIN; MATRIX_DIMENSION],
                local_position: std::array::from_fn(|axis| {
                    LOCAL_POSITION_BASE
                        .wrapping_add((node as u32).wrapping_mul(LOCAL_POSITION_NODE_SCALE))
                        .wrapping_add((axis as u32).wrapping_mul(LOCAL_POSITION_AXIS_SCALE))
                        as i32
                }),
                angles,
                radial_offset,
            })
            .collect()
    }

    #[test]
    fn matrix_builder_matches_all_complete_original_binary_states() {
        let vectors: Vec<MatrixOracleVector> = serde_json::from_str(include_str!(
            "../../../../../re/tools/oracle_vectors/xdb_manu3_func_0270_natural.json"
        ))
        .unwrap();
        assert_eq!(vectors.len(), MATRIX_ORACLE_VECTOR_COUNT);

        for (case_index, vector) in vectors.into_iter().enumerate() {
            let table = synthetic_trigonometry_table(case_index);
            let mut nodes = matrix_nodes(&vector.name);
            assert_eq!(nodes.len(), vector.state_count);
            let final_rotation = build_projection_matrices(&mut nodes, &root_transforms(), &table)
                .unwrap()
                .unwrap();
            assert_eq!(
                flatten_matrix(final_rotation),
                vector.final_rotation_matrix,
                "{}",
                vector.name
            );
            for (node, expected) in nodes.iter().zip(vector.states_after) {
                assert_eq!(
                    flatten_matrix(node.matrix),
                    expected.matrix,
                    "{}",
                    vector.name
                );
                assert_eq!(node.translation, expected.translation, "{}", vector.name);
                assert_eq!(
                    node.local_position, expected.local_position,
                    "{}",
                    vector.name
                );
            }
        }
    }

    fn projection_node(
        matrix: Matrix3,
        translation: Vector3,
        vertices: Range<usize>,
    ) -> ProjectionNode {
        ProjectionNode {
            parent: TransformParent::Root(usize::MIN),
            vertices,
            matrix,
            translation,
            local_position: [SCREEN_ORIGIN; MATRIX_DIMENSION],
            angles: [u16::MIN; MATRIX_DIMENSION],
            radial_offset: SCREEN_ORIGIN as i16,
        }
    }

    fn projection_fixture(
        vector: &ProjectionOracleVector,
    ) -> (ProjectionCenter, Vec<ProjectionNode>, Vec<ModelVertex>) {
        let (center, specifications): (ProjectionCenter, Vec<ProjectionSpecification>) =
            match vector.name.as_str() {
                "ordinary_centered" => (
                    ProjectionCenter { x: 10, y: 5 },
                    vec![(ZERO_MATRIX, [100, -50, 256], vec![[0, 0, 0]])],
                ),
                "zero_depth_rejected" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [20, 30, 0], vec![[1, 2, 3]])],
                ),
                "negative_depth_rejected" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [20, 30, -256], vec![[-1, -2, -3]])],
                ),
                "left_clip" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [-1, 0, 256], vec![[0, 0, 0]])],
                ),
                "left_clamp" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [-40, 0, 256], vec![[0, 0, 0]])],
                ),
                "right_clip" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [320, 0, 256], vec![[0, 0, 0]])],
                ),
                "right_clamp" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [360, 0, 256], vec![[0, 0, 0]])],
                ),
                "top_clip" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [0, 1, 256], vec![[0, 0, 0]])],
                ),
                "top_clamp" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [0, 100, 256], vec![[0, 0, 0]])],
                ),
                "bottom_clip" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [0, -200, 256], vec![[0, 0, 0]])],
                ),
                "bottom_clamp" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [0, -300, 256], vec![[0, 0, 0]])],
                ),
                "matrix_vertex_traversal" => (
                    ProjectionCenter::default(),
                    vec![(
                        [[1, 0, 0], [0, 1, 0], [0, 0, 0]],
                        [0, 0, 256],
                        vec![[10, -20, 7], [319, -199, -8], [-1, 1, 9]],
                    )],
                ),
                "two_projection_states" => (
                    ProjectionCenter { x: 3, y: 4 },
                    vec![
                        (ZERO_MATRIX, [7, -8, 256], vec![[0, 0, 0]]),
                        (ZERO_MATRIX, [34, -36, 512], vec![[0, 0, 0]]),
                    ],
                ),
                "copy_tail_two_vertices" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [0, 0, 0], vec![[0, 0, 0]])],
                ),
                "zero_vertex_count_wraps_65536_iterations" => (
                    ProjectionCenter::default(),
                    vec![(ZERO_MATRIX, [0, 0, -256], Vec::new())],
                ),
                unknown => panic!("unadapted MANU3 projection oracle case {unknown}"),
            };

        let mut nodes = Vec::with_capacity(specifications.len());
        let mut vertices = Vec::new();
        for (matrix, translation, positions) in specifications {
            let range_start = vertices.len();
            vertices.extend(positions.into_iter().map(|position| ModelVertex {
                position,
                ..ModelVertex::default()
            }));
            let range_end = vertices.len();
            nodes.push(projection_node(matrix, translation, range_start..range_end));
        }
        for (vertex, expected) in vertices.iter_mut().zip(&vector.projected_vertices) {
            vertex.projected.screen = [expected.screen_x, expected.screen_y];
        }
        (center, nodes, vertices)
    }

    #[test]
    fn entity_projection_matches_all_original_binary_semantic_cases() {
        let vectors: Vec<ProjectionOracleVector> = serde_json::from_str(include_str!(
            "../../../../../re/tools/oracle_vectors/xdb_manu3_func_0549_natural.json"
        ))
        .unwrap();
        assert_eq!(vectors.len(), PROJECTION_ORACLE_VECTOR_COUNT);

        for vector in vectors {
            let (center, nodes, mut vertices) = projection_fixture(&vector);
            if vector.name == "zero_vertex_count_wraps_65536_iterations" {
                assert_eq!(vector.iterations, ORIGINAL_ZERO_COUNT_ITERATIONS);
                let before = vertices.clone();
                project_entities(&nodes, &mut vertices, &[], center).unwrap();
                assert_eq!(vertices, before);
                continue;
            }

            project_entities(&nodes, &mut vertices, &[], center).unwrap();
            for (vertex, expected) in vertices.iter().zip(vector.projected_vertices) {
                assert_eq!(
                    vertex.projected.screen,
                    [expected.screen_x, expected.screen_y],
                    "{}",
                    vector.name
                );
                assert_eq!(vertex.projected.depth, expected.depth, "{}", vector.name);
                assert_eq!(
                    vertex.projected.clip_flags.bits(),
                    expected.clip_flags,
                    "{}",
                    vector.name
                );
            }
        }
    }

    #[test]
    fn projection_copies_use_typed_vertex_indices() {
        const SOURCE: usize = 0;
        const DESTINATION: usize = 1;
        const SOURCE_SCREEN: [i16; 2] = [123, -45];
        const SOURCE_DEPTH: i32 = 67_890;

        let source_projection = ProjectedVertex {
            screen: SOURCE_SCREEN,
            depth: SOURCE_DEPTH,
            clip_flags: ClipFlags::RIGHT,
        };
        let mut vertices = vec![
            ModelVertex {
                projected: source_projection,
                ..ModelVertex::default()
            },
            ModelVertex::default(),
        ];
        project_entities(
            &[],
            &mut vertices,
            &[ProjectionCopy {
                source: SOURCE,
                destination: DESTINATION,
            }],
            ProjectionCenter::default(),
        )
        .unwrap();
        assert_eq!(vertices[DESTINATION].projected, source_projection);
    }
}
